table Discipline
	lineageTag: 817a5a13-a5a3-46d5-b64f-233bbfad96ed

	column Prefix
		dataType: string
		lineageTag: fd5aca9b-78dd-4b81-85b6-8fb09034ca1f
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	column Discipline
		dataType: string
		lineageTag: 7e63062a-a6e7-4152-9d03-7b9f7cffa75a
		summarizeBy: none
		sourceColumn: Discipline

		annotation SummarizationSetBy = Automatic

	partition Discipline-81334040-e8b1-41f8-a52c-8b5ab0e43fab = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCnBW0lFyzUlNLinKTE7MUYrViVZyxiLmCRLzzCsuKSrNTc0rAYuFoIvFAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Prefix = _t, Discipline = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Prefix", type text}, {"Discipline", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

