table 'StaticTbl_PURPOSE SEQUENCE TABLE'
	lineageTag: a9c04654-a34e-4d68-9eb0-98d11f986a18

	column PURPOSE
		dataType: string
		lineageTag: dc7bd707-b27d-4a9b-86ec-5318c805e370
		summarizeBy: none
		sourceColumn: PURPOSE

		annotation SummarizationSetBy = Automatic

	column CODE
		dataType: int64
		formatString: 0
		lineageTag: dd707a09-2154-4991-9860-291a83756fe3
		summarizeBy: sum
		sourceColumn: CODE

		annotation SummarizationSetBy = Automatic

	partition 'StaticTbl_PURPOSE SEQUENCE TABLE-37e95a7c-ea73-44ef-b0ee-3eb49f8b48fa' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci4tUdJRMlSK1YlWcktMKspMTizJzM8DihmBxRyLi1Nzk3JSgQLGYAHPvOKSxJwcmCoTpdhYAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [PURPOSE = _t, CODE = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PURPOSE", type text}, {"CODE", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

