table StaticTbl_Project
	lineageTag: b58675a2-d1e0-48ca-beac-105be7f1bc6d

	column Project
		dataType: string
		lineageTag: a2bf3019-a611-4a20-b3c9-5f43af6aaf9b
		summarizeBy: none
		sourceColumn: Project

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: ed156f69-3f2d-4418-ad22-0253cc97f681
		summarizeBy: none
		sourceColumn: Code

		annotation SummarizationSetBy = Automatic

	partition StaticTbl_Project-9b9facaf-6f1f-4330-9516-f50013bd989b = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcjEzNzZS0lHyUIqNBQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Project = _t, Code = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Project", type text}, {"Code", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

