WITH SPCRPT_COMP_IOBJECT_PROP_TMP as
(
  
--Section #1b: Get IObject properties from SPF tables 
SELECT 
            COMPONENTITEM.OBID AS "COMPOBID",
            COMPONENTITEM.OBJUID AS "COMPUID",
            COMPONENTITEM.CONFIG AS "PROJECT"
-- sample: ,COMPONENTITEM.Property1 AS "Prop1"
      
FROM DATAOBJ COMPONENTITEM WHERE COMPONENTITEM.OBJDEFUID IN ('SPC_Spool') AND COMPONENTITEM.TERMINATIONDATE = '9999/12/31-23:59:59:999' ),


SPCRPT_WORKSTEP_IOBJ_PROP_TMP as (
SELECT
            COMPWORKSTEP.OBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP.OBJUID AS "COMPWORKSTEPUID",	  
            COMPWORKSTEP.CONFIG AS "PROJECT",
            COMPWORKSTEP.OBJNAME As "OBJNAME"
FROM DATAOBJ COMPWORKSTEP WHERE COMPWORKSTEP.OBJDEFUID = 'SPC_ComponentWorkTypeStep' AND COMPWORKSTEP.TERMINATIONDATE = '9999/12/31-23:59:59:999'),

SPCRPT_WORKSTEP_REL_PROP_TMP as (
SELECT
            COMPWORKSTEP.COMPWORKSTEPOBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP_WORKTYPE_COSTCODE.STRVALUE AS "COSTCODE",
            COMPWORKSTEP_FIWP.OBID AS "FIWPOBID",	
            COMPWORKSTEP_WORKTYPE.OBID AS "WORKTYPEOBID",
            COMPWORKSTEP.OBJNAME As "WORKSTEP",
            COMPWORKSTEP_COMP.OBID AS "COMPOBID",
            FIWP.OBJUID AS "FIWPUID",
            FIWP.OBJNAME as "WORKPACKNO",
            FIWP.DESCRIPTION as "WPDESCRIPTION",
            FIWP_DESIGNAREA.STRVALUE AS "JOBNO",
            CAST(COMPWORKSTEP_PLANNEDMANHOURS.STRVALUE AS FLOAT) AS "PLANNEDMANHOURS",
            CAST(COMPWORKSTEP_ACTUALMANHOURS.STRVALUE AS FLOAT) AS "ACTUALMANHOURS",
            COMPWORKSTEP_DATECOMPLETE.STRVALUE AS "ACTUALDATECOMPLETE",
            CAST(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE AS FLOAT) AS "QUANTITYCOMPLETE"
FROM SPCRPT_WORKSTEP_IOBJ_PROP_TMP COMPWORKSTEP
	LEFT JOIN DATAREL COMPWORKSTEP_FIWP_REL ON COMPWORKSTEP_FIWP_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID  AND COMPWORKSTEP_FIWP_REL.DEFUID = 'SPC_Package_ComponentWorkTypeStep' AND COMPWORKSTEP_FIWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_FIWP ON COMPWORKSTEP_FIWP.OBJUID = COMPWORKSTEP_FIWP_REL.UID1 AND COMPWORKSTEP_FIWP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL COMPWORKSTEP_WORKTYPE_REL ON COMPWORKSTEP_WORKTYPE_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID AND COMPWORKSTEP_WORKTYPE_REL.DEFUID = 'SPC_ComponentWorkType_ComponentWorkTypeSteps' AND COMPWORKSTEP_WORKTYPE_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_WORKTYPE ON COMPWORKSTEP_WORKTYPE.OBJUID = COMPWORKSTEP_WORKTYPE_REL.UID1 AND COMPWORKSTEP_WORKTYPE.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_WORKTYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_WORKTYPE_COSTCODE ON COMPWORKSTEP_WORKTYPE_COSTCODE.OBJOBID = COMPWORKSTEP_WORKTYPE.OBID AND COMPWORKSTEP_WORKTYPE_COSTCODE.PROPERTYDEFUID = 'ComponentWorkType_CostCode' AND COMPWORKSTEP_WORKTYPE_COSTCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL COMPWORKSTEP_COMP_REL ON COMPWORKSTEP_COMP_REL.UID2 = COMPWORKSTEP_WORKTYPE.OBJUID AND COMPWORKSTEP_COMP_REL.DEFUID = 'SPC_ComponentItem_ComponentWorkType' AND COMPWORKSTEP_COMP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_COMP ON COMPWORKSTEP_COMP.OBJUID = COMPWORKSTEP_COMP_REL.UID1 AND COMPWORKSTEP_COMP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_COMP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP ON FIWP.OBID = COMPWORKSTEP_FIWP.OBID  AND FIWP.OBJDEFUID = 'SPC_FIWP'  AND COMPWORKSTEP_COMP.TERMINATIONDATE = '9999/12/31-23:59:59:999'

--Design Area

	LEFT JOIN DATAREL FIWP_DESIGNAREA_REL ON FIWP_DESIGNAREA_REL.UID2 = FIWP.OBJUID AND FIWP_DESIGNAREA_REL.DEFUID = 'SPC_FunctionalArea_FIWPs' AND FIWP_DESIGNAREA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_DESIGNAREA_OBJ ON FIWP_DESIGNAREA_OBJ.OBJUID = FIWP_DESIGNAREA_REL.UID1 AND FIWP_DESIGNAREA_OBJ.CONFIG = FIWP.CONFIG AND FIWP_DESIGNAREA_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_DESIGNAREA ON FIWP_DESIGNAREA.OBJOBID = FIWP_DESIGNAREA_OBJ.OBID AND FIWP_DESIGNAREA.PROPERTYDEFUID = 'Name' AND FIWP_DESIGNAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  --PLANNEDMANHOURS
  LEFT JOIN DATAOBJPR COMPWORKSTEP_PLANNEDMANHOURS ON COMPWORKSTEP_PLANNEDMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_PLANNEDMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ManHours' AND COMPWORKSTEP_PLANNEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPWORKSTEP_ACTUALMANHOURS ON COMPWORKSTEP_ACTUALMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_ACTUALMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualHours' AND COMPWORKSTEP_ACTUALMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_DATECOMPLETE ON COMPWORKSTEP_DATECOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_DATECOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualDateComplete' AND COMPWORKSTEP_DATECOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_QUANTITYCOMPLETE ON COMPWORKSTEP_QUANTITYCOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_QUANTITYCOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_QuantityComplete' AND COMPWORKSTEP_QUANTITYCOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
),

-- Section #2a: Columns for Direct properties
SPCRPT_COMP_DIRECT_PROP_TMP as 
(
-- Section #2b: Get Direct properties from SPF tables 
SELECT 
            COMPONENTITEM.COMPOBID AS "COMPOBID",
            COMPONENTITEM_NAME.STRVALUE AS "NAME", 
            
            COMPONENTITEM_MATERIAL.STRVALUE AS "MATERIAL",	   
            COMPONENTITEM_INSTALLLOCATION.STRVALUE AS "INSTALLLOCATION",	   
            CAST(COMPONENTITEM_SIZE.STRVALUE AS FLOAT) AS "COMPSIZE",
			COMPONENTITEM_LINENUMBER.STRVALUE as "LINENUMBER", 
			COMPONENTITEM_DECKLEVEL.STRVALUE as "DECKLEVEL", 
            COMPONENTITEM_DRAWINGNO.STRVALUE as "DRAWINGNO",
			COMPONENTITEM_MATERIALSTATUS.STRVALUE as "MATERIALSTATUS",
            COMPONENTITEM_WELDDIA.STRVALUE as "WELDDIA",
			COMPONENTITEM_PMC.STRVALUE as "PMC",
			COMPONENTITEM_FWDIA.STRVALUE AS "FIELDWELDDIA",
			COMPONENTITEM_SAREA.STRVALUE AS "SURFACEAREA",
			COMPONENTITEM_REVISION.STRVALUE AS "REVISION",
			COMPONENTITEM_TRANSMITTAL.STRVALUE AS "TRANSMITTAL",
			COMPONENTITEM_PAINT.STRVALUE AS "PAINTSYSTEM",
			COMPONENTITEM_TESTPACK.STRVALUE AS "TESTPACK",
			COMPONENTITEM_TOPCOAT.STRVALUE as "TOPCOAT",
			COMPONENTITEM_WEIGHT.STRVALUE AS "WEIGHT",
			COMPONENTITEM_SPOOLSIZE.STRVALUE As "SPOOLSIZE",
			COMPONENTITEM_EQUIVDIA.STRVALUE As "EQUIVDIA",	
			COMPONENTITEM_EQUIVFIELDDIA.STRVALUE As "EQUIVFIELDDIA",		
			COMPONENTITEM_DELIVERYSEQNO.STRVALUE AS "DELIVERYSEQNO",
			COMPONENTITEM_DELIVERYDATE.STRVALUE AS "DELIVERYDATE",
			COMPONENTITEM_DELIVERYSEQNOPAINT.STRVALUE AS "DELIVERYSEQNOPAINT",
			COMPONENTITEM_DELIVERYDATEPAINT.STRVALUE AS "DELIVERYDATEPAINT",			
            COMPONENTITEM_PWHT.STRVALUE AS "PWHT"

-- sample: ,Property2.STRVALUE AS "Prop2"
      
FROM SPCRPT_COMP_IOBJECT_PROP_TMP COMPONENTITEM

--Section #2c: Join SPF tables to get Direct Properties 

--#region " Direct Properties "

	--Name
	LEFT JOIN DATAOBJPR COMPONENTITEM_NAME ON COMPONENTITEM_NAME.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_NAME.PROPERTYDEFUID = 'Name' AND COMPONENTITEM_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	
	--Material
	LEFT JOIN DATAOBJPR COMPONENTITEM_MATERIAL ON COMPONENTITEM_MATERIAL.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_MATERIAL.PROPERTYDEFUID = 'SPC_ComponentItem_Material' AND COMPONENTITEM_MATERIAL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	

	--Size
	LEFT JOIN DATAOBJPR COMPONENTITEM_SIZE ON COMPONENTITEM_SIZE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_SIZE.PROPERTYDEFUID = 'SPC_ComponentItem_Size' AND COMPONENTITEM_SIZE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	
	--Line Number
	LEFT JOIN DATAOBJPR COMPONENTITEM_LINENUMBER ON COMPONENTITEM_LINENUMBER.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_LINENUMBER.PROPERTYDEFUID = 'SPC_CustomLineNumber' AND COMPONENTITEM_LINENUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  --InstallLocation
	LEFT JOIN DATAOBJPR COMPONENTITEM_INSTALLLOCATION ON COMPONENTITEM_INSTALLLOCATION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_INSTALLLOCATION.PROPERTYDEFUID = 'SPC_CustomInstallLocation' AND COMPONENTITEM_INSTALLLOCATION.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--Deck Level
	LEFT JOIN DATAOBJPR COMPONENTITEM_DECKLEVEL ON COMPONENTITEM_DECKLEVEL.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DECKLEVEL.PROPERTYDEFUID = 'SPC_ComponentItem_DeckLevel' AND COMPONENTITEM_DECKLEVEL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--Drawing Number
	LEFT JOIN DATAOBJPR COMPONENTITEM_DRAWINGNO ON COMPONENTITEM_DRAWINGNO.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DRAWINGNO.PROPERTYDEFUID = 'SPC_FabricationDrawing' AND COMPONENTITEM_DRAWINGNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  --Piping Material Class -PMC
  LEFT JOIN DATAOBJPR COMPONENTITEM_PMC ON COMPONENTITEM_PMC.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_PMC.PROPERTYDEFUID = 'SPC_ComponentItem_PMC' AND COMPONENTITEM_PMC.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  --- MDR PROPS--- 
  
	--WeldDiaMetter
  	LEFT JOIN DATAOBJPR COMPONENTITEM_WELDDIA ON COMPONENTITEM_WELDDIA.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_WELDDIA.PROPERTYDEFUID = 'MDR_Spool_WeldDiameter' AND COMPONENTITEM_WELDDIA.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
	--Surface area
  	LEFT JOIN DATAOBJPR COMPONENTITEM_SAREA ON COMPONENTITEM_SAREA.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_SAREA.PROPERTYDEFUID = 'MDR_SurfaceArea' AND COMPONENTITEM_SAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--FieldweldDia
  	LEFT JOIN DATAOBJPR COMPONENTITEM_FWDIA ON COMPONENTITEM_FWDIA.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_FWDIA.PROPERTYDEFUID = 'MDR_FieldWeldDia' AND COMPONENTITEM_FWDIA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--Material Status
  	LEFT JOIN DATAOBJPR COMPONENTITEM_MATERIALSTATUS ON COMPONENTITEM_MATERIALSTATUS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_MATERIALSTATUS.PROPERTYDEFUID = 'MaterialStatus' AND COMPONENTITEM_MATERIALSTATUS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
   
   	--Revision
  	LEFT JOIN DATAOBJPR COMPONENTITEM_REVISION ON COMPONENTITEM_REVISION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_REVISION.PROPERTYDEFUID = 'MDR_IDOCS_DrawingRevision' AND COMPONENTITEM_REVISION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
   
    	--Transmittal
  	LEFT JOIN DATAOBJPR COMPONENTITEM_TRANSMITTAL ON COMPONENTITEM_TRANSMITTAL.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_TRANSMITTAL.PROPERTYDEFUID = 'MDR_IDOCS_TransmittalNo' AND COMPONENTITEM_TRANSMITTAL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
   
	--Paint Systems
  	LEFT JOIN DATAOBJPR COMPONENTITEM_PAINT ON COMPONENTITEM_PAINT.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_PAINT.PROPERTYDEFUID = 'MDR_CustomPaintSystem' AND COMPONENTITEM_PAINT.TERMINATIONDATE = '9999/12/31-23:59:59:999'     
	
	--TestPack
  	LEFT JOIN DATAOBJPR COMPONENTITEM_TESTPACK ON COMPONENTITEM_TESTPACK.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_TESTPACK.PROPERTYDEFUID = 'MDR_TestPackNo' AND COMPONENTITEM_TESTPACK.TERMINATIONDATE = '9999/12/31-23:59:59:999' 
	
	--TopCoat
  	LEFT JOIN DATAOBJPR COMPONENTITEM_TOPCOAT ON COMPONENTITEM_TOPCOAT.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_TOPCOAT.PROPERTYDEFUID = 'MDR_PaintTopCoat' AND COMPONENTITEM_TOPCOAT.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
	--Size
  	LEFT JOIN DATAOBJPR COMPONENTITEM_SPOOLSIZE ON COMPONENTITEM_SPOOLSIZE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_SPOOLSIZE.PROPERTYDEFUID = 'SPC_ComponentItem_Size' AND  COMPONENTITEM_SPOOLSIZE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--EQUIVDIA
	 LEFT JOIN DATAOBJPR COMPONENTITEM_EQUIVDIA ON COMPONENTITEM_EQUIVDIA.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_EQUIVDIA.PROPERTYDEFUID = 'MDR_Spool_EquiDiaInch' AND  COMPONENTITEM_EQUIVDIA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--EQUIVFIELDDIA
	 LEFT JOIN DATAOBJPR COMPONENTITEM_EQUIVFIELDDIA ON COMPONENTITEM_EQUIVFIELDDIA.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_EQUIVFIELDDIA.PROPERTYDEFUID = 'MDR_Spool_EquiDiaInch_Field' AND  COMPONENTITEM_EQUIVFIELDDIA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--Component Item Weight
  	LEFT JOIN DATAOBJPR COMPONENTITEM_WEIGHT ON COMPONENTITEM_WEIGHT.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_WEIGHT.PROPERTYDEFUID = 'SPC_ComponentItem_Weight' AND  COMPONENTITEM_WEIGHT.TERMINATIONDATE = '9999/12/31-23:59:59:999'

		--MDR_DeliverySeqNo
  	LEFT JOIN DATAOBJPR COMPONENTITEM_DELIVERYSEQNO ON COMPONENTITEM_DELIVERYSEQNO.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DELIVERYSEQNO.PROPERTYDEFUID = 'MDR_DeliverySeqNo' AND COMPONENTITEM_DELIVERYSEQNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'     
		--MDR_DeliveryDate
  	LEFT JOIN DATAOBJPR COMPONENTITEM_DELIVERYDATE ON COMPONENTITEM_DELIVERYDATE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DELIVERYDATE.PROPERTYDEFUID = 'MDR_DeliveryDate' AND COMPONENTITEM_DELIVERYDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'     
		--MDR_DeliverySeqNo_Paint
  	LEFT JOIN DATAOBJPR COMPONENTITEM_DELIVERYSEQNOPAINT ON COMPONENTITEM_DELIVERYSEQNOPAINT.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DELIVERYSEQNOPAINT.PROPERTYDEFUID = 'MDR_DeliverySeqNo_Paint' AND COMPONENTITEM_DELIVERYSEQNOPAINT.TERMINATIONDATE = '9999/12/31-23:59:59:999'     
		--MDR_DeliveryDate_Paint
  	LEFT JOIN DATAOBJPR COMPONENTITEM_DELIVERYDATEPAINT ON COMPONENTITEM_DELIVERYDATEPAINT.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DELIVERYDATEPAINT.PROPERTYDEFUID = 'MDR_DeliveryDate_Paint' AND COMPONENTITEM_DELIVERYDATEPAINT.TERMINATIONDATE = '9999/12/31-23:59:59:999'  

	--MDR_PWHT
  	LEFT JOIN DATAOBJPR COMPONENTITEM_PWHT ON COMPONENTITEM_PWHT.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_PWHT.PROPERTYDEFUID = 'MDR_PWHT' AND COMPONENTITEM_PWHT.TERMINATIONDATE = '9999/12/31-23:59:59:999'

where SUBSTRING(COMPONENTITEM_NAME.STRVALUE,5,1) in('A','F','H','J','U','V','Y','P','W') And 
SUBSTRING(COMPONENTITEM_NAME.STRVALUE,4,1) IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'T') And 
SUBSTRING(COMPONENTITEM_NAME.STRVALUE,2,1) IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'J', 'K', 'L','M', 'N', 'Q', 'R', 'S', 'H', 'P', 'V') And 
SUBSTRING(COMPONENTITEM_NAME.STRVALUE,1,1) IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K')
	)


--Section #4: Join temp tables to get data for report table
SELECT
     
	    --t1.COMPOBID, COMPUID
	   PROJECT,-- sample: Prop1Column,

	    NAME, LINENUMBER,COMPSIZE,DRAWINGNO,MATERIAL,DECKLEVEL,PMC,WELDDIA, WEIGHT, SPOOLSIZE, EQUIVDIA, EQUIVFIELDDIA,TOPCOAT, INSTALLLOCATION,FIELDWELDDIA,SURFACEAREA,JOBNO,REVISION,TRANSMITTAL, PAINTSYSTEM, TESTPACK, DELIVERYSEQNO, DELIVERYDATE, DELIVERYSEQNOPAINT, DELIVERYDATEPAINT
--,WORKPACKNO
,PWHT
FROM SPCRPT_COMP_IOBJECT_PROP_TMP t1
LEFT JOIN SPCRPT_COMP_DIRECT_PROP_TMP t2 ON t2.COMPOBID = t1.COMPOBID
--LEFT JOIN SPCRPT_WORKSTEP_REL_PROP_TMP t3 ON t3.COMPOBID = t1.COMPOBID
LEFT JOIN 
  (
    SELECT * from SPCRPT_WORKSTEP_REL_PROP_TMP  WHERE jobNo is not null
  )
  t3 ON t3.COMPOBID = t1.COMPOBID

Where Name Not Like '%Spool%'
--SUBSTRING(Name,1,1) In ('C') And Name Not Like '%Spool%'
Group By  PROJECT,

	    NAME, LINENUMBER,COMPSIZE,DRAWINGNO,MATERIAL,DECKLEVEL,PMC,WELDDIA, WEIGHT, SPOOLSIZE, EQUIVDIA,EQUIVFIELDDIA, TOPCOAT, INSTALLLOCATION,FIELDWELDDIA,SURFACEAREA,JOBNO,REVISION,TRANSMITTAL, PAINTSYSTEM, TESTPACK, DELIVERYSEQNO, DELIVERYDATE, DELIVERYSEQNOPAINT, DELIVERYDATEPAINT,PWHT
--,WORKPACKNO
