WITH SPCRPT_CWP_IOBJECT_PROP_TMP AS
(
 
SELECT 
            CWP.OBID AS "CWPOBID",
            CWP.OBJUID AS "CWPUID",
            CWP.CONFIG AS "PROJECT" 
-- sample: ,CWP.Property1 AS "Prop1"

FROM DATAOBJ CWP WHERE CWP.OBJDEFUID = 'SPC_CWP' AND CWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
),

-- Section #2a: Columns for Direct properties
SPCRPT_CWP_DIRECT_PROP_TMP AS
(

SELECT 
            CWP.CWPOBID AS "CWPOBID",
            CWP_NAME.STRVALUE AS "NAME", 
            CWP_DESCRIPTION.STRVALUE AS "DESCRIPTION",	 
            CWP_EWPNUMBER.STRVALUE AS "EWPNUMBER",
            CAST(CWP_BUDGETEDLABORHOURS.STRVALUE AS FLOAT) AS "BUDGETEDLABORHOURS",
            CONVERT(datetime,CWP_PLANNEDSTARTDATE.STRVALUE) AS "PLANNEDSTARTDATE",
            CONVERT(datetime,CWP_PLANNEDFINISHDATE.STRVALUE) AS "PLANNEDFINISHDATE",
            CONVERT(datetime,CWP_ACTUALSTARTDATE.STRVALUE) AS "ACTUALSTARTDATE",
            CONVERT(datetime,CWP_ACTUALFINISHDATE.STRVALUE) AS "ACTUALFINISHDATE",
            CONVERT(datetime,CWP_EARLYSTARTDATE.STRVALUE) AS "EARLYSTARTDATE",
            CONVERT(datetime,CWP_EARLYFINISHDATE.STRVALUE) AS "EARLYFINISHDATE",
            CONVERT(datetime,CWP_LATESTARTDATE.STRVALUE) AS "LATESTARTDATE",
            CONVERT(datetime,CWP_LATEFINISHDATE.STRVALUE) AS "LATEFINISHDATE",
            CWP_WBSPATH.STRVALUE AS "WBSPATH"
-- sample: ,Property2.STRVALUE AS "Prop2"

FROM SPCRPT_CWP_IOBJECT_PROP_TMP CWP

--Section #2c: Join SPF tables to get Direct Properties 

--#region " Direct Properties "

	--NAME
	LEFT JOIN DATAOBJPR CWP_NAME ON CWP_NAME.OBJOBID = CWP.CWPOBID AND CWP_NAME.PROPERTYDEFUID = 'Name' AND CWP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--DESCRIPTION
	LEFT JOIN DATAOBJPR CWP_DESCRIPTION ON CWP_DESCRIPTION.OBJOBID = CWP.CWPOBID AND CWP_DESCRIPTION.PROPERTYDEFUID = 'Description' AND CWP_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--EWPNUMBER
	LEFT JOIN DATAOBJPR CWP_EWPNUMBER ON CWP_EWPNUMBER.OBJOBID = CWP.CWPOBID AND CWP_EWPNUMBER.PROPERTYDEFUID = 'CWP_EWP_Number' AND CWP_EWPNUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--BUDGETEDLABORHOURS
	LEFT JOIN DATAOBJPR CWP_BUDGETEDLABORHOURS ON CWP_BUDGETEDLABORHOURS.OBJOBID = CWP.CWPOBID AND CWP_BUDGETEDLABORHOURS.PROPERTYDEFUID = 'CWP_BudgetedLaborHours' AND CWP_BUDGETEDLABORHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--PLANNEDSTARTDATE
	LEFT JOIN DATAOBJPR CWP_PLANNEDSTARTDATE ON CWP_PLANNEDSTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_PLANNEDSTARTDATE.PROPERTYDEFUID = 'CWP_PlannedStartDate' AND CWP_PLANNEDSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--PLANNEDFINISHDATE
	LEFT JOIN DATAOBJPR CWP_PLANNEDFINISHDATE ON CWP_PLANNEDFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_PLANNEDFINISHDATE.PROPERTYDEFUID = 'CWP_PlannedFinishDate' AND CWP_PLANNEDFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--ACTUALSTARTDATE
	LEFT JOIN DATAOBJPR CWP_ACTUALSTARTDATE ON CWP_ACTUALSTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_ACTUALSTARTDATE.PROPERTYDEFUID = 'CWP_ActualStartDate' AND CWP_ACTUALSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--ACTUALFINISHDATE
	LEFT JOIN DATAOBJPR CWP_ACTUALFINISHDATE ON CWP_ACTUALFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_ACTUALFINISHDATE.PROPERTYDEFUID = 'CWP_ActualFinishDate' AND CWP_ACTUALFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--EARLYSTARTDATE
	LEFT JOIN DATAOBJPR CWP_EARLYSTARTDATE ON CWP_EARLYSTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_EARLYSTARTDATE.PROPERTYDEFUID = 'CWP_EarlyStartDate' AND CWP_EARLYSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--EARLYFINISHDATE
	LEFT JOIN DATAOBJPR CWP_EARLYFINISHDATE ON CWP_EARLYFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_EARLYFINISHDATE.PROPERTYDEFUID = 'CWP_EarlyFinishDate' AND CWP_EARLYFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
		
	--LATESTARTDATE
	LEFT JOIN DATAOBJPR CWP_LATESTARTDATE ON CWP_LATESTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_LATESTARTDATE.PROPERTYDEFUID = 'CWP_LateStartDate' AND CWP_LATESTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--LATEFINISHDATE
	LEFT JOIN DATAOBJPR CWP_LATEFINISHDATE ON CWP_LATEFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_LATEFINISHDATE.PROPERTYDEFUID = 'CWP_LateFinishDate' AND CWP_LATEFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--WBSPATH
	LEFT JOIN DATAOBJPR CWP_WBSPATH ON CWP_WBSPATH.OBJOBID = CWP.CWPOBID AND CWP_WBSPATH.PROPERTYDEFUID = 'CWP_WBSPath' AND CWP_WBSPATH.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  ---- sample:
	--LEFT JOIN DATAOBJPR Property2 ON Property2.OBJOBID = FIWP.FIWPOBID AND Property2.PROPERTYDEFUID = '<PROPERTYDEFUID>' AND Property2.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	  
--#endregion " Direct Properties "
),

SPCRPT_CWP_DIR_ENUM_PROP_TMP AS
(
SELECT 
            CWP.CWPOBID AS "CWPOBID",
            CWP_DISCIPLINE.OBJNAME AS "DISCIPLINE"
            
-- sample: ,Property3.OBJNAME AS Prop3
      
FROM SPCRPT_CWP_IOBJECT_PROP_TMP CWP

-- Section #3c: Join SPF tables to Direct Properties (Enum Type)

--#region " Direct Properties with Enum Type "
	
	--CWP Discipline
	LEFT JOIN DATAOBJPR CWP_DISCIPLINE_PR ON CWP_DISCIPLINE_PR.OBJOBID = CWP.CWPOBID AND CWP_DISCIPLINE_PR.PROPERTYDEFUID = 'CWP_Discipline' AND CWP_DISCIPLINE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ CWP_DISCIPLINE ON CWP_DISCIPLINE.OBJUID = CWP_DISCIPLINE_PR.STRVALUE AND CWP_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  ---- sample:																																			 
	-- LEFT JOIN DATAOBJPR Property3_PR ON Property3_PR.OBJOBID = CWP.CWPOBID AND Property3_PR.PROPERTYDEFUID = '<PROPERTYDEFUID>' AND Property3_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	-- LEFT JOIN SCHEMAOBJ Property3 ON Property3.OBJUID = Prop3_PR.STRVALUE AND Property3.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
--#endregion " Direct Properties Enum Type "
),

-- Section #4a: Columns for Properties from related objects
SPCRPT_CWP_REL_PROP_TMP AS
(

SELECT
            CWP.CWPOBID AS "CWPOBID",
            CWP_DESIGNAREA.STRVALUE AS "DESIGNAREA",
            CWP_CWA.OBID AS "CWAOBID"
-- sample: ,Property4.STRVALUE AS "Prop4"

FROM SPCRPT_CWP_IOBJECT_PROP_TMP CWP

-- Section #4c: Join SPF tables to get Properties from related objects	

--#region " Relationship other end properties "

	--Design Area
	LEFT JOIN DATAREL CWP_DESIGNAREA_REL ON CWP_DESIGNAREA_REL.UID2 = CWP.CWPUID AND CWP_DESIGNAREA_REL.DEFUID = 'SPC_FunctionalArea_CWP' AND CWP_DESIGNAREA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ CWP_DESIGNAREA_OBJ ON CWP_DESIGNAREA_OBJ.OBJUID = CWP_DESIGNAREA_REL.UID1 AND CWP_DESIGNAREA_OBJ.CONFIG = CWP.PROJECT AND CWP_DESIGNAREA_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR CWP_DESIGNAREA ON CWP_DESIGNAREA.OBJOBID = CWP_DESIGNAREA_OBJ.OBID AND CWP_DESIGNAREA.PROPERTYDEFUID = 'Name' AND CWP_DESIGNAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--CWAs
	LEFT JOIN DATAREL CWP_CWA_REL ON CWP_CWA_REL.UID2 = CWP.CWPUID  AND CWP_CWA_REL.DEFUID = 'SPC_CWA_CWPs' AND CWP_CWA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ CWP_CWA ON CWP_CWA.OBJUID = CWP_CWA_REL.UID1 AND CWP_CWA.CONFIG = CWP.PROJECT AND CWP_CWA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  ---- sample:
	-- LEFT JOIN DATAREL Property4_REL ON Property4_REL.UID1 = CWP.CWPUID AND Property4_REL.DEFUID = '<RELDEFUID>' AND Property4_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	-- LEFT JOIN DATAOBJ Property4_OBJ ON Property4_OBJ.OBJUID = Property4_REL.UID2 AND Property4_OBJ.CONFIG = CWP.PROJECT AND Property4_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	-- LEFT JOIN DATAOBJPR Property4 ON Property4.OBJOBID = Property4_OBJ.OBID AND Property4.PROPERTYDEFUID = '<PROPERTYDEFUID>' AND Property4.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
--#endregion " Relationship other end properties "
),

SPCCWP AS 
(

SELECT
    -- Section #6a: IObject properties
	  t1.CWPOBID, CWPUID, PROJECT, -- sample: Prop1Column,
    -- Section #6b: Direct properties 
        
    NAME, DESCRIPTION, EWPNUMBER, BUDGETEDLABORHOURS, 
    PLANNEDSTARTDATE, 
    PLANNEDFINISHDATE, 
    ACTUALSTARTDATE, 
    ACTUALFINISHDATE, 
    EARLYSTARTDATE,	
    EARLYFINISHDATE, 
    LATESTARTDATE, 
    LATEFINISHDATE,	
    
    WBSPATH, -- sample: Prop2Column,
	  -- Section #6c: Direct properties (Enum type)			 
    DISCIPLINE, -- sample: Prop3Column,
    -- Section #6d: Properties from related objects	 
    DESIGNAREA, CWAOBID -- sample: ,Prop4Column	  
FROM SPCRPT_CWP_IOBJECT_PROP_TMP t1
LEFT JOIN SPCRPT_CWP_DIRECT_PROP_TMP t2 ON t2.CWPOBID = t1.CWPOBID
LEFT JOIN SPCRPT_CWP_DIR_ENUM_PROP_TMP t3 ON t3.CWPOBID = t1.CWPOBID
LEFT JOIN SPCRPT_CWP_REL_PROP_TMP t4 ON t4.CWPOBID = t1.CWPOBID
),
SPCRPT_WORKSTEP_IOBJ_PROP_TMP as (
SELECT
            COMPWORKSTEP.OBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP.OBJUID AS "COMPWORKSTEPUID",	  
            COMPWORKSTEP.CONFIG AS "PROJECT"
FROM DATAOBJ COMPWORKSTEP WHERE COMPWORKSTEP.OBJDEFUID = 'SPC_ComponentWorkTypeStep' AND COMPWORKSTEP.TERMINATIONDATE = '9999/12/31-23:59:59:999'),

SPCRPT_WORKSTEP_DIR_PROP_TMP as (
SELECT
            COMPWORKSTEP.COMPWORKSTEPOBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP_NAME.STRVALUE AS "NAME", 
            COMPWORKSTEP_DESCRIPTION.STRVALUE AS "DESCRIPTION",
            CAST(COMPWORKSTEP_SEQUENCE.STRVALUE AS INT) AS "SEQUENCE",
            CAST(COMPWORKSTEP_UNITRATE.STRVALUE AS FLOAT) AS "UNITRATE",
            COMPWORKSTEP_RATEUOM.STRVALUE AS "RATEUOM",
            COMPWORKSTEP_NOTES.STRVALUE AS "NOTES",
            CAST(COMPWORKSTEP_PLANNEDMANHOURS.STRVALUE AS FLOAT) AS "PLANNEDMANHOURS",
            CAST(COMPWORKSTEP_ACTUALMANHOURS.STRVALUE AS FLOAT) AS "ACTUALMANHOURS",
            COMPWORKSTEP_DATECOMPLETE.STRVALUE AS "ACTUALDATECOMPLETE",
            CAST(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE AS FLOAT) AS "QUANTITYCOMPLETE",
            COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONDATE,
            COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONUSER 
            
FROM SPCRPT_WORKSTEP_IOBJ_PROP_TMP COMPWORKSTEP
	LEFT JOIN DATAOBJPR COMPWORKSTEP_NAME ON COMPWORKSTEP_NAME.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_NAME.PROPERTYDEFUID = 'Name' AND COMPWORKSTEP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_DESCRIPTION ON COMPWORKSTEP_DESCRIPTION.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_DESCRIPTION.PROPERTYDEFUID = 'Description' AND COMPWORKSTEP_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_SEQUENCE ON COMPWORKSTEP_SEQUENCE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_SEQUENCE.PROPERTYDEFUID = 'ComponentWorkTypeStep_Sequence' AND COMPWORKSTEP_SEQUENCE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_UNITRATE ON COMPWORKSTEP_UNITRATE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_UNITRATE.PROPERTYDEFUID = 'ComponentWorkTypeStep_UnitRate' AND COMPWORKSTEP_UNITRATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_RATEUOM ON COMPWORKSTEP_RATEUOM.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_RATEUOM.PROPERTYDEFUID = 'ComponentWorkTypeStep_RateUoM' AND COMPWORKSTEP_RATEUOM.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_NOTES ON COMPWORKSTEP_NOTES.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_NOTES.PROPERTYDEFUID = 'ComponentWorkTypeStep_Notes' AND COMPWORKSTEP_NOTES.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_PLANNEDMANHOURS ON COMPWORKSTEP_PLANNEDMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_PLANNEDMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ManHours' AND COMPWORKSTEP_PLANNEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_ACTUALMANHOURS ON COMPWORKSTEP_ACTUALMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_ACTUALMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualHours' AND COMPWORKSTEP_ACTUALMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_DATECOMPLETE ON COMPWORKSTEP_DATECOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_DATECOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualDateComplete' AND COMPWORKSTEP_DATECOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  LEFT JOIN DATAOBJPR COMPWORKSTEP_QUANTITYCOMPLETE ON COMPWORKSTEP_QUANTITYCOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_QUANTITYCOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_QuantityComplete' AND COMPWORKSTEP_QUANTITYCOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'


),

SPCRPT_WORKSTEP_REL_PROP_TMP as (
SELECT
            COMPWORKSTEP.COMPWORKSTEPOBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP_WORKTYPE_COSTCODE.STRVALUE AS "COSTCODE",
            COMPWORKSTEP_FIWP.OBID AS "FIWPOBID",	  
            COMPWORKSTEP_WORKTYPE.OBID AS "WORKTYPEOBID",
            COMPWORKSTEP_COMP.OBID AS "COMPOBID",
            CAST(COMPONENTITEM_QUANTITYPLANNED.STRVALUE AS FLOAT) AS "QUANTITYPLANNED",
            
            CAST(COMPONENTITEM_UNITS.STRVALUE AS FLOAT) AS "UNITS"
FROM SPCRPT_WORKSTEP_IOBJ_PROP_TMP COMPWORKSTEP
	LEFT JOIN DATAREL COMPWORKSTEP_FIWP_REL ON COMPWORKSTEP_FIWP_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID  AND COMPWORKSTEP_FIWP_REL.DEFUID = 'SPC_Package_ComponentWorkTypeStep' AND COMPWORKSTEP_FIWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_FIWP ON COMPWORKSTEP_FIWP.OBJUID = COMPWORKSTEP_FIWP_REL.UID1 AND COMPWORKSTEP_FIWP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL COMPWORKSTEP_WORKTYPE_REL ON COMPWORKSTEP_WORKTYPE_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID AND COMPWORKSTEP_WORKTYPE_REL.DEFUID = 'SPC_ComponentWorkType_ComponentWorkTypeSteps' AND COMPWORKSTEP_WORKTYPE_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_WORKTYPE ON COMPWORKSTEP_WORKTYPE.OBJUID = COMPWORKSTEP_WORKTYPE_REL.UID1 AND COMPWORKSTEP_WORKTYPE.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_WORKTYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_WORKTYPE_COSTCODE ON COMPWORKSTEP_WORKTYPE_COSTCODE.OBJOBID = COMPWORKSTEP_WORKTYPE.OBID AND COMPWORKSTEP_WORKTYPE_COSTCODE.PROPERTYDEFUID = 'ComponentWorkType_CostCode' AND COMPWORKSTEP_WORKTYPE_COSTCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL COMPWORKSTEP_COMP_REL ON COMPWORKSTEP_COMP_REL.UID2 = COMPWORKSTEP_WORKTYPE.OBJUID AND COMPWORKSTEP_COMP_REL.DEFUID = 'SPC_ComponentItem_ComponentWorkType' AND COMPWORKSTEP_COMP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_COMP ON COMPWORKSTEP_COMP.OBJUID = COMPWORKSTEP_COMP_REL.UID1 AND COMPWORKSTEP_COMP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_COMP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_QUANTITYPLANNED ON COMPONENTITEM_QUANTITYPLANNED.OBJOBID = COMPWORKSTEP_COMP.OBID AND COMPONENTITEM_QUANTITYPLANNED.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_QUANTITYPLANNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_UNITS ON COMPONENTITEM_UNITS.OBJOBID = COMPWORKSTEP_COMP.OBID AND COMPONENTITEM_UNITS.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_UNITS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
),


WorkStepsX as (
SELECT

	    t1.COMPWORKSTEPOBID, COMPWORKSTEPUID, PROJECT, 
      NAME, DESCRIPTION, SEQUENCE, UNITRATE, RATEUOM, NOTES, PLANNEDMANHOURS,  CASE WHEN ISNULL(t3.UNITS,0)=0 then 0 else CASE WHEN ISNULL(QUANTITYCOMPLETE,0)/ ISNULL(t3.UNITS,0)>1 THEN 1 ELSE ISNULL(QUANTITYCOMPLETE,0)/ ISNULL(t3.UNITS,0) END * ISNULL(PLANNEDMANHOURS,0) end as ACTUALMANHOURS, 
      ACTUALDATECOMPLETE,  ISNULL(QUANTITYCOMPLETE,0) as UNIT_COMPLETED,
      CASE WHEN ISNULL(t3.UNITS,0)>0 THEN 
      CASE WHEN ISNULL(QUANTITYCOMPLETE,0)/ ISNULL(t3.UNITS,0) * ISNULL(PLANNEDMANHOURS,0)>=PLANNEDMANHOURS THEN 1 ELSE 0 END      
      END AS QUANTITYCOMPLETE, COSTCODE, FIWPOBID, WORKTYPEOBID, COMPOBID, QUANTITYPLANNED, CREATIONUSER, CREATIONDATE, t3.UNITS , QUANTITYPLANNED as PLAN_UNITS
      
FROM SPCRPT_WORKSTEP_IOBJ_PROP_TMP t1
LEFT JOIN SPCRPT_WORKSTEP_DIR_PROP_TMP t2 ON t2.COMPWORKSTEPOBID = t1.COMPWORKSTEPOBID
LEFT JOIN SPCRPT_WORKSTEP_REL_PROP_TMP t3 ON t3.COMPWORKSTEPOBID = t1.COMPWORKSTEPOBID),

WorkSteps as 
(

  SELECT COMPWORKSTEPOBID, COMPWORKSTEPUID, PROJECT, NAME, DESCRIPTION, SEQUENCE, UNITRATE, RATEUOM, NOTES, PLANNEDMANHOURS, ACTUALMANHOURS, ACTUALDATECOMPLETE, 
  QUANTITYCOMPLETE, COSTCODE, FIWPOBID, WORKTYPEOBID, COMPOBID, CREATIONUSER, CREATIONDATE, UNITS , COUNT(DISTINCT COMPOBID) AS QUANTITYPLANNED, sum(PLAN_UNITS) as PLAN_UNITS, SUM( DISTINCT UNIT_COMPLETED) as UNIT_COMPLETED,
  CASE WHEN PLANNEDMANHOURS=0 then 0 else CASE WHEN (ACTUALMANHOURS / PLANNEDMANHOURS)>=1 THEN 1 ELSE 0 END END as Gate_QTYComplete
  FROM WorkStepsX
  
  WHERE FIWPOBID <> '24GA018A' or FIWPOBID <> '235S06CA' or FIWPOBID <> '235S00NA'
  
  GROUP by COMPWORKSTEPOBID, COMPWORKSTEPUID, PROJECT, NAME, DESCRIPTION, SEQUENCE, UNITRATE, RATEUOM, NOTES, PLANNEDMANHOURS, ACTUALMANHOURS, ACTUALDATECOMPLETE, 
  QUANTITYCOMPLETE, COSTCODE, FIWPOBID, WORKTYPEOBID, COMPOBID, CREATIONUSER, CREATIONDATE, UNITS
  
),

 SPCRPT_COMP_IOBJECT_PROP_TMP as (
SELECT 
            COMPONENTITEM.OBID AS "COMPOBID",
            COMPONENTITEM.OBJUID AS "COMPUID",
            COMPONENTITEM.CONFIG AS "PROJECT"
FROM DATAOBJ COMPONENTITEM WHERE COMPONENTITEM.OBJDEFUID IN ('SPC_ComponentItem', 'SPC_AdhocComponentItem',  'SPC_NonPublishedComponentItem', 'SPC_Spool', 'SPC_Assembly') AND COMPONENTITEM.TERMINATIONDATE = '9999/12/31-23:59:59:999'
),

SPCRPT_COMP_DIRECT_PROP_TMP as (
SELECT 
            COMPONENTITEM.COMPOBID AS "COMPOBID",
            COMPONENTITEM_NAME.STRVALUE AS "NAME", 
            COMPONENTITEM_DESCRIPTION.STRVALUE AS "DESCRIPTION",	  
            COMPONENTITEM_MATERIAL.STRVALUE AS "MATERIAL",	  
            COMPONENTITEM_RATING.STRVALUE AS "RATING",	  
            COMPONENTITEM_CLASS.STRVALUE AS "CLASS",	  
            CAST(COMPONENTITEM_SIZE.STRVALUE AS FLOAT) AS "COMPSIZE",	  
            COMPONENTITEM_THICKNESS.STRVALUE AS "THICKNESS",	  
            CAST(COMPONENTITEM_UNITS.STRVALUE AS FLOAT) AS "UNITS",
            COMPONENTITEM_COMMODITYCODE.STRVALUE AS "COMMODITYCODE",
            COMPONENTITEM_DRAWINGTITLE.STRVALUE AS "DRAWINGTITLE",
            COMPONENTITEM_DRAWINGREVISION.STRVALUE AS "DRAWINGREVISION",
            COMPONENTITEM_REVISIONDATE.STRVALUE AS "REVISIONDATE",
            COMPONENTITEM_TRANSMITTALNO.STRVALUE AS "TRANSMITTALNO",
            COMPONENTITEM_COMPONENTSTATUS.STRVALUE AS "COMPONENTSTATUS"
FROM SPCRPT_COMP_IOBJECT_PROP_TMP COMPONENTITEM
	LEFT JOIN DATAOBJPR COMPONENTITEM_NAME ON COMPONENTITEM_NAME.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_NAME.PROPERTYDEFUID = 'Name' AND COMPONENTITEM_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_DESCRIPTION ON COMPONENTITEM_DESCRIPTION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DESCRIPTION.PROPERTYDEFUID = 'SPC_ComponentItem_ShortDescription' AND COMPONENTITEM_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
    LEFT JOIN DATAOBJPR COMPONENTITEM_MATERIAL ON COMPONENTITEM_MATERIAL.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_MATERIAL.PROPERTYDEFUID = 'SPC_ComponentItem_Material' AND COMPONENTITEM_MATERIAL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_RATING ON COMPONENTITEM_RATING.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_RATING.PROPERTYDEFUID = 'SPC_ComponentItem_Rating' AND COMPONENTITEM_RATING.TERMINATIONDATE = '9999/12/31-23:59:59:999'
    LEFT JOIN DATAOBJPR COMPONENTITEM_CLASS ON COMPONENTITEM_CLASS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_CLASS.PROPERTYDEFUID = 'SpcNonPublishedClassDesignation' AND COMPONENTITEM_CLASS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_SIZE ON COMPONENTITEM_SIZE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_SIZE.PROPERTYDEFUID = 'SPC_ComponentItem_Size' AND COMPONENTITEM_SIZE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_THICKNESS ON COMPONENTITEM_THICKNESS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_THICKNESS.PROPERTYDEFUID = 'SPC_ComponentItem_Thickness' AND COMPONENTITEM_THICKNESS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_UNITS ON COMPONENTITEM_UNITS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_UNITS.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_UNITS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_COMMODITYCODE ON COMPONENTITEM_COMMODITYCODE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_COMMODITYCODE.PROPERTYDEFUID = 'SPC_ComponentItem_CommodityCode' AND COMPONENTITEM_COMMODITYCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_DRAWINGTITLE ON COMPONENTITEM_DRAWINGTITLE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DRAWINGTITLE.PROPERTYDEFUID = 'MDR_IDOCS_DrawingTitle' AND COMPONENTITEM_DRAWINGTITLE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_DRAWINGREVISION ON COMPONENTITEM_DRAWINGREVISION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DRAWINGREVISION.PROPERTYDEFUID = 'MDR_IDOCS_DrawingRevision' AND COMPONENTITEM_DRAWINGREVISION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_REVISIONDATE ON COMPONENTITEM_REVISIONDATE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_REVISIONDATE.PROPERTYDEFUID = 'MDR_IDOCS_RevisionDate' AND COMPONENTITEM_REVISIONDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_TRANSMITTALNO ON COMPONENTITEM_TRANSMITTALNO.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_TRANSMITTALNO.PROPERTYDEFUID = 'MDR_IDOCS_TransmittalNo' AND COMPONENTITEM_TRANSMITTALNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_COMPONENTSTATUS ON COMPONENTITEM_COMPONENTSTATUS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_COMPONENTSTATUS.PROPERTYDEFUID = 'MDR_ComponentStatus' AND COMPONENTITEM_COMPONENTSTATUS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
),
SPCRPT_COMPONENTITEM1 as (
SELECT
      
	    t1.COMPOBID, COMPUID, PROJECT,     
	    NAME, DESCRIPTION, MATERIAL, RATING, CLASS, COMPSIZE, THICKNESS, UNITS, COMMODITYCODE,DRAWINGTITLE,DRAWINGREVISION,REVISIONDATE,TRANSMITTALNO,COMPONENTSTATUS
FROM SPCRPT_COMP_IOBJECT_PROP_TMP t1
LEFT JOIN SPCRPT_COMP_DIRECT_PROP_TMP t2 ON t2.COMPOBID = t1.COMPOBID),

SPCRPT_FIWP_IOBJECT_PROP_TMP as (

SELECT 
            FIWP.OBID AS "FIWPOBID",
            FIWP.OBJUID AS "FIWPUID",
            FIWP.CONFIG AS "PROJECT",
            FIWP.CREATIONUSER, FIWP.CREATIONDATE
FROM DATAOBJ FIWP WHERE FIWP.OBJDEFUID = 'SPC_FIWP' AND FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'),

 SPCRPT_FIWP_DIRECT_PROP_TMP  as (

SELECT 
            FIWP.FIWPOBID AS "FIWPOBID",
             FIWP_NAME.STRVALUE AS "NAME", 
            FIWP_DESCRIPTION.STRVALUE AS "DESCRIPTION", 
            CONVERT(datetime,FIWP_PLANNEDSTARTDATE.STRVALUE) AS "PLANNEDSTARTDATE",            
            CONVERT(datetime,FIWP_PLANNEDFINISHDATE.STRVALUE) AS "PLANNEDFINISHDATE",
            CONVERT(datetime,FIWP_ACTUALSTARTDATE.STRVALUE) AS "ACTUALSTARTDATE",
            CONVERT(datetime,FIWP_ACTUALFINISHDATE.STRVALUE) AS "ACTUALFINISHDATE",
            CAST(FIWP_ESTIMATEDMANHOURS.STRVALUE AS FLOAT) AS "ESTIMATEDMANHOURS",
            FIWP_SCOPE.STRVALUE AS "SCOPE",
            FIWP_NOTES.STRVALUE AS "NOTES",
            CAST(FIWP_CREWSIZE.STRVALUE AS INT) AS "CREWSIZE", 
            FIWP_EWPNUMBER.STRVALUE AS "EWPNUMBER",
            FIWP_CREWDURATION.STRVALUE AS "CREWDURATION",
            FIWP.FIWPUID as "UID",
           CAST( FIWP_PREVPROGRESS.STRVALUE AS FLOAT) as "PREV_PROGRESS",
           CAST( FIWP_PREVEARNED.STRVALUE AS FLOAT)  as "PREV_EARNED",
           CAST(FIWP_PREVWKLYEARNED.STRVALUE AS FLOAT)  as "PREV_WKLYEARNED"
           
FROM SPCRPT_FIWP_IOBJECT_PROP_TMP FIWP
	LEFT JOIN DATAOBJPR FIWP_NAME ON FIWP_NAME.OBJOBID = FIWP.FIWPOBID AND FIWP_NAME.PROPERTYDEFUID = 'Name' AND FIWP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_DESCRIPTION ON FIWP_DESCRIPTION.OBJOBID = FIWP.FIWPOBID AND FIWP_DESCRIPTION.PROPERTYDEFUID = 'Description' AND FIWP_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_PLANNEDSTARTDATE ON FIWP_PLANNEDSTARTDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_PLANNEDSTARTDATE.PROPERTYDEFUID = 'FIWP_PlannedStartDate' AND FIWP_PLANNEDSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_PLANNEDFINISHDATE ON FIWP_PLANNEDFINISHDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_PLANNEDFINISHDATE.PROPERTYDEFUID = 'FIWP_PlannedFinishDate' AND FIWP_PLANNEDFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALSTARTDATE ON FIWP_ACTUALSTARTDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_ACTUALSTARTDATE.PROPERTYDEFUID = 'FIWP_ActualStartDate'  AND FIWP_ACTUALSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALFINISHDATE ON FIWP_ACTUALFINISHDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_ACTUALFINISHDATE.PROPERTYDEFUID = 'FIWP_ActualFinishDate'  AND FIWP_ACTUALFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ESTIMATEDMANHOURS ON FIWP_ESTIMATEDMANHOURS.OBJOBID = FIWP.FIWPOBID AND FIWP_ESTIMATEDMANHOURS.PROPERTYDEFUID = 'FIWP_Estimated_Manhours'  AND FIWP_ESTIMATEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_SCOPE ON FIWP_SCOPE.OBJOBID = FIWP.FIWPOBID AND FIWP_SCOPE.PROPERTYDEFUID = 'FIWP_Scope' AND FIWP_SCOPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_NOTES ON FIWP_NOTES.OBJOBID = FIWP.FIWPOBID AND FIWP_NOTES.PROPERTYDEFUID like 'FIWP_Notes' AND FIWP_NOTES.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CREWSIZE ON FIWP_CREWSIZE.OBJOBID = FIWP.FIWPOBID AND FIWP_CREWSIZE.PROPERTYDEFUID = 'FIWP_Crew_Size' AND FIWP_CREWSIZE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_EWPNUMBER ON FIWP_EWPNUMBER.OBJOBID = FIWP.FIWPOBID AND FIWP_EWPNUMBER.PROPERTYDEFUID = 'FIWP_EWP_Number' AND FIWP_EWPNUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CREWDURATION ON FIWP_CREWDURATION.OBJOBID = FIWP.FIWPOBID AND FIWP_CREWDURATION.PROPERTYDEFUID = 'SPC_CrewDuration' AND FIWP_CREWDURATION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  LEFT JOIN DATAOBJPR FIWP_PREVPROGRESS ON FIWP_PREVPROGRESS.OBJOBID = FIWP.FIWPOBID AND FIWP_PREVPROGRESS.PROPERTYDEFUID = 'MDR_PreviousProgress' AND FIWP_PREVPROGRESS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR FIWP_PREVEARNED ON FIWP_PREVEARNED.OBJOBID = FIWP.FIWPOBID AND FIWP_PREVEARNED.PROPERTYDEFUID = 'MDR_PreviousEarned' AND FIWP_PREVEARNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR FIWP_PREVWKLYEARNED ON FIWP_PREVWKLYEARNED.OBJOBID = FIWP.FIWPOBID AND FIWP_PREVWKLYEARNED.PROPERTYDEFUID = 'MDR_PrevWeeklyEarned' AND FIWP_PREVWKLYEARNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  ),
  
SPCRPT_FIWP_DIR_ENUM_PROP_TMP as ( 
  SELECT 
            FIWP.FIWPOBID AS "FIWPOBID",
            FIWP_PURPOSE.OBJNAME AS "PURPOSE",
            FIWP_DISCIPLINE.OBJNAME AS "DISCIPLINE",
            FIWP_STATUS.OBJNAME AS "STATUS" 
            
FROM SPCRPT_FIWP_IOBJECT_PROP_TMP FIWP
	LEFT JOIN DATAOBJPR FIWP_PURPOSE_PR ON FIWP_PURPOSE_PR.OBJOBID = FIWP.FIWPOBID AND FIWP_PURPOSE_PR.PROPERTYDEFUID = 'FIWP_Purpose' AND FIWP_PURPOSE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_PURPOSE ON FIWP_PURPOSE.OBJUID = FIWP_PURPOSE_PR.STRVALUE AND FIWP_PURPOSE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_DISCIPLINE_PR ON FIWP_DISCIPLINE_PR.OBJOBID = FIWP.FIWPOBID AND FIWP_DISCIPLINE_PR.PROPERTYDEFUID = 'FIWP_Discipline' AND FIWP_DISCIPLINE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_DISCIPLINE ON FIWP_DISCIPLINE.OBJUID = FIWP_DISCIPLINE_PR.STRVALUE AND FIWP_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  LEFT JOIN DATAOBJPR FIWP_STATUS_PR ON FIWP_STATUS_PR.OBJOBID = FIWP.FIWPOBID AND FIWP_STATUS_PR.PROPERTYDEFUID = 'Package_Status' AND FIWP_STATUS_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_STATUS ON FIWP_STATUS.OBJUID = FIWP_STATUS_PR.STRVALUE AND FIWP_STATUS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
--  WHERE  FIWP_STATUS.OBJNAME != 'Preliminary'
  
	)


  SELECT
            FIWP.FIWPOBID AS "FIWPOBID",
            t2.NAME AS "WPNO",
            CAST(FIWP_PLANNEDMANHOURS.STRVALUE AS FLOAT) AS "PLANNEDMANHOURS",
            CAST(FIWP_ACTUALMANHOURS.STRVALUE AS FLOAT) AS "ACTUALMANHOURS",
            CAST(FIWP_COMPLETEDMANHOURS.STRVALUE AS FLOAT) AS "COMPLETEDMANHOURS",
            CAST(FIWP_COMPONENTTOTALCONSTRAINTS.STRVALUE AS INT) AS "TOTALCOMPONENTCONSTRAINTS",
            CAST(FIWP_COMPONENTOPENCONSTRAINTS.STRVALUE AS INT) AS "OPENCOMPONENTCONSTRAINTS",
            FIWP_CONTRACT.STRVALUE AS "CONTRACT",
            FIWP_CONTRACTOR.STRVALUE AS "CONTRACTOR",
            FIWP_DESIGNAREA.STRVALUE AS "DESIGNAREA",
            FIWP_FOREMAN.STRVALUE AS "FOREMAN",
            FIWP_GENERALFOREMAN.STRVALUE AS "GENERALFOREMAN",
            FIWP_FIELDENGINEER.STRVALUE AS "FIELDENGINEER",
            FIWP_SUPERINTENDENT.STRVALUE AS "SUPERINTENDENT",
            FIWP_ISSUEDBY.STRVALUE AS "ISSUEDBY",
            FIWP_NAMEDCREW.OBID AS "CREWOBID",
            FIWP_CWP.OBID AS "CWPOBID",
            FIWP_REVDATE.STRVALUE AS "REVDATE",
            FIWP_RECEDATE.STRVALUE AS "RECEDATE",
            enumpr.objname AS "WP_REVNO",
            FIWP_TaskNo.STRVALUE AS "FIWPTASKNO",
            CAST(FIWP_Estimated.STRVALUE AS FLOAT) AS "FIWPAFCHRS",
			
			FIWP_MDRWeightage.STRVALUE AS "WEIGHTAGE",
            FIWP_MDRResourceCode.STRVALUE AS "RESOURCECODE",
			 
			FIWP_MDRWorkPhase.STRVALUE AS "WORKPHASE",
			FIWP_MDRProgressGrouping.STRVALUE AS "PROGRESSGROUPING"
      
      
          

FROM SPCRPT_FIWP_IOBJECT_PROP_TMP FIWP
	LEFT JOIN DATAREL FIWP_PACKAGEROLLUPDATE_REL ON FIWP_PACKAGEROLLUPDATE_REL.UID1 = FIWP.FIWPUID AND FIWP_PACKAGEROLLUPDATE_REL.DEFUID = 'SPC_Package_PackageRollupData' AND FIWP_PACKAGEROLLUPDATE_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_PACKAGEROLLUPDATE ON FIWP_PACKAGEROLLUPDATE.OBJUID = FIWP_PACKAGEROLLUPDATE_REL.UID2 AND FIWP_PACKAGEROLLUPDATE.CONFIG = FIWP.PROJECT AND FIWP_PACKAGEROLLUPDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR FIWP_PLANNEDMANHOURS ON FIWP_PLANNEDMANHOURS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_PLANNEDMANHOURS.PROPERTYDEFUID = 'PackageRollupData_TotalManHours' AND FIWP_PLANNEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALMANHOURS ON FIWP_ACTUALMANHOURS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_ACTUALMANHOURS.PROPERTYDEFUID = 'PackageRollupData_TotalActualManHours' AND FIWP_ACTUALMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_COMPLETEDMANHOURS ON FIWP_COMPLETEDMANHOURS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_COMPLETEDMANHOURS.PROPERTYDEFUID = 'PackageRollupData_TotalManHoursCompleted' AND FIWP_COMPLETEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_COMPONENTTOTALCONSTRAINTS ON FIWP_COMPONENTTOTALCONSTRAINTS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_COMPONENTTOTALCONSTRAINTS.PROPERTYDEFUID = 'PackageRollupData_TotalConstraints' AND FIWP_COMPONENTTOTALCONSTRAINTS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_COMPONENTOPENCONSTRAINTS ON FIWP_COMPONENTOPENCONSTRAINTS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_COMPONENTOPENCONSTRAINTS.PROPERTYDEFUID = 'PackageRollupData_OpenConstraints' AND FIWP_COMPONENTOPENCONSTRAINTS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL FIWP_CONTRACT_REL ON FIWP_CONTRACT_REL.UID1 = FIWP.FIWPUID AND FIWP_CONTRACT_REL.DEFUID = 'SPC_Package_Contract' AND FIWP_CONTRACT_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_CONTRACT_OBJ ON FIWP_CONTRACT_OBJ.OBJUID = FIWP_CONTRACT_REL.UID2 AND FIWP_CONTRACT_OBJ.CONFIG = FIWP.PROJECT AND FIWP_CONTRACT_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CONTRACT ON FIWP_CONTRACT.OBJOBID = FIWP_CONTRACT_OBJ.OBID AND FIWP_CONTRACT.PROPERTYDEFUID = 'Description' AND FIWP_CONTRACT.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  LEFT JOIN DATAREL FIWP_CONTRACTOR_REL ON FIWP_CONTRACTOR_REL.UID1 = FIWP.FIWPUID AND FIWP_CONTRACTOR_REL.DEFUID = 'SPC_Package_Contractor' AND FIWP_CONTRACTOR_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_CONTRACTOR_OBJ ON FIWP_CONTRACTOR_OBJ.OBJUID = FIWP_CONTRACTOR_REL.UID2 AND FIWP_CONTRACTOR_OBJ.CONFIG = FIWP.PROJECT AND FIWP_CONTRACTOR_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CONTRACTOR ON FIWP_CONTRACTOR.OBJOBID = FIWP_CONTRACTOR_OBJ.OBID AND FIWP_CONTRACTOR.PROPERTYDEFUID = 'Name' AND FIWP_CONTRACTOR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL FIWP_DESIGNAREA_REL ON FIWP_DESIGNAREA_REL.UID1 = FIWP.FIWPUID AND FIWP_DESIGNAREA_REL.DEFUID = 'SPC_FunctionalArea_FIWPs' AND FIWP_DESIGNAREA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_DESIGNAREA_OBJ ON FIWP_DESIGNAREA_OBJ.OBJUID = FIWP_DESIGNAREA_REL.UID1 AND FIWP_DESIGNAREA_OBJ.CONFIG = FIWP.PROJECT AND FIWP_DESIGNAREA_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_DESIGNAREA ON FIWP_DESIGNAREA.OBJOBID = FIWP_DESIGNAREA_OBJ.OBID AND FIWP_DESIGNAREA.PROPERTYDEFUID = 'Name' AND FIWP_DESIGNAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	

	--LEFT JOIN DATAREL FIWP_FOREMAN_REL ON FIWP_FOREMAN_REL.UID1 = FIWP.FIWPUID AND FIWP_FOREMAN_REL.DEFUID = 'SPC_Package_ForemanRole' AND FIWP_FOREMAN_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	LEFT JOIN
  (
    select DENSE_RANK() OVER (PARTITION BY UID1 ORDER BY CREATIONDATE DESC) AS SEQUENCE , UID1, UID2, CREATIONDATE
    FROM SCHEMAREL where  DEFUID='SPC_Package_ForemanRole'
    AND TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  ) FIWP_FOREMAN_REL ON FIWP_FOREMAN_REL.UID1=FIWP.FIWPUID AND FIWP_FOREMAN_REL.SEQUENCE=1
	
	LEFT JOIN SCHEMAOBJ FIWP_FOREMAN_OBJ ON FIWP_FOREMAN_OBJ.OBJUID = FIWP_FOREMAN_REL.UID2 AND FIWP_FOREMAN_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_FOREMAN ON FIWP_FOREMAN.OBJOBID = FIWP_FOREMAN_OBJ.OBID AND FIWP_FOREMAN.PROPERTYDEFUID = 'Name' AND FIWP_FOREMAN.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
		
	--LEFT JOIN DATAREL FIWP_GENERALFOREMAN_REL ON FIWP_GENERALFOREMAN_REL.UID1 = FIWP.FIWPUID AND FIWP_GENERALFOREMAN_REL.DEFUID = 'SPC_Package_GeneralForemanRole' AND FIWP_GENERALFOREMAN_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	LEFT JOIN
  (
    select DENSE_RANK() OVER (PARTITION BY UID1 ORDER BY CREATIONDATE DESC) AS SEQUENCE , UID1, UID2, CREATIONDATE
    FROM SCHEMAREL where  DEFUID='SPC_Package_GeneralForemanRole'
    AND TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  ) FIWP_GENERALFOREMAN_REL ON FIWP_GENERALFOREMAN_REL.UID1=FIWP.FIWPUID AND FIWP_GENERALFOREMAN_REL.SEQUENCE=1
	
	LEFT JOIN SCHEMAOBJ FIWP_GENERALFOREMAN_OBJ ON FIWP_GENERALFOREMAN_OBJ.OBJUID = FIWP_GENERALFOREMAN_REL.UID2 AND FIWP_GENERALFOREMAN_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_GENERALFOREMAN ON FIWP_GENERALFOREMAN.OBJOBID = FIWP_GENERALFOREMAN_OBJ.OBID AND FIWP_GENERALFOREMAN.PROPERTYDEFUID = 'Name' AND FIWP_GENERALFOREMAN.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	
	LEFT JOIN SCHEMAREL FIWP_FIELDENGINEER_REL ON FIWP_FIELDENGINEER_REL.UID1 = FIWP.FIWPUID AND FIWP_FIELDENGINEER_REL.DEFUID = 'SPC_Package_FieldEngineerRole' AND FIWP_FIELDENGINEER_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_FIELDENGINEER_OBJ ON FIWP_FIELDENGINEER_OBJ.OBJUID = FIWP_FIELDENGINEER_REL.UID2 AND FIWP_FIELDENGINEER_OBJ.CONFIG = FIWP.PROJECT AND FIWP_FIELDENGINEER_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_FIELDENGINEER ON FIWP_FIELDENGINEER.OBJOBID = FIWP_FIELDENGINEER_OBJ.OBID AND FIWP_FIELDENGINEER.PROPERTYDEFUID = 'Name' AND FIWP_FIELDENGINEER.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAREL FIWP_SUPERINTENDENT_REL ON FIWP_SUPERINTENDENT_REL.UID1 = FIWP.FIWPUID AND FIWP_SUPERINTENDENT_REL.DEFUID = 'SPC_Package_SuperintendentRole' AND FIWP_SUPERINTENDENT_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_SUPERINTENDENT_OBJ ON FIWP_SUPERINTENDENT_OBJ.OBJUID = FIWP_SUPERINTENDENT_REL.UID2 AND FIWP_SUPERINTENDENT_OBJ.CONFIG = FIWP.PROJECT AND FIWP_SUPERINTENDENT_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_SUPERINTENDENT ON FIWP_SUPERINTENDENT.OBJOBID = FIWP_SUPERINTENDENT_OBJ.OBID AND FIWP_SUPERINTENDENT.PROPERTYDEFUID = 'Name' AND FIWP_SUPERINTENDENT.TERMINATIONDATE = '9999/12/31-23:59:59:999'	
  LEFT JOIN SCHEMAREL FIWP_ISSUEDBY_REL ON FIWP_ISSUEDBY_REL.UID1 = FIWP.FIWPUID AND FIWP_ISSUEDBY_REL.DEFUID = 'SPC_Package_IWPIssuedBy' AND FIWP_ISSUEDBY_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_ISSUEDBY_OBJ ON FIWP_ISSUEDBY_OBJ.OBJUID = FIWP_ISSUEDBY_REL.UID2 AND  FIWP_ISSUEDBY_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_ISSUEDBY ON FIWP_ISSUEDBY.OBJOBID = FIWP_ISSUEDBY_OBJ.OBID AND FIWP_ISSUEDBY.PROPERTYDEFUID = 'Name' AND FIWP_ISSUEDBY.TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  LEFT JOIN DATAREL FIWP_NAMEDCREW_REL ON FIWP_NAMEDCREW_REL.UID1 = FIWP.FIWPUID AND FIWP_NAMEDCREW_REL.DEFUID = 'SPC_Package_Crew' AND FIWP_NAMEDCREW_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_NAMEDCREW ON FIWP_NAMEDCREW.OBJUID = FIWP_NAMEDCREW_REL.UID2 AND FIWP_NAMEDCREW.CONFIG = FIWP.PROJECT AND FIWP_NAMEDCREW.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL FIWP_CWP_REL ON FIWP_CWP_REL.UID2 = FIWP.FIWPUID AND FIWP_CWP_REL.DEFUID = 'SPC_CWP_FIWPs' AND FIWP_CWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_CWP ON FIWP_CWP.OBJUID = FIWP_CWP_REL.UID1 AND FIWP_CWP.CONFIG = FIWP.PROJECT AND FIWP_CWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
      	--IWP REVDATE
	LEFT JOIN DATAOBJPR FIWP_REVDATE ON FIWP_REVDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_REVDATE.PROPERTYDEFUID = 'MDR_RevDate' AND FIWP_REVDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_REV ON FIWP_REV.OBJOBID = FIWP.FIWPOBID AND FIWP_REV.PROPERTYDEFUID = 'MDR_Rev' AND FIWP_REV.TERMINATIONDATE = '9999/12/31-23:59:59:999'	
  left join schemaobj enumpr on FIWP_REV.strvalue=enumpr.objuid and enumpr.objdefuid='EnumEnum' and enumpr.terminationdate='9999/12/31-23:59:59:999'
--where pr.propertydefuid='MDR_Rev' and pr.OBJOBID = '1SRI000A' 
  
	--IWP RECEDATE
	LEFT JOIN DATAOBJPR FIWP_RECEDATE ON FIWP_RECEDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_RECEDATE.PROPERTYDEFUID = 'MDR_RecievedDate' AND FIWP_RECEDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--FIWP TASK NO
	LEFT JOIN DATAOBJPR FIWP_TaskNo ON FIWP_TaskNo.OBJOBID = FIWP.FIWPOBID AND FIWP_TaskNo.PROPERTYDEFUID = 'MDR_FIWPTaskNo' AND FIWP_TaskNo.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--FIWP AFC Hrs
	LEFT JOIN DATAOBJPR FIWP_Estimated ON FIWP_Estimated.OBJOBID = FIWP.FIWPOBID AND FIWP_Estimated.PROPERTYDEFUID = 'FIWP_Estimated_Manhours' AND FIWP_Estimated.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
		--MDR_Weld_Weightage
	LEFT JOIN DATAOBJPR FIWP_MDRWeightage ON FIWP_MDRWeightage.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRWeightage.PROPERTYDEFUID = 'MDR_Weld_Weightage' AND FIWP_MDRWeightage.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--MDR_ResourceCode
	LEFT JOIN DATAOBJPR FIWP_MDRResourceCode ON FIWP_MDRResourceCode.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRResourceCode.PROPERTYDEFUID = 'MDR_ResourceCode' AND FIWP_MDRResourceCode.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--MDR_ProgressGrouping
	LEFT JOIN DATAOBJPR FIWP_MDRProgressGrouping ON FIWP_MDRProgressGrouping.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRProgressGrouping.PROPERTYDEFUID = 'MDR_ProgressGrouping' AND FIWP_MDRProgressGrouping.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--MDR_WorkPhase
	LEFT JOIN DATAOBJPR FIWP_MDRWorkPhase ON FIWP_MDRWorkPhase.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRWorkPhase.PROPERTYDEFUID = 'MDR_WorkPhase' AND FIWP_MDRWorkPhase.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	
LEFT JOIN SPCRPT_FIWP_DIRECT_PROP_TMP t2 ON t2.FIWPOBID = FIWP.FIWPOBID