cable tray
spc all

SELECT COMPONENTITEM.OBID AS "COMPOBID",
        COMPONENTITEM.OBJNAME as "COMPONENT",
        COMPONENTITEM.CONFIG AS "PROJECT" ,
        COMPONENTITEM_FIWP.OBID AS "FIWPOBID",
        COMPONENTITEM_FIWP.OBJUID AS "FIWPUID",
        COMPONENTITEM_FIWP_NAME.STRVALUE AS "WPNO",
        FIWP_DISCIPLINE.OBJNAME AS "DISCIPLINE",
        FIWP_PURPOSE.OBJNAME AS "PURPOSE",
        FIWP_DESIGNAREA.STRVALUE AS "DESIGNAREA",
        CAST(COMPONENTITEM_QUANTITYPLANNED.STRVALUE AS FLOAT) AS "QUANTITYPLANNED",
        FIWP_CONTRACTOR.STRVALUE AS "CONTRACTOR", 
        FIWP_TaskNo.STRVALUE AS "TASKNO",
        CAST(FIWP_Estimated.STRVALUE AS FLOAT) AS "AFCHRS" ,
        enumpr.objname AS "WP_REVNO",
        FIWP_STATUS.OBJNAME AS "WP STATUS" ,
        FIWP_REVDATE.STRVALUE AS "REVDATE",
        FIWP_RECEDATE.STRVALUE AS "RECEDATE",
        CONVERT(datetime,FIWP_PLANNEDSTARTDATE.STRVALUE) AS "PLANNEDSTARTDATE",            
        CONVERT(datetime,FIWP_PLANNEDFINISHDATE.STRVALUE) AS "PLANNEDFINISHDATE",
        CONVERT(datetime,FIWP_ACTUALSTARTDATE.STRVALUE) AS "ACTUALSTARTDATE",
        CONVERT(datetime,FIWP_ACTUALFINISHDATE.STRVALUE) AS "ACTUALFINISHDATE",
        
				----Component Properties
        MDR_DISCIPLINE.STRVALUE as "MDR_DISCIPLINE",		      
        MDR_ROOMNO.STRVALUE as "MDR_ROOMNO",
        MDR_TYPE.STRVALUE as "MDR_TYPE",
        MDR_LEVEL.STRVALUE as "MDR_LEVEL",
        MDR_PARTNUMBER.STRVALUE as "MDR_PARTNUMBER",
        MDR_DRAWINGNO.STRVALUE as "MDR_DRAWINGNO",
        MDR_PARENTNAME.STRVALUE as "MDR_PARENTNAME",        
        MDR_SHORTDESC.STRVALUE as "MDR_SHORTDESC",  
		MDR_ZONECOLD.STRVALUE as "MDR_ZONECOLD",  
		MDR_ITEMZONE.STRVALUE as "MDR_ITEMZONE", 
		MDR_SYSTEMPATH.STRVALUE as "MDR_SYSTEMPATH",
        MDR_UNITS.STRVALUE as "MDR_UNITS",
		MDR_PARTNUMBER1.STRVALUE as "MDR_PARTNUMBER1",
        MDR_PARTCODE_ESTI.STRVALUE as "MDR_PARTCODE_ESTI",        
        COMP_IDENTCODE.STRVALUE as "COMP_IDENTCODE",	
        COMP_IDENTCODE_M.STRVALUE as "COMP_IDENTCODE_M",			
        COMP_SHORTDESC.STRVALUE as "COMP_SHORTDESC",		
		PIP_COMPNODE.STRVALUE as "PIP_COMPNODE",		
        MDR_MATCUSTOM.STRVALUE as "MDR_MATCUSTOM",
		COMPNODE_COMPTYPE.STRVALUE as "COMPNODE_COMPTYPE",
		COMMCODE.STRVALUE as "COMMODITY CODE",
		HOLDSTATUS.STRVALUE as "HOLDSTATUS",

		
        ClassDesignation.STRVALUE As "CLASSDESIG",
        IsAssembly.STRVALUE As "ISASSEMBLY",		
        COMPONENTITEM.OBJDEFUID as "CLASSDEF"
		
            
  FROM DATAOBJ COMPONENTITEM

  LEFT JOIN DATAREL COMPONENTITEM_FIWP_REL ON COMPONENTITEM_FIWP_REL.UID2 = COMPONENTITEM.OBJUID AND COMPONENTITEM_FIWP_REL.DEFUID = 'SPC_Package_ComponentItems' AND COMPONENTITEM_FIWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPONENTITEM_FIWP ON COMPONENTITEM_FIWP.OBJUID = COMPONENTITEM_FIWP_REL.UID1 AND COMPONENTITEM_FIWP.CONFIG = COMPONENTITEM.CONFIG AND COMPONENTITEM_FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
 	
	LEFT JOIN DATAOBJPR FIWP_DISCIPLINE_PR ON FIWP_DISCIPLINE_PR.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_DISCIPLINE_PR.PROPERTYDEFUID = 'FIWP_Discipline' AND FIWP_DISCIPLINE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_FIWP_NAME ON COMPONENTITEM_FIWP_NAME.OBJOBID = COMPONENTITEM_FIWP.OBID AND COMPONENTITEM_FIWP_NAME.PROPERTYDEFUID = 'Name' AND COMPONENTITEM_FIWP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_DISCIPLINE ON FIWP_DISCIPLINE.OBJUID = FIWP_DISCIPLINE_PR.STRVALUE AND FIWP_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
 
  LEFT JOIN DATAOBJPR FIWP_PURPOSE_PR ON FIWP_PURPOSE_PR.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_PURPOSE_PR.PROPERTYDEFUID = 'FIWP_Purpose' AND FIWP_PURPOSE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_PURPOSE ON FIWP_PURPOSE.OBJUID = FIWP_PURPOSE_PR.STRVALUE AND FIWP_PURPOSE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_QUANTITYPLANNED ON COMPONENTITEM_QUANTITYPLANNED.OBJOBID = COMPONENTITEM.OBID  AND COMPONENTITEM_QUANTITYPLANNED.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_QUANTITYPLANNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	LEFT JOIN DATAREL FIWP_CONTRACTOR_REL ON FIWP_CONTRACTOR_REL.UID1 = COMPONENTITEM_FIWP.OBJUID AND FIWP_CONTRACTOR_REL.DEFUID = 'SPC_Package_Contractor' AND FIWP_CONTRACTOR_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_CONTRACTOR_OBJ ON FIWP_CONTRACTOR_OBJ.OBJUID = FIWP_CONTRACTOR_REL.UID2 AND FIWP_CONTRACTOR_OBJ.CONFIG = COMPONENTITEM.CONFIG AND FIWP_CONTRACTOR_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CONTRACTOR ON FIWP_CONTRACTOR.OBJOBID = FIWP_CONTRACTOR_OBJ.OBID AND FIWP_CONTRACTOR.PROPERTYDEFUID = 'Name' AND FIWP_CONTRACTOR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL FIWP_DESIGNAREA_REL ON FIWP_DESIGNAREA_REL.UID2 = COMPONENTITEM_FIWP.OBJUID AND FIWP_DESIGNAREA_REL.DEFUID = 'SPC_FunctionalArea_FIWPs' AND FIWP_DESIGNAREA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_DESIGNAREA_OBJ ON FIWP_DESIGNAREA_OBJ.OBJUID = FIWP_DESIGNAREA_REL.UID1 AND FIWP_DESIGNAREA_OBJ.CONFIG = COMPONENTITEM.CONFIG AND FIWP_DESIGNAREA_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_DESIGNAREA ON FIWP_DESIGNAREA.OBJOBID = FIWP_DESIGNAREA_OBJ.OBID AND FIWP_DESIGNAREA.PROPERTYDEFUID = 'Name' AND FIWP_DESIGNAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'	
  
        	--IWP REVDATE
	LEFT JOIN DATAOBJPR FIWP_REVDATE ON FIWP_REVDATE.OBJOBID =  COMPONENTITEM_FIWP.OBID AND FIWP_REVDATE.PROPERTYDEFUID = 'MDR_RevDate' AND FIWP_REVDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_REV ON FIWP_REV.OBJOBID =  COMPONENTITEM_FIWP.OBID AND FIWP_REV.PROPERTYDEFUID = 'MDR_Rev' AND FIWP_REV.TERMINATIONDATE = '9999/12/31-23:59:59:999'	
  LEFT JOIN DATAOBJPR FIWP_RECEDATE ON FIWP_RECEDATE.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_RECEDATE.PROPERTYDEFUID = 'MDR_RecievedDate' AND FIWP_RECEDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  left join schemaobj enumpr on FIWP_REV.strvalue=enumpr.objuid and enumpr.objdefuid='EnumEnum' and enumpr.terminationdate='9999/12/31-23:59:59:999'
  
	LEFT JOIN DATAOBJPR FIWP_TaskNo ON FIWP_TaskNo.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_TaskNo.PROPERTYDEFUID = 'MDR_FIWPTaskNo' AND FIWP_TaskNo.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--FIWP AFC Hrs
	LEFT JOIN DATAOBJPR FIWP_Estimated ON FIWP_Estimated.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_Estimated.PROPERTYDEFUID = 'FIWP_Estimated_Manhours' AND FIWP_Estimated.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  LEFT JOIN DATAOBJPR FIWP_STATUS_PR ON FIWP_STATUS_PR.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_STATUS_PR.PROPERTYDEFUID = 'Package_Status' AND FIWP_STATUS_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_STATUS ON FIWP_STATUS.OBJUID = FIWP_STATUS_PR.STRVALUE AND FIWP_STATUS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  --DATES
  LEFT JOIN DATAOBJPR FIWP_PLANNEDSTARTDATE ON FIWP_PLANNEDSTARTDATE.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_PLANNEDSTARTDATE.PROPERTYDEFUID = 'FIWP_PlannedStartDate' AND FIWP_PLANNEDSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_PLANNEDFINISHDATE ON FIWP_PLANNEDFINISHDATE.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_PLANNEDFINISHDATE.PROPERTYDEFUID = 'FIWP_PlannedFinishDate' AND FIWP_PLANNEDFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALSTARTDATE ON FIWP_ACTUALSTARTDATE.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_ACTUALSTARTDATE.PROPERTYDEFUID = 'FIWP_ActualStartDate'  AND FIWP_ACTUALSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALFINISHDATE ON FIWP_ACTUALFINISHDATE.OBJOBID = COMPONENTITEM_FIWP.OBID AND FIWP_ACTUALFINISHDATE.PROPERTYDEFUID = 'FIWP_ActualFinishDate'  AND FIWP_ACTUALFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
 
----Component Properties 
  LEFT JOIN DATAOBJPR MDR_DISCIPLINE ON MDR_DISCIPLINE.objobid = COMPONENTITEM.OBID AND MDR_DISCIPLINE.propertydefuid = 'MDR_Discipline'   AND MDR_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_MATCUSTOM ON MDR_MATCUSTOM.objobid = COMPONENTITEM.OBID AND MDR_MATCUSTOM.propertydefuid = 'MDR_MaterialICustom'   AND MDR_MATCUSTOM.TERMINATIONDATE = '9999/12/31-23:59:59:999'	  
  LEFT JOIN DATAOBJPR MDR_ROOMNO ON MDR_ROOMNO.objobid = COMPONENTITEM.OBID AND MDR_ROOMNO.propertydefuid = 'MDR_RoomNo'   AND MDR_ROOMNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_TYPE ON MDR_TYPE.objobid = COMPONENTITEM.OBID AND MDR_TYPE.propertydefuid = 'MDR_Type'   AND MDR_TYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_LEVEL ON MDR_LEVEL.objobid = COMPONENTITEM.OBID AND MDR_LEVEL.propertydefuid = 'MDR_Level'   AND MDR_LEVEL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_PARTNUMBER ON MDR_PARTNUMBER.objobid = COMPONENTITEM.OBID AND MDR_PARTNUMBER.propertydefuid = 'MDR_PartNumber1'   AND MDR_PARTNUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_DRAWINGNO ON MDR_DRAWINGNO.objobid = COMPONENTITEM.OBID AND MDR_DRAWINGNO.propertydefuid = 'MDR_IDOCS_DrawingNo'   AND MDR_DRAWINGNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_PARENTNAME ON MDR_PARENTNAME.objobid = COMPONENTITEM.OBID AND MDR_PARENTNAME.propertydefuid = 'MDR_ParentName'   AND MDR_PARENTNAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_SHORTDESC ON MDR_SHORTDESC.objobid = COMPONENTITEM.OBID AND MDR_SHORTDESC.propertydefuid = 'SPC_ComponentItem_ShortDescription'   AND MDR_SHORTDESC.TERMINATIONDATE = '9999/12/31-23:59:59:999'
   
   LEFT JOIN DATAOBJPR MDR_ZONECOLD ON MDR_ZONECOLD.objobid = COMPONENTITEM.OBID AND MDR_ZONECOLD.propertydefuid = 'MDR_Zone_Cold'   AND MDR_ZONECOLD.TERMINATIONDATE = '9999/12/31-23:59:59:999' 
   LEFT JOIN DATAOBJPR MDR_ITEMZONE ON MDR_ITEMZONE.objobid = COMPONENTITEM.OBID AND MDR_ITEMZONE.propertydefuid = 'SPC_ComponentItem_Zone'   AND MDR_ITEMZONE.TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  
  LEFT JOIN DATAOBJPR MDR_SYSTEMPATH ON MDR_SYSTEMPATH.objobid = COMPONENTITEM.OBID AND MDR_SYSTEMPATH.propertydefuid = 'SPC_SystemPath'   AND MDR_SYSTEMPATH.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_UNITS ON MDR_UNITS.objobid = COMPONENTITEM.OBID AND MDR_UNITS.propertydefuid = 'SPC_ComponentItem_Units'   AND MDR_UNITS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_PARTNUMBER1 ON MDR_PARTNUMBER1.objobid = COMPONENTITEM.OBID AND MDR_PARTNUMBER1.propertydefuid = 'MDR_PartNumber1'   AND MDR_PARTNUMBER1.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MDR_PARTCODE_ESTI ON MDR_PARTCODE_ESTI.objobid = COMPONENTITEM.OBID AND MDR_PARTCODE_ESTI.propertydefuid = 'MDR_PartCode_Esti'   AND MDR_PARTCODE_ESTI.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMP_IDENTCODE_M ON COMP_IDENTCODE_M.objobid = COMPONENTITEM.OBID AND COMP_IDENTCODE_M.propertydefuid = 'SPC_ComponentItem_IdentCode_M'   AND COMP_IDENTCODE_M.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMP_IDENTCODE ON COMP_IDENTCODE.objobid = COMPONENTITEM.OBID AND COMP_IDENTCODE.propertydefuid = 'Ident_Code'   AND COMP_IDENTCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  LEFT JOIN DATAOBJPR COMP_SHORTDESC ON COMP_SHORTDESC.objobid = COMPONENTITEM.OBID AND COMP_SHORTDESC.propertydefuid = 'SPC_ComponentItem_ShortDescription'   AND COMP_SHORTDESC.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR PIP_COMPNODE ON PIP_COMPNODE.objobid = COMPONENTITEM.OBID AND PIP_COMPNODE.propertydefuid = 'PipingComponentNode_ComponentType'   AND PIP_COMPNODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  
  LEFT JOIN DATAOBJPR COMPNODE_COMPTYPE ON COMPNODE_COMPTYPE.objobid = COMPONENTITEM.OBID AND COMPNODE_COMPTYPE.propertydefuid = 'PipingComponentNode_ComponentType'   AND COMPNODE_COMPTYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMMCODE ON COMMCODE.objobid = COMPONENTITEM.OBID AND COMMCODE.propertydefuid = 'SPC_ComponentItem_CommodityCode'   AND COMMCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR HOLDSTATUS ON HOLDSTATUS.objobid = COMPONENTITEM.OBID AND HOLDSTATUS.propertydefuid = 'MDR_Hold_Status'   AND HOLDSTATUS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  

	  	--Class
 LEFT JOIN DATAOBJPR ClassDesignation ON ClassDesignation.OBJOBID = COMPONENTITEM.OBID AND ClassDesignation.PROPERTYDEFUID = 'SpcNonPublishedClassDesignation' AND  ClassDesignation.TERMINATIONDATE = '9999/12/31-23:59:59:999'
 
  	  	--Assembly
 LEFT JOIN DATAOBJPR IsAssembly ON IsAssembly.OBJOBID = COMPONENTITEM.OBID AND IsAssembly.PROPERTYDEFUID = 'SPC_Assembly_IsSimple' AND  IsAssembly.TERMINATIONDATE = '9999/12/31-23:59:59:999'
 
	 WHERE  
	 (COMPONENTITEM.OBJNAME LIKE '%-TRAY-%' OR 
	 COMPONENTITEM.OBJNAME LIKE '857-CTI%' OR
	 COMPONENTITEM.OBJNAME LIKE '857-CLI%' OR
	 COMPONENTITEM.OBJNAME LIKE '857-CTP%' OR 
	 COMPONENTITEM.OBJNAME LIKE '857-CLP%' )
	 
	 AND COMPONENTITEM.TERMINATIONDATE = '9999/12/31-23:59:59:999' 
 -- AND COMPONENTITEM.OBJNAME = '854-CLI1C-109-TRAY-0001'