WITH SPCRPT_WORKSTEP_IOBJ_PROP_TMP as 
(
  
SELECT
            COMPWORKSTEP.OBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP.OBJUID AS "COMPWORKSTEPUID",	  
            COMPWORKSTEP.CONFIG AS "PROJECT",
            COMPWORKSTEP.LASTUPDATED AS "LASTUPDATED",
            COMPWORKSTEP.CREATIONUSER AS "LASTUPDATEDBY"
FROM DATAOBJ COMPWORKSTEP WHERE COMPWORKSTEP.OBJDEFUID = 'SPC_ComponentWorkTypeStep' AND COMPWORKSTEP.TERMINATIONDATE = '9999/12/31-23:59:59:999'),

SPCRPT_SPOOL_TMP as
(

  SELECT 
              COMPONENTITEM.OBID AS "COMPOBID",
              COMPONENTITEM.OBJUID AS "COMPUID",
              COMPONENTITEM.CONFIG AS "PROJECT"
	--		  SUBSTRING(SPOOL_IWP_REL.CREATIONDATE, 1, 10) AS SPOOL_IWP_DATEPACKAGED
			  
  FROM DATAOBJ COMPONENTITEM 
  
  --LEO
  
  --LEFT JOIN DATAREL SPOOL_IWP_REL ON SPOOL_IWP_REL.UID2 = COMPONENTITEM.OBJUID  AND SPOOL_IWP_REL.DEFUID = 'SPC_Package_ComponentItems' AND SPOOL_IWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  WHERE COMPONENTITEM.OBJDEFUID IN ('SPC_Spool','SPC_ComponentItem') AND COMPONENTITEM.TERMINATIONDATE = '9999/12/31-23:59:59:999'
),
SPCRPT_WORKSTEP_DIR_PROP_TMP as 
(	
SELECT
            COMPWORKSTEP.COMPWORKSTEPOBID AS "COMPWORKSTEPOBID",
            CASE WHEN COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE>0 then  COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONDATE ELSE COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONDATE  END as "LASTUPDATED",
            COMPWORKSTEP_NAME.STRVALUE AS "NAME", 
            COMPWORKSTEP_DESCRIPTION.STRVALUE AS "DESCRIPTION",
            CAST(COMPWORKSTEP_SEQUENCE.STRVALUE AS INT) AS "SEQUENCE",
            CAST(COMPWORKSTEP_PLANNEDMANHOURS.STRVALUE AS FLOAT) AS "PLANNEDMANHOURS",
            CAST(COMPWORKSTEP_ACTUALMANHOURS.STRVALUE AS FLOAT) AS "ACTUALMANHOURS",
            COMPWORKSTEP_DATECOMPLETE.STRVALUE AS "ACTUALDATECOMPLETE",
            CAST(COMPWORKSTEP_ACTUALQTY.STRVALUE AS FLOAT) AS "ACTUALQUANTITY",
            CAST(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE AS FLOAT) AS "COMPLETEQUANTITY",
            CASE WHEN COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE>0 then  COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONUSER ELSE COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONUSER  END as  "LASTUPDATEDBY"
          
FROM SPCRPT_WORKSTEP_IOBJ_PROP_TMP COMPWORKSTEP
	
	--Name
	LEFT JOIN DATAOBJPR COMPWORKSTEP_NAME ON COMPWORKSTEP_NAME.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_NAME.PROPERTYDEFUID = 'Name' AND COMPWORKSTEP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--Description
	LEFT JOIN DATAOBJPR COMPWORKSTEP_DESCRIPTION ON COMPWORKSTEP_DESCRIPTION.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_DESCRIPTION.PROPERTYDEFUID = 'Description' AND COMPWORKSTEP_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--Sequence
	LEFT JOIN DATAOBJPR COMPWORKSTEP_SEQUENCE ON COMPWORKSTEP_SEQUENCE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_SEQUENCE.PROPERTYDEFUID = 'ComponentWorkTypeStep_Sequence' AND COMPWORKSTEP_SEQUENCE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--PlannedManHours
	LEFT JOIN DATAOBJPR COMPWORKSTEP_PLANNEDMANHOURS ON COMPWORKSTEP_PLANNEDMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_PLANNEDMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ManHours' AND COMPWORKSTEP_PLANNEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--ActualManHours
	LEFT JOIN DATAOBJPR COMPWORKSTEP_ACTUALMANHOURS ON COMPWORKSTEP_ACTUALMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_ACTUALMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualHours' AND COMPWORKSTEP_ACTUALMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  LEFT JOIN DATAOBJPR COMPWORKSTEP_DATECOMPLETE ON COMPWORKSTEP_DATECOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_DATECOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualDateComplete' 
--AND COMPWORKSTEP_DATECOMPLETE.CREATIONUSER<>'superuser' 
AND COMPWORKSTEP_DATECOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'



LEFT JOIN DATAOBJPR COMPWORKSTEP_ACTUALQTY ON COMPWORKSTEP_ACTUALQTY.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_ACTUALQTY.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualQuantity' 
--AND COMPWORKSTEP_ACTUALQTY.CREATIONUSER<>'superuser' 
AND  COMPWORKSTEP_ACTUALQTY.TERMINATIONDATE = '9999/12/31-23:59:59:999'


	LEFT JOIN DATAOBJPR COMPWORKSTEP_QUANTITYCOMPLETE ON COMPWORKSTEP_QUANTITYCOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_QUANTITYCOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_QuantityComplete' 
--AND COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONUSER<>'superuser' 
AND  COMPWORKSTEP_QUANTITYCOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
),

SPCRPT_WORKSTEP_REL_PROP_TMP as 
(	
	
SELECT
            COMPWORKSTEP.COMPWORKSTEPOBID AS "COMPWORKSTEPOBID",            
            COMPWORKSTEP_WORKTYPE_COSTCODE.STRVALUE AS "COSTCODE",
            COMPWORKSTEP_FIWP.OBID AS "FIWPOBID",	  
            COMPWORKSTEP_WORKTYPE.OBID AS "WORKTYPEOBID",
            COMPWORKSTEP_COMP.OBID AS "COMPOBID",
            CAST(COMPONENTITEM_QUANTITYPLANNED.STRVALUE AS FLOAT) AS "QUANTITYPLANNED",
            FIWP_PURPOSE.OBJNAME AS "PURPOSE"
FROM SPCRPT_WORKSTEP_IOBJ_PROP_TMP COMPWORKSTEP
	
	--IWP
	LEFT JOIN DATAREL COMPWORKSTEP_FIWP_REL ON COMPWORKSTEP_FIWP_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID  AND COMPWORKSTEP_FIWP_REL.DEFUID = 'SPC_Package_ComponentWorkTypeStep' AND COMPWORKSTEP_FIWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_FIWP ON COMPWORKSTEP_FIWP.OBJUID = COMPWORKSTEP_FIWP_REL.UID1 AND COMPWORKSTEP_FIWP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--WorkType
	LEFT JOIN DATAREL COMPWORKSTEP_WORKTYPE_REL ON COMPWORKSTEP_WORKTYPE_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID AND COMPWORKSTEP_WORKTYPE_REL.DEFUID = 'SPC_ComponentWorkType_ComponentWorkTypeSteps' AND COMPWORKSTEP_WORKTYPE_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_WORKTYPE ON COMPWORKSTEP_WORKTYPE.OBJUID = COMPWORKSTEP_WORKTYPE_REL.UID1 AND COMPWORKSTEP_WORKTYPE.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_WORKTYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	--Cost Code
	LEFT JOIN DATAOBJPR COMPWORKSTEP_WORKTYPE_COSTCODE ON COMPWORKSTEP_WORKTYPE_COSTCODE.OBJOBID = COMPWORKSTEP_WORKTYPE.OBID AND COMPWORKSTEP_WORKTYPE_COSTCODE.PROPERTYDEFUID = 'ComponentWorkType_CostCode' AND COMPWORKSTEP_WORKTYPE_COSTCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--Component
	LEFT JOIN DATAREL COMPWORKSTEP_COMP_REL ON COMPWORKSTEP_COMP_REL.UID2 = COMPWORKSTEP_WORKTYPE.OBJUID AND COMPWORKSTEP_COMP_REL.DEFUID = 'SPC_ComponentItem_ComponentWorkType' AND COMPWORKSTEP_COMP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_COMP ON COMPWORKSTEP_COMP.OBJUID = COMPWORKSTEP_COMP_REL.UID1 AND COMPWORKSTEP_COMP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_COMP.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--Quantity Planned
	LEFT JOIN DATAOBJPR COMPONENTITEM_QUANTITYPLANNED ON COMPONENTITEM_QUANTITYPLANNED.OBJOBID = COMPWORKSTEP_COMP.OBID AND COMPONENTITEM_QUANTITYPLANNED.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_QUANTITYPLANNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  LEFT JOIN DATAOBJPR FIWP_PURPOSE_PR ON FIWP_PURPOSE_PR.OBJOBID = COMPWORKSTEP_FIWP.OBID AND FIWP_PURPOSE_PR.PROPERTYDEFUID = 'FIWP_Purpose' AND FIWP_PURPOSE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_PURPOSE ON FIWP_PURPOSE.OBJUID = FIWP_PURPOSE_PR.STRVALUE AND FIWP_PURPOSE.TERMINATIONDATE = '9999/12/31-23:59:59:999'),
	
SPCRPT_COMPONENTWORKSTEP  as
(   
  SELECT
  -- Section #5a: IObject properties
        t1.COMPWORKSTEPOBID, COMPWORKSTEPUID, PROJECT, NAME as "EVENTS", SEQUENCE,  --DESCRIPTION, UNITRATE, RATEUOM, NOTES, 
        PLANNEDMANHOURS, ACTUALMANHOURS, ACTUALDATECOMPLETE, ACTUALQUANTITY,COMPLETEQUANTITY, -- sample: Prop2Column,
            COSTCODE, FIWPOBID, WORKTYPEOBID, COMPOBID, QUANTITYPLANNED , t2.LASTUPDATED, t2.DESCRIPTION, t3.PURPOSE, t2.LASTUPDATEDBY -- sample: ,Prop3Column	  
  FROM SPCRPT_WORKSTEP_IOBJ_PROP_TMP t1
  LEFT JOIN SPCRPT_WORKSTEP_DIR_PROP_TMP t2 ON t2.COMPWORKSTEPOBID = t1.COMPWORKSTEPOBID
  LEFT JOIN SPCRPT_WORKSTEP_REL_PROP_TMP t3 ON t3.COMPWORKSTEPOBID = t1.COMPWORKSTEPOBID
),

DETAILBYTAG as
(
SELECT 
            COMPONENTITEM.COMPWORKSTEPOBID,
            COMPONENTITEM.COMPOBID AS "COMPOBID",
            COMPONENTITEM.FIWPOBID,
            COMPONENTITEM.DESCRIPTION,
            COMPONENTITEM.PROJECT, COMPONENTITEM.PURPOSE,
            COMPONENTITEM_NAME.STRVALUE AS "NAME",

            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'SUP')>0 THEN 'NTS' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'PEN')>0 THEN 'PEN' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'CUT')>0 THEN 'PEN' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'NTS')>0 THEN 'NTS' ELSE 
              UPPER(SUBSTRING(COMPONENTITEM_NAME.STRVALUE,7,1))     
            END END END END as SUPPORTGROUP,
        
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), '-CD')>0 THEN 'CD' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), '-MD')>0 THEN 'MD' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), '-MZ')>0 THEN 'MZ' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), '-HD')>0 THEN 'HD' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'ZD')>0 THEN 'MZ' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'UD')>0 THEN 'UD' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'AW')>0 THEN 'WD' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'BLDG')>0 THEN 'BLDG' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'BHD')>0 THEN 'HD' ELSE 
            CASE WHEN CHARINDEX(UPPER(COMPONENTITEM_NAME.STRVALUE), 'WD')>0 THEN 'WD' ELSE 
            --CASE WHEN INSTR(UPPER(COMPONENTITEM_NAME.STRVALUE), 'MD')>0 THEN 'MD' ELSE      
              UPPER(SUBSTRING(COMPONENTITEM_NAME.STRVALUE,5,2))     
            END END END END END END END END END END as SUPPORTLOCATION,
        
            COMPONENTITEM.EVENTS,
            COMPONENTITEM.SEQUENCE,
            COMPONENTITEM.ACTUALQUANTITY,
            COMPONENTITEM.COMPLETEQUANTITY,
	    COMPONENTITEM.QUANTITYPLANNED,
	
            SUPPORTTYPE.STRVALUE AS "SUPPORTTYPE",
            AREADESC.STRVALUE AS "AREADESC",
            --SURFACEAREA.STRVALUE AS "SURFACEAREA",
            WEIGHT.STRVALUE AS "WEIGHT",
            SUPPORTDRAWING.STRVALUE AS "SUPPORTDRAWING",
            TRANSMITTAL.STRVALUE AS "TRANSMITTAL",
            DRAWINGREV.STRVALUE AS "DRAWINGREV",
            DELIVERY.STRVALUE AS "DELIVERY",
          --  FABHRS.STRVALUE AS "FABHRS"
           CAST(COMPONENTITEM.PLANNEDMANHOURS AS FLOAT) AS "FABHRS",
          CAST(COMPONENTITEM.ACTUALMANHOURS AS FLOAT) AS "ACTUALHRS", 
          CASE WHEN COMPONENTITEM.PLANNEDMANHOURS>0 THEN COMPONENTITEM.ACTUALMANHOURS / COMPONENTITEM.PLANNEDMANHOURS ELSE 0 END as "PROGRESS",
          FIWP_NAME.STRVALUE AS "WPNO",
          FIWP_REVDATE.STRVALUE AS "REVDATE",
          enumpr.objname AS "REVNO",		  
          FIWP_DISCIPLINE.OBJNAME AS "DISCIPLINE",
          SUBSTRING(COMPONENTITEM.ACTUALDATECOMPLETE, 1,10)  as "DATEPROGRESS",
          SUBSTRING(COMPONENTITEM.LASTUPDATED, 1,10)  as "DATEPROGRESS1",
          COMPONENTITEM_ELEVATION.STRVALUE as "ELEVATION",
          COMPONENTITEM_SURFACEAREA.STRVALUE as "SURFACEAREA", 
          COMPONENTITEM_ASSEMBLY.STRVALUE as "ASSM_SURFACEAREA",
          COMPONENTITEM_ZONE.STRVALUE as "ZONE",
          COMPONENTITEM_SUPPORTHEIGHT.STRVALUE as "SUPPORTHEIGHT",
          MATERIAL.STRVALUE as "MATERIAL",
          LINE_NO.STRVALUE as "LINE_NO",
          WELD_DIA.STRVALUE as "WELD_DIA",
          FIELD_DIA.STRVALUE as "FIELD_DIA",
	  COMPONENTITEM_PAINTSYSTEM.STRVALUE AS "PAINTSYSTEM",
          COMPONENTITEM.LASTUPDATEDBY
      
  FROM SPCRPT_COMPONENTWORKSTEP COMPONENTITEM
	--Name
	LEFT JOIN DATAOBJPR COMPONENTITEM_NAME ON COMPONENTITEM_NAME.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_NAME.PROPERTYDEFUID = 'Name' AND COMPONENTITEM_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--Description
	LEFT JOIN DATAOBJPR COMPONENTITEM_DESCRIPTION ON COMPONENTITEM_DESCRIPTION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DESCRIPTION.PROPERTYDEFUID = 'SPC_ComponentItem_ShortDescription' AND COMPONENTITEM_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR SUPPORTTYPE ON SUPPORTTYPE.OBJOBID = COMPONENTITEM.COMPOBID AND SUPPORTTYPE.PROPERTYDEFUID = 'MDR_3DSupportType' AND SUPPORTTYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR AREADESC ON AREADESC.OBJOBID = COMPONENTITEM.COMPOBID AND AREADESC.PROPERTYDEFUID = 'SPC_ComponentItem_DeckLevel' AND AREADESC.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR SURFACEAREA ON SURFACEAREA.OBJOBID = COMPONENTITEM.COMPOBID AND SURFACEAREA.PROPERTYDEFUID = 'MDR_AssmSurfaceArea' AND SURFACEAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR WEIGHT ON WEIGHT.OBJOBID = COMPONENTITEM.COMPOBID AND WEIGHT.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND WEIGHT.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR SUPPORTDRAWING ON SUPPORTDRAWING.OBJOBID = COMPONENTITEM.COMPOBID AND SUPPORTDRAWING.PROPERTYDEFUID = 'SPC_FabricationDrawing' AND SUPPORTDRAWING.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR MATERIAL ON MATERIAL.OBJOBID = COMPONENTITEM.COMPOBID AND MATERIAL.PROPERTYDEFUID = 'SPC_ComponentItem_Material' AND MATERIAL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR LINE_NO ON LINE_NO.OBJOBID = COMPONENTITEM.COMPOBID AND LINE_NO.PROPERTYDEFUID = 'SPC_CustomLineNumber' AND LINE_NO.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR WELD_DIA ON WELD_DIA.OBJOBID = COMPONENTITEM.COMPOBID AND WELD_DIA.PROPERTYDEFUID = 'MDR_Spool_WeldDiameter' AND WELD_DIA.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR FIELD_DIA ON FIELD_DIA.OBJOBID = COMPONENTITEM.COMPOBID AND FIELD_DIA.PROPERTYDEFUID = 'MDR_FieldWeldDia' AND FIELD_DIA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  LEFT JOIN DATAOBJPR TRANSMITTAL ON TRANSMITTAL.OBJOBID = COMPONENTITEM.COMPOBID AND TRANSMITTAL.PROPERTYDEFUID = 'MDR_IDOCS_TransmittalNo' AND TRANSMITTAL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR DRAWINGREV ON DRAWINGREV.OBJOBID = COMPONENTITEM.COMPOBID AND DRAWINGREV.PROPERTYDEFUID = 'MDR_IDOCS_DrawingRevision' AND DRAWINGREV.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR DELIVERY ON DELIVERY.OBJOBID = COMPONENTITEM.COMPOBID AND DELIVERY.PROPERTYDEFUID = 'MDR_DeliveryCHARINDEXuction' AND DELIVERY.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
--LEFT JOIN DATAOBJPR FABHRS ON FABHRS.OBJOBID = COMPONENTITEM.COMPOBID AND FABHRS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ManHours' AND FABHRS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
LEFT JOIN DATAOBJPR FIWP_NAME ON FIWP_NAME.OBJOBID = COMPONENTITEM.FIWPOBID AND FIWP_NAME.PROPERTYDEFUID = 'Name' AND FIWP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
--MDR REVDATE
       LEFT JOIN DATAOBJPR FIWP_REVDATE ON FIWP_REVDATE.OBJOBID = COMPONENTITEM.FIWPOBID AND FIWP_REVDATE.PROPERTYDEFUID = 'MDR_RevDate' AND FIWP_REVDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	   
--MDR REV
       LEFT JOIN DATAOBJPR FIWP_REVNO ON FIWP_REVNO.OBJOBID = COMPONENTITEM.FIWPOBID AND FIWP_REVNO.PROPERTYDEFUID = 'MDR_Rev' AND FIWP_REVNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'	


  left join schemaobj enumpr on FIWP_REVNO.strvalue=enumpr.objuid and enumpr.objdefuid='EnumEnum' and enumpr.terminationdate='9999/12/31-23:59:59:999'	   

--LEFT JOIN DATAOBJPR COMPWORKSTEP_DATECOMPLETE ON COMPWORKSTEP_DATECOMPLETE.OBJOBID = COMPONENTITEM.COMPWORKSTEPOBID AND COMPWORKSTEP_DATECOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualDateComplete'-- AND COMPWORKSTEP_DATECOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  	--IWP DISCIPLINE
	LEFT JOIN DATAOBJPR FIWP_DISCIPLINE_PR ON FIWP_DISCIPLINE_PR.OBJOBID = COMPONENTITEM.FIWPOBID AND FIWP_DISCIPLINE_PR.PROPERTYDEFUID = 'FIWP_Discipline' AND FIWP_DISCIPLINE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_DISCIPLINE ON FIWP_DISCIPLINE.OBJUID = FIWP_DISCIPLINE_PR.STRVALUE AND FIWP_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  --LEFT JOIN DATAOBJPR COMPONENTITEM_ZONE ON COMPONENTITEM_ZONE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_ZONE.PROPERTYDEFUID = 'SPC_ComponentItem_Zone' AND COMPONENTITEM_ZONE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_ELEVATION ON COMPONENTITEM_ELEVATION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_ELEVATION.PROPERTYDEFUID = 'MDR_ElevationDesc' AND COMPONENTITEM_ELEVATION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_SURFACEAREA ON COMPONENTITEM_SURFACEAREA.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_SURFACEAREA.PROPERTYDEFUID = 'MDR_SurfaceArea' AND COMPONENTITEM_SURFACEAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_ASSEMBLY ON COMPONENTITEM_ASSEMBLY.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_ASSEMBLY.PROPERTYDEFUID = 'MDR_AssmSurfaceArea' AND COMPONENTITEM_ASSEMBLY.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_ZONE ON COMPONENTITEM_ZONE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_ZONE.PROPERTYDEFUID = 'SPC_ComponentItem_Zone' AND COMPONENTITEM_ZONE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_SUPPORTHEIGHT ON COMPONENTITEM_SUPPORTHEIGHT.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_SUPPORTHEIGHT.PROPERTYDEFUID = 'MDR_SupportHeight' AND COMPONENTITEM_SUPPORTHEIGHT.TERMINATIONDATE = '9999/12/31-23:59:59:999'

--Paint System
  	LEFT JOIN DATAOBJPR COMPONENTITEM_PAINTSYSTEM ON COMPONENTITEM_PAINTSYSTEM.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_PAINTSYSTEM.PROPERTYDEFUID = 'MDR_PaintSystem' AND  COMPONENTITEM_PAINTSYSTEM.TERMINATIONDATE = '9999/12/31-23:59:59:999'
   
  WHERE 
  SUBSTRING(COMPONENTITEM_NAME.STRVALUE,5,1) in('A','J','F','U','V')  AND 
    SUBSTRING(COMPONENTITEM_NAME.STRVALUE,1,1) in('A','B','C','D','E','F','G','H','J','V','P')
  --AND FIWP_DISCIPLINE.OBJNAME IN('Piping', 'Coating')
 -- FIWP_DISCIPLINE.OBJNAME IN('Coating')
),

DUMP AS
( 
    SELECT ax.COMPWORKSTEPOBID, ax.FIWPOBID,
    ax.Project, 
    ax.Name,    
    ax.PURPOSE,
    CASE SUPPORTGROUP
       WHEN 'A' THEN 'STANDARD PIPE SUPPORT'
       WHEN 'B' THEN 'SPECIAL PIPE SUPPORT'
       WHEN 'C' THEN 'PRIMARY CABLE TRAY SUPPORT'
       WHEN 'D' THEN 'SECONDARY CABLE TRAY SUPPORT'
       WHEN 'E' THEN 'TUBING TRAY SUPPORT'
       WHEN 'F' THEN '4 INCH FIELD CABLE TRAY SUPPORT'
       WHEN 'G' THEN '4 INCH FIELD TUBE TRAY SUPPORT'
       WHEN 'H' THEN 'STANDARD PIPE SUPPORT'
       WHEN 'J' THEN 'SPECIAL PIPE SUPPORT'
       WHEN 'K' THEN 'PRIMARY CABLE TRAY SUPPORT'
       WHEN 'L' THEN 'SECONDARY CABLE TRAY SUPPORT'
       WHEN 'M' THEN 'TUBING TRAY SUPPORT'
       WHEN 'N' THEN '4 INCH FIELD CABLE TRAY SUPPORT'
       WHEN 'P' THEN '4 INCH FIELD TUBE TRAY SUPPORT'
       WHEN 'Q' THEN 'HVAC SYSTEM (SUBCON)'
       WHEN 'R' THEN 'BUILDING ARCH AND PIPING (SUBCON)'
       WHEN 'NTS' THEN 'NON TRAY SUPPORTS'
       WHEN 'PEN' THEN 'PENETRATION SUPPORTS'
    END as "SUPPORTTYPE", ax.SUPPORTLOCATION,
    
    CASE ax.SUPPORTLOCATION
      WHEN 'AJ' THEN 'JACKET AREA'
      WHEN 'AL' THEN 'ABOVE BOAT LANDING'
      WHEN 'BL' THEN 'BELOW BOAT LANDING'
      WHEN 'AC' THEN 'ABOVE CELLAR DECK'
      WHEN 'BC' THEN 'BELOW CELLAR DECK'
      WHEN 'AM' THEN 'ABOVE MAIN DECK'
      WHEN 'BM' THEN 'BELOW MAIN DECK'
      WHEN 'AZ' THEN 'ABOVE MEZZANINE DECK'
      WHEN 'BZ' THEN 'BELOW MEZZANINE DECK'
      WHEN 'AU' THEN 'ABOVE UPPER DECK'
      WHEN 'BU' THEN 'BELOW UPPER DECK'
      WHEN 'AP' THEN 'ABOVE MANIFOLD DECK'
      WHEN 'BP' THEN 'BELOW MANIFOLD DECK'
      WHEN 'AH' THEN 'ABOVE HELI DECK'
      WHEN 'BH' THEN 'BELOW HELI DECK'
      WHEN 'AD' THEN 'FLARE BOOM'
      WHEN 'AF' THEN 'FLARE TOWER'
      WHEN 'AB' THEN 'ABOVE BRIDGE CONNECTION'
      WHEN 'AN' THEN 'ABOVE WELLHEAD ACCESS DECK'
      WHEN 'BN' THEN 'BELOW WELLHEAD ACCESS DECK'
      WHEN 'BW' THEN 'BELOW E AND I BUILDING'
      WHEN 'AW' THEN 'ABOVE E AND i BUILDING'
      WHEN 'MD' THEN 'MAIN DECK'
      WHEN 'CD' THEN 'CELLAR DECK'
      WHEN 'MZ' THEN 'MEZZANINE DECK'
      WHEN 'HD' THEN 'HELI DECK'
      WHEN 'UD' THEN 'UPPER DECK'
      WHEN 'WD' THEN 'WELLHEAD'
      WHEN 'BLDG' THEN 'BUILDING'
    END AS "AREADESCx",	
    ax.AREADESC,
    ax.ASSM_SURFACEAREA as "SURFACEAREA",	
    ax.WEIGHT,	
    ax.SUPPORTDRAWING,	
    ax.TRANSMITTAL,
    ax.DRAWINGREV,	
    ax.ELEVATION,
    ax.DISCIPLINE,
    ax.WPNO, ax.REVDATE,ax.REVNO, ax.ZONE, ax.EVENTS , ax.SEQUENCE, ax.SUPPORTHEIGHT,  ax.SUPPORTGROUP, ax.ACTUALHRS , MATERIAL, LINE_NO,    
    WELD_DIA, FIELD_DIA,PAINTSYSTEM,
    --FABRICATION
    CASE WHEN ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.WPNO else null end as FE_FabWPNo,
    CASE WHEN ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.FABHRS else null end as FE_FabHrs, 
    CASE WHEN ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.ACTUALHRS else null end as FE_FabEarned, 

	 --FAB REVDATE
       CASE WHEN ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.REVDATE else null end as FE_REVDATE,
	 --FAB REVNO
       CASE WHEN ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.REVNO else null end as FE_REVNO,
    --SPOOL_IWP_DATEPACKAGED
	--    CASE WHEN ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ay.SPOOL_IWP_DATEPACKAGED else null end as FE_Fab_PackagedDate,


    --CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS --ELSE null END ELSE NULL END as FE_FITUP,
    --CASE WHEN ax.SEQUENCE = 2 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS --ELSE null END ELSE NULL END as FE_WELD,
    --CASE WHEN ax.SEQUENCE = 3 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS --ELSE null END ELSE NULL END as FE_NDT,
    --CASE WHEN ax.SEQUENCE = 4 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS --ELSE null END ELSE NULL END as FE_DELIVERY, 
    
    CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.DATEPROGRESS1 ELSE null END  as FE_FITUP,
    CASE WHEN ax.SEQUENCE = 2 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.DATEPROGRESS1 ELSE null END  as FE_WELD,
    CASE WHEN ax.SEQUENCE = 3 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.DATEPROGRESS1 ELSE null END  as FE_NDT,
    CASE WHEN ax.SEQUENCE = 4 AND ax.PURPOSE = 'Fabrication' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.DATEPROGRESS1 ELSE null END  as FE_DELIVERY, 

 --Work Step Progress 
    --CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as FE_FITUPPRO,
    --CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as FE_WELDPRO,
	--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as FE_NDTPRO,
	--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as FE_DELIVERYPRO,

 --Work Step Progress With QTY completed 20260702

CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as FE_FITUPPRO,
    CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as FE_WELDPRO,
	CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as FE_NDTPRO,
	CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE in('Fabrication','Fabrication - Site Run') AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as FE_DELIVERYPRO,


    --INSTALLATION    
    CASE WHEN ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.WPNO else null end as IE_InstallWPNo,
    CASE WHEN ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.FABHRS else null end as IE_InstallHrs,
    CASE WHEN ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.ACTUALHRS else null end as IE_InstallEarned,

	--INSREVDATE
	CASE WHEN ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.REVDATE else null end as IE_REVDATE,
	
	--INSREVNO
	CASE WHEN ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.REVNO else null end as IE_REVNO,
	

    CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_HUNG,
    CASE WHEN ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_FITUP,
    CASE WHEN ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_WELD,
 CASE WHEN ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_INSTALL,
 CASE WHEN ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_NDT,
    
   
--Work Step Progress Installation
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_HUNGPRO,
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_FITUPPRO,
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_WELDPRO,
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_INSTALLPRO,
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_NDTPRO,

--Work Step Progress Installation WITH QTY COMPLETED 20260702

CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_HUNGPRO,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_FITUPPRO,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_WELDPRO,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_INSTALLPRO,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_NDTPRO,

--Work hrs Progress Installation
     CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0) ELSE 0 END as IE_HUNG_EARN,
    CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0) ELSE 0 END as IE_FITUP_EARN,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0) ELSE 0 END as IE_WELD_EARN,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0) ELSE 0 END as IE_INSTALL_EARN,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0) ELSE 0 END as IE_NDT_EARN,

--Plan hrs Progress Installation
     CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.FABHRS,0) ELSE 0 END as IE_HUNG_PLAN,
    CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.FABHRS,0) ELSE 0 END as IE_FITUP_PLAN,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.FABHRS,0) ELSE 0 END as IE_WELD_PLAN,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.FABHRS,0) ELSE 0 END as IE_INSTALL_PLAN,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.FABHRS,0) ELSE 0 END as IE_NDT_PLAN,

   --INSTALLATION SITE
    CASE WHEN ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.WPNO else null end as IE_Site_InstallWPNo,
    CASE WHEN ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.FABHRS else null end as IE_Site_InstallHrs,
    CASE WHEN ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.ACTUALHRS else null end as IE_Site_InstallEarned,

	--INSREVDATE
	CASE WHEN  ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.REVDATE else null end as IE_SITE_REVDATE,
	
	--INSREVNO
	CASE WHEN  ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then ax.REVNO else null end as IE_SITE_REVNO,
	

    CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_Site_PREP,
    CASE WHEN ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_Site_HUNG,
    CASE WHEN ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_Site_FITUP,
 CASE WHEN ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_Site_INSTALL,
 CASE WHEN ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IE_Site_NDT,
    
   
--Work Step Progress Installation
     --CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_Site_PREPPRO,
    --CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_Site_HUNGPRO,
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_Site_FITUPPRO,
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_Site_INSTALLPRO,
--CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as IE_Site_NDTPRO,

--Work Step Progress Installation SITE RUN WITH QTY COMPLED 20260702

   CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_Site_PREPPRO,
    CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_Site_HUNGPRO,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 3 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_Site_FITUPPRO,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 4 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_Site_INSTALLPRO,
CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 5 AND ax.PURPOSE = 'Installation - Site Run' AND ax.Discipline in ('Electrical','Piping','CHARINDEXumentation') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as IE_Site_NDTPRO,


    --PAINTING / ERECTION
    CASE WHEN ax.PURPOSE like 'Erection - Blast%' AND ax.Discipline='Coating' then ax.WPNO else null end as EB_CoatingInstallWPNo,
    CASE WHEN ax.PURPOSE like 'Erection - Blast%' AND ax.Discipline='Coating' then ax.FABHRS else null end as EB_CoatingInstallHrs,
    CASE WHEN ax.PURPOSE like 'Erection - Blast%' AND ax.Discipline='Coating' then ax.ACTUALHRS else null end as EB_CoatingInstallEarned,
    
    CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE like 'Erection - Blast%' AND ax.Discipline='Coating' then ax.DATEPROGRESS ELSE NULL END as EB_BLASTANDPRIME,
    
    CASE WHEN ax.PURPOSE like 'Erection - Intermediate%' AND ax.Discipline='Coating' then ax.WPNO else null end as EI_CoatingInstallWPNo,
    CASE WHEN ax.PURPOSE like 'Erection - Intermediate%' AND ax.Discipline='Coating' then ax.FABHRS else null end as EI_CoatingInstallHrs,
    CASE WHEN ax.PURPOSE like 'Erection - Intermediate%' AND ax.Discipline='Coating' then ax.ACTUALHRS else null end as EI_CoatingInstallEarned,
    CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE like 'Erection - Intermediate%' AND ax.Discipline='Coating' then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as EI_MIDCOAT,
    CASE WHEN ax.SEQUENCE = 2 AND ax.PURPOSE like 'Erection - Intermediate%' AND ax.Discipline='Coating' then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as EI_TOPCOAT,
    
   
    --PAINTING / FABRICATION
    CASE WHEN ax.PURPOSE like 'IPF - Blast%' AND ax.Discipline='Coating' then ax.WPNO else null end as IPFB_CoatingFABWPNo,
    CASE WHEN ax.PURPOSE like 'IPF - Blast%' AND ax.Discipline='Coating' then ax.FABHRS else null end as IPFB_CoatingFABHrs,
    CASE WHEN ax.PURPOSE like 'IPF - Blast%' AND ax.Discipline='Coating' then ax.ACTUALHRS else null end as IPFB_CoatingFABEarned,
    
    CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE like 'IPF - Blast%' AND ax.Discipline='Coating' then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IPFB_BLASTANDPRIME,
    CASE WHEN ax.SEQUENCE = 2 AND ax.PURPOSE like 'IPF - Blast%' AND ax.Discipline='Coating' then CASE WHEN ax.FABHRS= ax.ACTUALHRS THEN ax.DATEPROGRESS1 ELSE null END ELSE NULL END as IPFB_PROJECTPRIMER,
    
    CASE WHEN ax.PURPOSE like 'IPF - Intermediate%' AND ax.Discipline='Coating' then ax.WPNO else null end as IPFI_CoatingInstallWPNo,
    CASE WHEN ax.PURPOSE like 'IPF - Intermediate%' AND ax.Discipline='Coating' then ax.FABHRS else null end as IPFI_CoatingInstallHrs,
    CASE WHEN ax.PURPOSE like 'IPF - Intermediate%' AND ax.Discipline='Coating' then ax.ACTUALHRS else null end as IPFI_CoatingInstallEarned,
    
    CASE WHEN ax.SEQUENCE = 1 AND ax.PURPOSE like 'IPF - Intermediate & Top' AND ax.Discipline='Coating' THEN ax.DATEPROGRESS1 ELSE  NULL END as IPFI_MIDCOAT,
    CASE WHEN ax.SEQUENCE = 2 AND ax.PURPOSE like 'IPF - Intermediate & Top' AND ax.Discipline='Coating' THEN ax.DATEPROGRESS1 ELSE  NULL END as IPFI_TOPCOAT,

	
    --Work Step Progress 
     --CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE in('IPF - Intermediate & Top') AND ax.Discipline in ('Coating') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as I_MIDCOATPRO,
    --CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE in('IPF - Intermediate & Top') AND ax.Discipline in ('Coating') then nullif(ax.ACTUALHRS,0)/ nullif(ax.FABHRS,0)*100 ELSE 0 END as I_TOPCOATPRO,

 --Work Step Progress WITH QTY COMPLETED 20260702
     CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 1 AND ax.PURPOSE in('IPF - Intermediate & Top') AND ax.Discipline in ('Coating') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as I_MIDCOATPRO,
    CASE WHEN ax.FABHRS > 0 And ax.SEQUENCE = 2 AND ax.PURPOSE in('IPF - Intermediate & Top') AND ax.Discipline in ('Coating') then nullif(ax.COMPLETEQUANTITY,0)/ nullif(ax.QUANTITYPLANNED,0)*100 ELSE 0 END as I_TOPCOATPRO,


    CASE WHEN ax.Discipline in ('Piping','Coating') then  ax.DATEPROGRESS else null end as LASTPROGRESSDATE, ax.LASTUPDATEDBY
    
 
    FROM DETAILBYTAG ax     
    INNER JOIN SPCRPT_SPOOL_TMP ay
    on ax.COMPOBID=ay.COMPOBID
    --where ax.NAME='DBJJA003401' 
     --order by WPNO, SEQUENCE
),

FINAL as (

 
SELECT 
 
    ax.Project as "PLANT NAME", 
    ax.Name as "TAG", 
    --ax.DISCIPLINE,
    --ax.PURPOSE,
    --ax.SUPPORTTYPE as "SUPPORT TYPE", 
    ax.AREADESC as "LEVEL",	
    --ax.SURFACEAREA as "SURFACE AREA",	
    --ax.WEIGHT as "WEIGHT",	
    ax.SUPPORTDRAWING as "SPOOL DRAWING",	
    --ax.TRANSMITTAL,
    --ax.DRAWINGREV as "REV",	
    --ax.ELEVATION as "ELEVATION",   
    MATERIAL , LINE_NO, WELD_DIA, FIELD_DIA, PAINTSYSTEM,
  --ax.ZONE as "ZONE", 
  --ax.SUPPORTHEIGHT,    
  --ax.SUPPORTGROUP, 
  --ax.SUPPORTLOCATION ,

   MAX(FE_REVDATE) AS FABWPREVDATE,
   MAX(FE_REVNO) AS FABWPREVNO,
--   MAX(ax.FE_Fab_PackagedDate) AS FAB_PACKAGEDATE,

  MAX(ax.FE_FabWPNo) as FabWPNo,
  SUM(ax.FE_FabHrs) as FabHrs,
  SUM(ax.FE_FabEarned) as FabEarned,
  MAX(ax.FE_FITUP) as FITUP,
  MAX(ax.FE_WELD) as WELD,
  MAX(ax.FE_NDT) as NDT,
  MAX(ax.FE_DELIVERY) as DELIVERY,
  
 MAX(ax.FE_FITUPPRO) as FITUPPROG,
  MAX(ax.FE_WELDPRO) as WELDPROG,
  MAX(ax.FE_NDTPRO) as NDTPROG,
	MAX(ax.FE_DELIVERYPRO) as DELIVERYPROG,

  MAX(ax.IPFI_CoatingInstallWPNo) as I_TopCoatWPNo,
  SUM(ax.IPFI_CoatingInstallHrs) as IPFI_TopCoatlHrs,  
  --SUM(ax.IPFI_CoatingInstallEarned) as IPFI_TopCoatEarned,  
  MAX(ax.IPFI_MIDCOAT) as I_MIDCOAT,
  MAX(ax.IPFI_TOPCOAT) as I_TOPCOAT,

  MAX(ax.I_MIDCOATPRO) as I_MIDCOATPRO,
  MAX(ax.I_TOPCOATPRO) as I_TOPCOATPRO,

  
   MAX(ax.IE_REVDATE) as INSWPREVDATE,
   MAX(ax.IE_REVNO) as INSWPREVNO,

  MAX(ax.IE_InstallWPNo) as InstallWPNo,
  SUM(ax.IE_InstallHrs) as InstallHrs,
  SUM(ax.IE_InstallEarned) as InstallEarned,
  MAX(ax.IE_HUNG) as INS_HUNG,
  MAX(ax.IE_FITUP) as INS_FITUP,
  MAX(ax.IE_WELD) as INS_WELD,
  MAX(ax.IE_INSTALL) as INS_INSTALL,
  MAX(ax.IE_NDT) as INS_NDT,

  MAX(ax.IE_HUNGPRO) as INS_HUNGPRO,
MAX(ax.IE_FITUPPRO) as INS_FITUPPRO,
 MAX(ax.IE_WELDPRO) as INS_WELDPRO,
 MAX(ax.IE_INSTALLPRO) as INS_INSTALLPRO,
 MAX(ax.IE_NDTPRO) as INS_NDTPRO,
 
  MAX(ax.IE_HUNG_EARN) as INS_HUNG_EARN,
 MAX(ax.IE_FITUP_EARN) as INS_FITUP_EARN,
 MAX(ax.IE_WELD_EARN) as INS_WELD_EARN,
 MAX(ax.IE_INSTALL_EARN) as INS_INSTALL_EARN,
 MAX(ax.IE_NDT_EARN) as INS_NDT_EARN,
 
  MAX(ax.IE_HUNG_PLAN) as INS_HUNG_PLAN,
 MAX(ax.IE_FITUP_PLAN) as INS_FITUP_PLAN,
 MAX(ax.IE_WELD_PLAN) as INS_WELD_PLAN,
 MAX(ax.IE_INSTALL_PLAN) as INS_INSTALL_PLAN,
 MAX(ax.IE_NDT_PLAN) as INS_NDT_PLAN,

   MAX(ax.IE_SITE_REVDATE) as INS_SITE_WPREVDATE,
   MAX(ax.IE_SITE_REVNO) as INS_SITE_WPREVNO,

 MAX(ax.IE_SITE_InstallWPNo) as InstallSiteWPNo,
 SUM(ax.IE_SITE_InstallHrs) as InstallSiteHrs,
 SUM(ax.IE_SITE_InstallEarned) as InstallSiteEarned,
 MAX(ax.IE_SITE_PREP) as INS_SITE_PREP,
 MAX(ax.IE_SITE_HUNG) as INS_SITE_HUNG,
 MAX(ax.IE_SITE_FITUP) as INS_SITE_FITUP,
 MAX(ax.IE_SITE_INSTALL) as INS_SITE_INSTALL,
 MAX(ax.IE_SITE_NDT) as INS_SITE_NDT,

 MAX(ax.IE_SITE_PREPPRO) as INS_SITE_PREPPRO,
 MAX(ax.IE_SITE_HUNGPRO) as INS_SITE_HUNGPRO,
 MAX(ax.IE_SITE_FITUPPRO) as INS_SITE_FITUPPRO,
 MAX(ax.IE_SITE_INSTALLPRO) as INS_SITE_INSTALLPRO,
 MAX(ax.IE_SITE_NDTPRO) as INS_SITE_NDTPRO,

  MAX(ax.IPFB_CoatingFABWPNo) as I_TieCoatWPNo,
  SUM(ax.IPFB_CoatingFABHrs) as I_TieCoatHrs,  
  --SUM(ax.IPFB_CoatingFABEarned) as I_TieCoatEarned,  
  MAX(ax.IPFB_BLASTANDPRIME) as I_BLASTANDPRIME
  --MAX(ax.IPFB_PROJECTPRIMER) as IPFB_PROJECTPRIMER,
  
   
  
    
  --MAX(ax.EB_CoatingInstallWPNo) as EB_CoatingInstallWPNo,
  --SUM(ax.EB_CoatingInstallHrs) as EB_CoatingInstallHrs,
  --SUM(ax.EB_CoatingInstallEarned) as EB_CoatingInstallEarned,
  --MAX(ax.EB_BLASTANDPRIME) as EB_BLASTANDPRIME,
  
  --MAX(ax.EI_CoatingInstallWPNo) as EI_CoatingInstallWPNo,
  --SUM(ax.EI_CoatingInstallHrs) as EI_CoatingInstallHrs,
  --SUM(ax.EI_CoatingInstallEarned) as EI_CoatingInstallEarned,
  --MAX(ax.EI_MIDCOAT) as EI_MIDCOAT,
  --MAX(ax.EI_TOPCOAT) as EI_TOPCOAT,
  --MAX(LASTPROGRESSDATE) as LASTPROGRESSDATE,
  --MAX(LASTUPDATEDBY) as LASTUPDATEDBY


FROM DUMP ax
WHERE ax.WELD_DIA is not null  
GROUP BY      ax.Project,     ax.Name, --ax.DISCIPLINE,
ax.SUPPORTTYPE ,     ax.AREADESC ,     ax.SURFACEAREA ,	
    ax.WEIGHT ,    ax.SUPPORTDRAWING ,     ax.DRAWINGREV ,     ax.ELEVATION ,  
  --ax.ZONE ,   ax.SUPPORTHEIGHT,  
  --ax.SUPPORTGROUP, 
  --ax.SUPPORTLOCATION , 
  ax.TRANSMITTAL, ax.MATERIAL, ax.LINE_NO, ax.WELD_DIA, ax.FIELD_DIA,PAINTSYSTEM
 )
 
 select * from Final