
WITH SCRIPT_WORKSTEP AS
(


SELECT
--          COMPWORKSTEP.OBID AS "COMPWORKSTEPOBID",
--          COMPWORKSTEP.OBJUID AS "COMPWORKSTEPUID",	  
            COMPWORKSTEP.CONFIG AS "PROJECT",
            COMPWORKSTEP_COMP.OBID AS "COMPOBID",
			COMPWORKSTEP_COMP.OBJNAME AS "COMPONENT",
			MDR_COMPSEQNO.STRVALUE AS "COMPONENT SEQNO",
--          COMPWORKSTEP_NAME.STRVALUE AS "WORKSTEP",
--          COMPWORKSTEP_SEQUENCE.STRVALUE as "GATENO",
            COMPWORKSTEP_FIWP.OBID AS "FIWPOBID" ,
			COMPWORKSTEP_FIWP_NAME.STRVALUE AS "WPNO",
        	COMPWORKSTEP_FIWP_DISCIPLINE.OBJNAME AS "DISCIPLINE",
			COMPWORKSTEP_FIWP_PURPOSE.OBJNAME AS "PURPOSE",
--            SUM(CAST(COMPONENTITEM_UNITS.STRVALUE AS FLOAT)) AS "PLAN_UNITS",
--      		  SUM(CAST(WORKSTEP_MANHRS.STRVALUE AS FLOAT)) AS "WORKSTEP_MANHRS",
--         	  SUM(CAST(WORKSTEP_ACTUALHRS.STRVALUE AS FLOAT)) AS "WORKSTEP_ACTUALHRS",
--            SUM(CAST(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE AS FLOAT)) AS "UNIT_COMPLETED",
            COMPWORKSTEP_WORKTYPE_COSTCODE.STRVALUE AS "COSTCODE",
            COMPWORKSTEP_RATEUOM.STRVALUE AS "RATEUOM",
            SUBSTRING(MAX(COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONDATE),1,10) as "PROGRESS_DATE",
            MAX(COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONUSER) as "PROGRESS_BY",
			COMPWORKSTEP_COMP_DELETED_REL.TERMINATIONUSER as "TERMINATED BY",
			COMPWORKSTEP_COMP_DELETED_REL.TERMINATIONDATE as "TERMINATION DATE",
			USERUPDATE_WEB.STRVALUE AS "USERUPDATE_WEB",
			
	MAX(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '1' THEN COMPWORKSTEP_NAME.STRVALUE END) as "ROC 1",
	MAX(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '2' THEN COMPWORKSTEP_NAME.STRVALUE END) as "ROC 2",
	MAX(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '3' THEN COMPWORKSTEP_NAME.STRVALUE END) as "ROC 3",
	MAX(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '4' THEN COMPWORKSTEP_NAME.STRVALUE END) as "ROC 4",
	MAX(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '5' THEN COMPWORKSTEP_NAME.STRVALUE END) as "ROC 5",
	MAX(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '6' THEN COMPWORKSTEP_NAME.STRVALUE END) as "ROC 6",
    
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '1' THEN CAST(ISNULL(WORKSTEP_MANHRS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "WP Hrs ROC 1",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '2' THEN CAST(ISNULL(WORKSTEP_MANHRS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "WP Hrs ROC 2",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '3' THEN CAST(ISNULL(WORKSTEP_MANHRS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "WP Hrs ROC 3",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '4' THEN CAST(ISNULL(WORKSTEP_MANHRS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "WP Hrs ROC 4",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '5' THEN CAST(ISNULL(WORKSTEP_MANHRS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "WP Hrs ROC 5",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '6' THEN CAST(ISNULL(WORKSTEP_MANHRS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "WP Hrs ROC 6",

	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '1' THEN CAST(ISNULL(COMPONENTITEM_UNITS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Planned 1",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '2' THEN CAST(ISNULL(COMPONENTITEM_UNITS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Planned 2",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '3' THEN CAST(ISNULL(COMPONENTITEM_UNITS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Planned 3",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '4' THEN CAST(ISNULL(COMPONENTITEM_UNITS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Planned 4",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '5' THEN CAST(ISNULL(COMPONENTITEM_UNITS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Planned 5",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '6' THEN CAST(ISNULL(COMPONENTITEM_UNITS.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Planned 6",
  
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '1' THEN CAST(ISNULL(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Completed 1",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '2' THEN CAST(ISNULL(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Completed 2",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '3' THEN CAST(ISNULL(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Completed 3",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '4' THEN CAST(ISNULL(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Completed 4",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '5' THEN CAST(ISNULL(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Completed 5",
	sum(CASE COMPWORKSTEP_SEQUENCE.STRVALUE WHEN '6' THEN CAST(ISNULL(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE,0) AS FLOAT) ELSE 0 END) as "Qty Completed 6"


 
  FROM DATAOBJ COMPWORKSTEP 
  LEFT JOIN DATAOBJPR COMPWORKSTEP_NAME ON COMPWORKSTEP_NAME.OBJOBID =  COMPWORKSTEP.OBID AND COMPWORKSTEP_NAME.PROPERTYDEFUID = 'Name' AND COMPWORKSTEP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAREL COMPWORKSTEP_WORKTYPE_REL ON COMPWORKSTEP_WORKTYPE_REL.UID2 =  COMPWORKSTEP.OBJUID AND COMPWORKSTEP_WORKTYPE_REL.DEFUID = 'SPC_ComponentWorkType_ComponentWorkTypeSteps' AND COMPWORKSTEP_WORKTYPE_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	
	LEFT JOIN DATAOBJ COMPWORKSTEP_WORKTYPE ON COMPWORKSTEP_WORKTYPE.OBJUID = COMPWORKSTEP_WORKTYPE_REL.UID1 AND COMPWORKSTEP_WORKTYPE.CONFIG =  COMPWORKSTEP.CONFIG AND COMPWORKSTEP_WORKTYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL COMPWORKSTEP_COMP_REL ON COMPWORKSTEP_COMP_REL.UID2 = COMPWORKSTEP_WORKTYPE.OBJUID AND COMPWORKSTEP_COMP_REL.DEFUID = 'SPC_ComponentItem_ComponentWorkType' AND COMPWORKSTEP_COMP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_COMP ON COMPWORKSTEP_COMP.OBJUID = COMPWORKSTEP_COMP_REL.UID1 AND COMPWORKSTEP_COMP.CONFIG =COMPWORKSTEP.CONFIG AND COMPWORKSTEP_COMP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
--DELETED	
	LEFT JOIN DATAREL COMPWORKSTEP_COMP_DELETED_REL ON COMPWORKSTEP_COMP_DELETED_REL.UID1 = COMPWORKSTEP_COMP.OBJUID AND COMPWORKSTEP_COMP_DELETED_REL.DEFUID = 'SPC_ComponentItem_SharedObject'-- AND COMPWORKSTEP_COMP_DELETED_REL.TERMINATIONUSER IS NOT NULL
--	LEFT JOIN DATAOBJ COMPWORKSTEP_COMP_DELETED ON COMPWORKSTEP_COMP.OBJUID = COMPWORKSTEP_COMP_DELETED_REL.UID1 AND COMPWORKSTEP_COMP.CONFIG =COMPWORKSTEP.CONFIG AND COMPWORKSTEP_COMP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	
	LEFT JOIN DATAOBJPR MDR_COMPSEQNO ON MDR_COMPSEQNO.objobid = COMPWORKSTEP_COMP.OBID AND MDR_COMPSEQNO.propertydefuid = 'SPC_ComponentItem_CompSeqNo'   AND MDR_COMPSEQNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'	
	
	
 	LEFT JOIN DATAOBJPR COMPWORKSTEP_SEQUENCE ON COMPWORKSTEP_SEQUENCE.OBJOBID = COMPWORKSTEP.OBID AND COMPWORKSTEP_SEQUENCE.PROPERTYDEFUID = 'ComponentWorkTypeStep_Sequence' AND COMPWORKSTEP_SEQUENCE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAREL COMPWORKSTEP_FIWP_REL ON COMPWORKSTEP_FIWP_REL.UID2 =  COMPWORKSTEP.OBJUID  AND COMPWORKSTEP_FIWP_REL.DEFUID = 'SPC_Package_ComponentWorkTypeStep' AND COMPWORKSTEP_FIWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	LEFT JOIN DATAOBJ COMPWORKSTEP_FIWP ON COMPWORKSTEP_FIWP.OBJUID = COMPWORKSTEP_FIWP_REL.UID1 AND COMPWORKSTEP_FIWP.CONFIG = COMPWORKSTEP.CONFIG  AND COMPWORKSTEP_FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_FIWP_NAME ON COMPWORKSTEP_FIWP_NAME.OBJOBID = COMPWORKSTEP_FIWP.OBID AND COMPWORKSTEP_FIWP_NAME.PROPERTYDEFUID = 'Name' AND COMPWORKSTEP_FIWP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
	LEFT JOIN DATAOBJPR FIWP_DISCIPLINE_PR ON FIWP_DISCIPLINE_PR.OBJOBID = COMPWORKSTEP_FIWP.OBID AND FIWP_DISCIPLINE_PR.PROPERTYDEFUID = 'FIWP_Discipline' AND FIWP_DISCIPLINE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ COMPWORKSTEP_FIWP_DISCIPLINE ON COMPWORKSTEP_FIWP_DISCIPLINE.OBJUID = FIWP_DISCIPLINE_PR.STRVALUE AND COMPWORKSTEP_FIWP_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	LEFT JOIN DATAOBJPR FIWP_PURPOSE_PR ON FIWP_PURPOSE_PR.OBJOBID = COMPWORKSTEP_FIWP.OBID AND FIWP_PURPOSE_PR.PROPERTYDEFUID = 'FIWP_Purpose' AND FIWP_PURPOSE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ COMPWORKSTEP_FIWP_PURPOSE ON COMPWORKSTEP_FIWP_PURPOSE.OBJUID = FIWP_PURPOSE_PR.STRVALUE AND COMPWORKSTEP_FIWP_PURPOSE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  LEFT JOIN DATAOBJPR COMPONENTITEM_UNITS ON COMPONENTITEM_UNITS.OBJOBID = COMPWORKSTEP_COMP.OBID AND COMPONENTITEM_UNITS.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_UNITS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
 	LEFT JOIN DATAOBJPR COMPWORKSTEP_QUANTITYCOMPLETE ON COMPWORKSTEP_QUANTITYCOMPLETE.OBJOBID = COMPWORKSTEP.OBID AND COMPWORKSTEP_QUANTITYCOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_QuantityComplete' AND COMPWORKSTEP_QUANTITYCOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	LEFT JOIN DATAOBJPR COMPWORKSTEP_WORKTYPE_COSTCODE ON COMPWORKSTEP_WORKTYPE_COSTCODE.OBJOBID = COMPWORKSTEP_WORKTYPE.OBID AND COMPWORKSTEP_WORKTYPE_COSTCODE.PROPERTYDEFUID = 'ComponentWorkType_CostCode' AND COMPWORKSTEP_WORKTYPE_COSTCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPWORKSTEP_RATEUOM ON COMPWORKSTEP_RATEUOM.OBJOBID = COMPWORKSTEP.OBID AND COMPWORKSTEP_RATEUOM.PROPERTYDEFUID = 'ComponentWorkTypeStep_RateUoM' AND COMPWORKSTEP_RATEUOM.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR WORKSTEP_MANHRS on WORKSTEP_MANHRS.objobid=COMPWORKSTEP.OBID AND WORKSTEP_MANHRS.PROPERTYDEFUID='ComponentWorkTypeStep_ManHours' AND WORKSTEP_MANHRS.terminationdate='9999/12/31-23:59:59:999'  
  LEFT JOIN DATAOBJPR WORKSTEP_QTY_COMPLETE on WORKSTEP_QTY_COMPLETE.objobid=COMPWORKSTEP.OBID AND WORKSTEP_QTY_COMPLETE.PROPERTYDEFUID='ComponentWorkTypeStep_QuantityComplete' AND WORKSTEP_QTY_COMPLETE.terminationdate='9999/12/31-23:59:59:999' 
  LEFT JOIN DATAOBJPR WORKSTEP_ACTUALHRS on WORKSTEP_ACTUALHRS.objobid=COMPWORKSTEP.OBID AND WORKSTEP_ACTUALHRS.PROPERTYDEFUID='ComponentWorkTypeStep_ActualHours' AND WORKSTEP_ACTUALHRS.terminationdate='9999/12/31-23:59:59:999' 
  
  LEFT JOIN DATAOBJPR WORKSTEP_QTY_PLANNED on WORKSTEP_QTY_PLANNED.objobid=COMPWORKSTEP.OBID AND WORKSTEP_QTY_PLANNED.PROPERTYDEFUID='ComponentWorkType_QuantityPlanned' AND WORKSTEP_QTY_PLANNED.terminationdate='9999/12/31-23:59:59:999' 
 
  LEFT JOIN DATAOBJPR USERUPDATE_WEB on USERUPDATE_WEB.objobid=COMPWORKSTEP.OBID AND USERUPDATE_WEB.PROPERTYDEFUID='ComponentWorkTypeStep_Notes' AND USERUPDATE_WEB.terminationdate='9999/12/31-23:59:59:999'  
   
  WHERE COMPWORKSTEP_FIWP.OBID is not null and COMPWORKSTEP.OBJDEFUID = 'SPC_ComponentWorkTypeStep' AND COMPWORKSTEP.TERMINATIONDATE = '9999/12/31-23:59:59:999' --AND COMPWORKSTEP_FIWP_DISCIPLINE.OBJNAME IN ('Structural','General','Piping','Electrical','Instrumentation','Mechanical','Coating')
  
  
  GROUP BY 
COMPWORKSTEP.CONFIG,
COMPWORKSTEP_COMP.OBID,
COMPWORKSTEP_COMP.OBJNAME,
COMPWORKSTEP_FIWP.OBID,
COMPWORKSTEP_FIWP_NAME.STRVALUE,
COMPWORKSTEP_FIWP_DISCIPLINE.OBJNAME,
COMPWORKSTEP_FIWP_PURPOSE.OBJNAME,
COMPWORKSTEP_WORKTYPE_COSTCODE.STRVALUE,
COMPWORKSTEP_RATEUOM.STRVALUE,
MDR_COMPSEQNO.STRVALUE,
COMPWORKSTEP_COMP_DELETED_REL.TERMINATIONUSER,
COMPWORKSTEP_COMP_DELETED_REL.TERMINATIONDATE,
USERUPDATE_WEB.STRVALUE

)

SELECT

"FIWPOBID",
"WPNO",
"PURPOSE",
"PROJECT",
COSTCODE AS "ACTIVITY CODE",
"DISCIPLINE",
"RATEUOM",
"ROC 1",
"ROC 2",
"ROC 3",
"ROC 4",
"ROC 5",
"ROC 6",
"WP Hrs ROC 1",
"WP Hrs ROC 2",
"WP Hrs ROC 3",
"WP Hrs ROC 4",
"WP Hrs ROC 5",
"WP Hrs ROC 6",

"Qty Planned 1",
"Qty Planned 2",
"Qty Planned 3",
"Qty Planned 4",
"Qty Planned 5",
"Qty Planned 6",
"Qty Completed 1",
"Qty Completed 2",
"Qty Completed 3",
"Qty Completed 4",
"Qty Completed 5",
"Qty Completed 6",

CASE WHEN "Qty Planned 1"=0 THEN 0 ELSE ROUND(("Qty Completed 1" / "Qty Planned 1")* "WP Hrs ROC 1", 4) END  as "WP Hrs Earned ROC 1",
CASE WHEN "Qty Planned 2"=0 THEN 0 ELSE ROUND(("Qty Completed 2" / "Qty Planned 2")* "WP Hrs ROC 2", 4) END  as "WP Hrs Earned ROC 2",
CASE WHEN "Qty Planned 3"=0 THEN 0 ELSE ROUND(("Qty Completed 3" / "Qty Planned 3")* "WP Hrs ROC 3", 4) END  as "WP Hrs Earned ROC 3",
CASE WHEN "Qty Planned 4"=0 THEN 0 ELSE ROUND(("Qty Completed 4" / "Qty Planned 4")* "WP Hrs ROC 4", 4) END  as "WP Hrs Earned ROC 4",
CASE WHEN "Qty Planned 5"=0 THEN 0 ELSE ROUND(("Qty Completed 5" / "Qty Planned 5")* "WP Hrs ROC 5", 4) END  as "WP Hrs Earned ROC 5",
CASE WHEN "Qty Planned 6"=0 THEN 0 ELSE ROUND(("Qty Completed 6" / "Qty Planned 6")* "WP Hrs ROC 6", 4) END  as "WP Hrs Earned ROC 6",

CASE WHEN "Qty Planned 1"=0 THEN 0 ELSE ROUND(("Qty Completed 1" / "Qty Planned 1"), 4) END  as "Progress ROC 1",
CASE WHEN "Qty Planned 2"=0 THEN 0 ELSE ROUND(("Qty Completed 2" / "Qty Planned 2"), 4) END  as "Progress ROC 2",
CASE WHEN "Qty Planned 3"=0 THEN 0 ELSE ROUND(("Qty Completed 3" / "Qty Planned 3"), 4) END  as "Progress ROC 3",
CASE WHEN "Qty Planned 4"=0 THEN 0 ELSE ROUND(("Qty Completed 4" / "Qty Planned 4"), 4) END  as "Progress ROC 4",
CASE WHEN "Qty Planned 5"=0 THEN 0 ELSE ROUND(("Qty Completed 5" / "Qty Planned 5"), 4) END  as "Progress ROC 5",
CASE WHEN "Qty Planned 6"=0 THEN 0 ELSE ROUND(("Qty Completed 6" / "Qty Planned 6"), 4) END  as "Progress ROC 6",

----Component Properties
COMPONENT,
COMPOBID,
"COMPONENT SEQNO",
"TERMINATED BY",
"TERMINATION DATE",
"USERUPDATE_WEB",
"PROGRESS_DATE",
"PROGRESS_BY"


 
 from SCRIPT_WORKSTEP
 
 
 OPTION (MAXDOP 4, HASH JOIN);