
-- 1 
SELECT 
            CWP.OBID AS "CWPOBID",
            CWP.OBJUID AS "CWPUID",
            CWP.CONFIG AS "PROJECT" 
-- sample: ,CWP.Property1 AS "Prop1"

INTO #D7650SPCRPT_CWP_IOBJECT_PROP_TMP

FROM DATAOBJ CWP With(Nolock) WHERE CWP.OBJDEFUID = 'SPC_CWP' AND CWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'

-- 2
SELECT 
            CWP.CWPOBID AS "CWPOBID",
            CWP_NAME.STRVALUE AS "NAME", 
            CWP_DESCRIPTION.STRVALUE AS "DESCRIPTION",	 
            CWP_EWPNUMBER.STRVALUE AS "EWPNUMBER",
            CAST(CWP_BUDGETEDLABORHOURS.STRVALUE AS FLOAT) AS "BUDGETEDLABORHOURS",
            CONVERT(datetime,CWP_PLANNEDSTARTDATE.STRVALUE) AS "PLANNEDSTARTDATE",
            CONVERT(datetime,CWP_PLANNEDFINISHDATE.STRVALUE) AS "PLANNEDFINISHDATE",
            CONVERT(datetime,CWP_ACTUALSTARTDATE.STRVALUE) AS "ACTUALSTARTDATE",
            CONVERT(datetime,CWP_ACTUALFINISHDATE.STRVALUE) AS "ACTUALFINISHDATE",
            CONVERT(datetime,CWP_EARLYSTARTDATE.STRVALUE) AS "EARLYSTARTDATE",
            CONVERT(datetime,CWP_EARLYFINISHDATE.STRVALUE) AS "EARLYFINISHDATE",
            CONVERT(datetime,CWP_LATESTARTDATE.STRVALUE) AS "LATESTARTDATE",
            CONVERT(datetime,CWP_LATEFINISHDATE.STRVALUE) AS "LATEFINISHDATE",
            CWP_WBSPATH.STRVALUE AS "WBSPATH"
-- sample: ,Property2.STRVALUE AS "Prop2"

INTO #D7650SPCRPT_CWP_DIRECT_PROP_TMP

FROM #D7650SPCRPT_CWP_IOBJECT_PROP_TMP CWP With(Nolock)

--Section #D76502c: Join SPF tables to get Direct Properties 

--#D7650region " Direct Properties "

	--NAME
	LEFT JOIN DATAOBJPR CWP_NAME ON CWP_NAME.OBJOBID = CWP.CWPOBID AND CWP_NAME.PROPERTYDEFUID = 'Name' AND CWP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--DESCRIPTION
	LEFT JOIN DATAOBJPR CWP_DESCRIPTION ON CWP_DESCRIPTION.OBJOBID = CWP.CWPOBID AND CWP_DESCRIPTION.PROPERTYDEFUID = 'Description' AND CWP_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--EWPNUMBER
	LEFT JOIN DATAOBJPR CWP_EWPNUMBER ON CWP_EWPNUMBER.OBJOBID = CWP.CWPOBID AND CWP_EWPNUMBER.PROPERTYDEFUID = 'CWP_EWP_Number' AND CWP_EWPNUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--BUDGETEDLABORHOURS
	LEFT JOIN DATAOBJPR CWP_BUDGETEDLABORHOURS ON CWP_BUDGETEDLABORHOURS.OBJOBID = CWP.CWPOBID AND CWP_BUDGETEDLABORHOURS.PROPERTYDEFUID = 'CWP_BudgetedLaborHours' AND CWP_BUDGETEDLABORHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--PLANNEDSTARTDATE
	LEFT JOIN DATAOBJPR CWP_PLANNEDSTARTDATE ON CWP_PLANNEDSTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_PLANNEDSTARTDATE.PROPERTYDEFUID = 'CWP_PlannedStartDate' AND CWP_PLANNEDSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--PLANNEDFINISHDATE
	LEFT JOIN DATAOBJPR CWP_PLANNEDFINISHDATE ON CWP_PLANNEDFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_PLANNEDFINISHDATE.PROPERTYDEFUID = 'CWP_PlannedFinishDate' AND CWP_PLANNEDFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--ACTUALSTARTDATE
	LEFT JOIN DATAOBJPR CWP_ACTUALSTARTDATE ON CWP_ACTUALSTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_ACTUALSTARTDATE.PROPERTYDEFUID = 'CWP_ActualStartDate' AND CWP_ACTUALSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--ACTUALFINISHDATE
	LEFT JOIN DATAOBJPR CWP_ACTUALFINISHDATE ON CWP_ACTUALFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_ACTUALFINISHDATE.PROPERTYDEFUID = 'CWP_ActualFinishDate' AND CWP_ACTUALFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--EARLYSTARTDATE
	LEFT JOIN DATAOBJPR CWP_EARLYSTARTDATE ON CWP_EARLYSTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_EARLYSTARTDATE.PROPERTYDEFUID = 'CWP_EarlyStartDate' AND CWP_EARLYSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--EARLYFINISHDATE
	LEFT JOIN DATAOBJPR CWP_EARLYFINISHDATE ON CWP_EARLYFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_EARLYFINISHDATE.PROPERTYDEFUID = 'CWP_EarlyFinishDate' AND CWP_EARLYFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
		
	--LATESTARTDATE
	LEFT JOIN DATAOBJPR CWP_LATESTARTDATE ON CWP_LATESTARTDATE.OBJOBID = CWP.CWPOBID AND CWP_LATESTARTDATE.PROPERTYDEFUID = 'CWP_LateStartDate' AND CWP_LATESTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--LATEFINISHDATE
	LEFT JOIN DATAOBJPR CWP_LATEFINISHDATE ON CWP_LATEFINISHDATE.OBJOBID = CWP.CWPOBID AND CWP_LATEFINISHDATE.PROPERTYDEFUID = 'CWP_LateFinishDate' AND CWP_LATEFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--WBSPATH
	LEFT JOIN DATAOBJPR CWP_WBSPATH ON CWP_WBSPATH.OBJOBID = CWP.CWPOBID AND CWP_WBSPATH.PROPERTYDEFUID = 'CWP_WBSPath' AND CWP_WBSPATH.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  ---- sample:
	--LEFT JOIN DATAOBJPR Property2 ON Property2.OBJOBID = FIWP.FIWPOBID AND Property2.PROPERTYDEFUID = '<PROPERTYDEFUID>' AND Property2.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	  
--#D7650endregion " Direct Properties "

-- 3

SELECT 
            CWP.CWPOBID AS "CWPOBID",
            CWP_DISCIPLINE.OBJNAME AS "DISCIPLINE"
            
-- sample: ,Property3.OBJNAME AS Prop3

INTO #D7650SPCRPT_CWP_DIR_ENUM_PROP_TMP
      
FROM #D7650SPCRPT_CWP_IOBJECT_PROP_TMP CWP With(Nolock)

-- Section #D76503c: Join SPF tables to Direct Properties (Enum Type)

--#D7650region " Direct Properties with Enum Type "
	
	--CWP Discipline
	LEFT JOIN DATAOBJPR CWP_DISCIPLINE_PR ON CWP_DISCIPLINE_PR.OBJOBID = CWP.CWPOBID AND CWP_DISCIPLINE_PR.PROPERTYDEFUID = 'CWP_Discipline' AND CWP_DISCIPLINE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ CWP_DISCIPLINE ON CWP_DISCIPLINE.OBJUID = CWP_DISCIPLINE_PR.STRVALUE AND CWP_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  ---- sample:																																			 
	-- LEFT JOIN DATAOBJPR Property3_PR ON Property3_PR.OBJOBID = CWP.CWPOBID AND Property3_PR.PROPERTYDEFUID = '<PROPERTYDEFUID>' AND Property3_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	-- LEFT JOIN SCHEMAOBJ Property3 ON Property3.OBJUID = Prop3_PR.STRVALUE AND Property3.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
--#D7650endregion " Direct Properties Enum Type "

-- 4
SELECT
            CWP.CWPOBID AS "CWPOBID",
            CWP_DESIGNAREA.STRVALUE AS "DESIGNAREA",
            CWP_CWA.OBID AS "CWAOBID"
-- sample: ,Property4.STRVALUE AS "Prop4"

INTO #D7650SPCRPT_CWP_REL_PROP_TMP

FROM #D7650SPCRPT_CWP_IOBJECT_PROP_TMP CWP With(Nolock)

-- Section #D76504c: Join SPF tables to get Properties from related objects	

--#D7650region " Relationship other end properties "

	--Design Area
	LEFT JOIN DATAREL CWP_DESIGNAREA_REL ON CWP_DESIGNAREA_REL.UID2 = CWP.CWPUID AND CWP_DESIGNAREA_REL.DEFUID = 'SPC_FunctionalArea_CWP' AND CWP_DESIGNAREA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ CWP_DESIGNAREA_OBJ ON CWP_DESIGNAREA_OBJ.OBJUID = CWP_DESIGNAREA_REL.UID1 AND CWP_DESIGNAREA_OBJ.CONFIG = CWP.PROJECT AND CWP_DESIGNAREA_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR CWP_DESIGNAREA ON CWP_DESIGNAREA.OBJOBID = CWP_DESIGNAREA_OBJ.OBID AND CWP_DESIGNAREA.PROPERTYDEFUID = 'Name' AND CWP_DESIGNAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--CWAs
	LEFT JOIN DATAREL CWP_CWA_REL ON CWP_CWA_REL.UID2 = CWP.CWPUID  AND CWP_CWA_REL.DEFUID = 'SPC_CWA_CWPs' AND CWP_CWA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ CWP_CWA ON CWP_CWA.OBJUID = CWP_CWA_REL.UID1 AND CWP_CWA.CONFIG = CWP.PROJECT AND CWP_CWA.TERMINATIONDATE = '9999/12/31-23:59:59:999'

  ---- sample:
	-- LEFT JOIN DATAREL Property4_REL ON Property4_REL.UID1 = CWP.CWPUID AND Property4_REL.DEFUID = '<RELDEFUID>' AND Property4_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	-- LEFT JOIN DATAOBJ Property4_OBJ ON Property4_OBJ.OBJUID = Property4_REL.UID2 AND Property4_OBJ.CONFIG = CWP.PROJECT AND Property4_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	-- LEFT JOIN DATAOBJPR Property4 ON Property4.OBJOBID = Property4_OBJ.OBID AND Property4.PROPERTYDEFUID = '<PROPERTYDEFUID>' AND Property4.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
--#D7650endregion " Relationship other end properties "

-- 5
SELECT
    -- Section #D76506a: IObject properties
	  t1.CWPOBID, CWPUID, PROJECT, -- sample: Prop1Column,
    -- Section #D76506b: Direct properties 
        
    NAME, DESCRIPTION, EWPNUMBER, BUDGETEDLABORHOURS, 
    PLANNEDSTARTDATE, 
    PLANNEDFINISHDATE, 
    ACTUALSTARTDATE, 
    ACTUALFINISHDATE, 
    EARLYSTARTDATE,	
    EARLYFINISHDATE, 
    LATESTARTDATE, 
    LATEFINISHDATE,	
    
    WBSPATH, -- sample: Prop2Column,
	  -- Section #D76506c: Direct properties (Enum type)			 
    DISCIPLINE, -- sample: Prop3Column,
    -- Section #D76506d: Properties from related objects	 
    DESIGNAREA, CWAOBID -- sample: ,Prop4Column	  
	
INTO #D7650SPCCWP

FROM #D7650SPCRPT_CWP_IOBJECT_PROP_TMP t1 With(Nolock)
LEFT JOIN #D7650SPCRPT_CWP_DIRECT_PROP_TMP t2 ON t2.CWPOBID = t1.CWPOBID
LEFT JOIN #D7650SPCRPT_CWP_DIR_ENUM_PROP_TMP t3 ON t3.CWPOBID = t1.CWPOBID
LEFT JOIN #D7650SPCRPT_CWP_REL_PROP_TMP t4 ON t4.CWPOBID = t1.CWPOBID

-- 6
SELECT
            COMPWORKSTEP.OBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP.OBJUID AS "COMPWORKSTEPUID",	  
            COMPWORKSTEP.CONFIG AS "PROJECT"

INTO #D7650SPCRPT_WORKSTEP_IOBJ_PROP_TMP

FROM DATAOBJ COMPWORKSTEP With(Nolock) WHERE COMPWORKSTEP.OBJDEFUID = 'SPC_ComponentWorkTypeStep' AND COMPWORKSTEP.TERMINATIONDATE = '9999/12/31-23:59:59:999'

-- 7
SELECT
            COMPWORKSTEP.COMPWORKSTEPOBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP_NAME.STRVALUE AS "NAME", 
            COMPWORKSTEP_DESCRIPTION.STRVALUE AS "DESCRIPTION",
            CAST(COMPWORKSTEP_SEQUENCE.STRVALUE AS INT) AS "SEQUENCE",
            CAST(COMPWORKSTEP_UNITRATE.STRVALUE AS FLOAT) AS "UNITRATE",
            COMPWORKSTEP_RATEUOM.STRVALUE AS "RATEUOM",
            COMPWORKSTEP_NOTES.STRVALUE AS "NOTES",
            CAST(COMPWORKSTEP_PLANNEDMANHOURS.STRVALUE AS FLOAT) AS "PLANNEDMANHOURS",
            CAST(COMPWORKSTEP_ACTUALMANHOURS.STRVALUE AS FLOAT) AS "ACTUALMANHOURS",
            COMPWORKSTEP_DATECOMPLETE.STRVALUE AS "ACTUALDATECOMPLETE",
            CAST(COMPWORKSTEP_QUANTITYCOMPLETE.STRVALUE AS FLOAT) AS "QUANTITYCOMPLETE",
            COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONDATE,
            COMPWORKSTEP_QUANTITYCOMPLETE.CREATIONUSER 

INTO #D7650SPCRPT_WORKSTEP_DIR_PROP_TMP
            
FROM #D7650SPCRPT_WORKSTEP_IOBJ_PROP_TMP COMPWORKSTEP With(Nolock)
	LEFT JOIN DATAOBJPR COMPWORKSTEP_NAME ON COMPWORKSTEP_NAME.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_NAME.PROPERTYDEFUID = 'Name' AND COMPWORKSTEP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_DESCRIPTION ON COMPWORKSTEP_DESCRIPTION.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_DESCRIPTION.PROPERTYDEFUID = 'Description' AND COMPWORKSTEP_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_SEQUENCE ON COMPWORKSTEP_SEQUENCE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_SEQUENCE.PROPERTYDEFUID = 'ComponentWorkTypeStep_Sequence' AND COMPWORKSTEP_SEQUENCE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_UNITRATE ON COMPWORKSTEP_UNITRATE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_UNITRATE.PROPERTYDEFUID = 'ComponentWorkTypeStep_UnitRate' AND COMPWORKSTEP_UNITRATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_RATEUOM ON COMPWORKSTEP_RATEUOM.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_RATEUOM.PROPERTYDEFUID = 'ComponentWorkTypeStep_RateUoM' AND COMPWORKSTEP_RATEUOM.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_NOTES ON COMPWORKSTEP_NOTES.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_NOTES.PROPERTYDEFUID = 'ComponentWorkTypeStep_Notes' AND COMPWORKSTEP_NOTES.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_PLANNEDMANHOURS ON COMPWORKSTEP_PLANNEDMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_PLANNEDMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ManHours' AND COMPWORKSTEP_PLANNEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_ACTUALMANHOURS ON COMPWORKSTEP_ACTUALMANHOURS.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_ACTUALMANHOURS.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualHours' AND COMPWORKSTEP_ACTUALMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_DATECOMPLETE ON COMPWORKSTEP_DATECOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_DATECOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_ActualDateComplete' AND COMPWORKSTEP_DATECOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  LEFT JOIN DATAOBJPR COMPWORKSTEP_QUANTITYCOMPLETE ON COMPWORKSTEP_QUANTITYCOMPLETE.OBJOBID = COMPWORKSTEP.COMPWORKSTEPOBID AND COMPWORKSTEP_QUANTITYCOMPLETE.PROPERTYDEFUID = 'ComponentWorkTypeStep_QuantityComplete' AND COMPWORKSTEP_QUANTITYCOMPLETE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

OPTION (MAXDOP 4, HASH JOIN);

-- 8
SELECT
            COMPWORKSTEP.COMPWORKSTEPOBID AS "COMPWORKSTEPOBID",
            COMPWORKSTEP_WORKTYPE_COSTCODE.STRVALUE AS "COSTCODE",
            COMPWORKSTEP_FIWP.OBID AS "FIWPOBID",	  
            COMPWORKSTEP_WORKTYPE.OBID AS "WORKTYPEOBID",
            COMPWORKSTEP_COMP.OBID AS "COMPOBID",
            CAST(COMPONENTITEM_QUANTITYPLANNED.STRVALUE AS FLOAT) AS "QUANTITYPLANNED",
            
            CAST(COMPONENTITEM_UNITS.STRVALUE AS FLOAT) AS "UNITS"

INTO #D7650SPCRPT_WORKSTEP_REL_PROP_TMP

FROM #D7650SPCRPT_WORKSTEP_IOBJ_PROP_TMP COMPWORKSTEP With(Nolock)
	LEFT JOIN DATAREL COMPWORKSTEP_FIWP_REL ON COMPWORKSTEP_FIWP_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID  AND COMPWORKSTEP_FIWP_REL.DEFUID = 'SPC_Package_ComponentWorkTypeStep' AND COMPWORKSTEP_FIWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_FIWP ON COMPWORKSTEP_FIWP.OBJUID = COMPWORKSTEP_FIWP_REL.UID1 AND COMPWORKSTEP_FIWP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL COMPWORKSTEP_WORKTYPE_REL ON COMPWORKSTEP_WORKTYPE_REL.UID2 = COMPWORKSTEP.COMPWORKSTEPUID AND COMPWORKSTEP_WORKTYPE_REL.DEFUID = 'SPC_ComponentWorkType_ComponentWorkTypeSteps' AND COMPWORKSTEP_WORKTYPE_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_WORKTYPE ON COMPWORKSTEP_WORKTYPE.OBJUID = COMPWORKSTEP_WORKTYPE_REL.UID1 AND COMPWORKSTEP_WORKTYPE.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_WORKTYPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPWORKSTEP_WORKTYPE_COSTCODE ON COMPWORKSTEP_WORKTYPE_COSTCODE.OBJOBID = COMPWORKSTEP_WORKTYPE.OBID AND COMPWORKSTEP_WORKTYPE_COSTCODE.PROPERTYDEFUID = 'ComponentWorkType_CostCode' AND COMPWORKSTEP_WORKTYPE_COSTCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL COMPWORKSTEP_COMP_REL ON COMPWORKSTEP_COMP_REL.UID2 = COMPWORKSTEP_WORKTYPE.OBJUID AND COMPWORKSTEP_COMP_REL.DEFUID = 'SPC_ComponentItem_ComponentWorkType' AND COMPWORKSTEP_COMP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ COMPWORKSTEP_COMP ON COMPWORKSTEP_COMP.OBJUID = COMPWORKSTEP_COMP_REL.UID1 AND COMPWORKSTEP_COMP.CONFIG = COMPWORKSTEP.PROJECT AND COMPWORKSTEP_COMP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_QUANTITYPLANNED ON COMPONENTITEM_QUANTITYPLANNED.OBJOBID = COMPWORKSTEP_COMP.OBID AND COMPONENTITEM_QUANTITYPLANNED.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_QUANTITYPLANNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR COMPONENTITEM_UNITS ON COMPONENTITEM_UNITS.OBJOBID = COMPWORKSTEP_COMP.OBID AND COMPONENTITEM_UNITS.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_UNITS.TERMINATIONDATE = '9999/12/31-23:59:59:999'

-- 9
SELECT

	    t1.COMPWORKSTEPOBID, COMPWORKSTEPUID, PROJECT, 
      NAME, DESCRIPTION, SEQUENCE, UNITRATE, RATEUOM, NOTES, PLANNEDMANHOURS,  CASE WHEN ISNULL(t3.UNITS,0)=0 then 0 else CASE WHEN ISNULL(QUANTITYCOMPLETE,0)/ ISNULL(t3.UNITS,0)>1 THEN 1 ELSE ISNULL(QUANTITYCOMPLETE,0)/ ISNULL(t3.UNITS,0) END * ISNULL(PLANNEDMANHOURS,0) end as ACTUALMANHOURS, 
      ACTUALDATECOMPLETE,  ISNULL(QUANTITYCOMPLETE,0) as UNIT_COMPLETED,
      CASE WHEN ISNULL(t3.UNITS,0)>0 THEN 
      CASE WHEN ISNULL(QUANTITYCOMPLETE,0)/ ISNULL(t3.UNITS,0) * ISNULL(PLANNEDMANHOURS,0)>=PLANNEDMANHOURS THEN 1 ELSE 0 END      
      END AS QUANTITYCOMPLETE, COSTCODE, FIWPOBID, WORKTYPEOBID, COMPOBID, QUANTITYPLANNED, CREATIONUSER, CREATIONDATE, t3.UNITS , QUANTITYPLANNED as PLAN_UNITS

INTO #D7650WorkStepsX
      
FROM #D7650SPCRPT_WORKSTEP_IOBJ_PROP_TMP t1 With(Nolock)
LEFT JOIN #D7650SPCRPT_WORKSTEP_DIR_PROP_TMP t2 ON t2.COMPWORKSTEPOBID = t1.COMPWORKSTEPOBID
LEFT JOIN #D7650SPCRPT_WORKSTEP_REL_PROP_TMP t3 ON t3.COMPWORKSTEPOBID = t1.COMPWORKSTEPOBID

-- 9.1
SELECT COMPWORKSTEPOBID, COMPWORKSTEPUID, PROJECT, NAME, DESCRIPTION, SEQUENCE, UNITRATE, RATEUOM, NOTES, PLANNEDMANHOURS, ACTUALMANHOURS, ACTUALDATECOMPLETE, 
  QUANTITYCOMPLETE, COSTCODE, FIWPOBID, WORKTYPEOBID, COMPOBID, CREATIONUSER, CREATIONDATE, UNITS , COUNT(DISTINCT COMPOBID) AS QUANTITYPLANNED, sum(PLAN_UNITS) as PLAN_UNITS, SUM( DISTINCT UNIT_COMPLETED) as UNIT_COMPLETED,
  CASE WHEN PLANNEDMANHOURS=0 then 0 else CASE WHEN (ACTUALMANHOURS / PLANNEDMANHOURS)>=1 THEN 1 ELSE 0 END END as Gate_QTYComplete

  INTO #D7650WorkSteps

  FROM #D7650WorkStepsX With(Nolock)
  GROUP by COMPWORKSTEPOBID, COMPWORKSTEPUID, PROJECT, NAME, DESCRIPTION, SEQUENCE, UNITRATE, RATEUOM, NOTES, PLANNEDMANHOURS, ACTUALMANHOURS, ACTUALDATECOMPLETE, 
  QUANTITYCOMPLETE, COSTCODE, FIWPOBID, WORKTYPEOBID, COMPOBID, CREATIONUSER, CREATIONDATE, UNITS


-- 10
SELECT 
            COMPONENTITEM.OBID AS "COMPOBID",
            COMPONENTITEM.OBJUID AS "COMPUID",
            COMPONENTITEM.CONFIG AS "PROJECT"
			
INTO #D7650SPCRPT_COMP_IOBJECT_PROP_TMP

FROM DATAOBJ COMPONENTITEM With(Nolock) WHERE COMPONENTITEM.OBJDEFUID IN ('SPC_ComponentItem', 'SPC_AdhocComponentItem',  'SPC_NonPublishedComponentItem', 'SPC_Spool', 'SPC_Assembly') AND COMPONENTITEM.TERMINATIONDATE = '9999/12/31-23:59:59:999'

-- 11
SELECT 
            COMPONENTITEM.COMPOBID AS "COMPOBID",
            COMPONENTITEM_NAME.STRVALUE AS "NAME", 
            COMPONENTITEM_DESCRIPTION.STRVALUE AS "DESCRIPTION",	  
            COMPONENTITEM_MATERIAL.STRVALUE AS "MATERIAL",	  
            COMPONENTITEM_RATING.STRVALUE AS "RATING",	  
            COMPONENTITEM_CLASS.STRVALUE AS "CLASS",	  
            CAST(COMPONENTITEM_SIZE.STRVALUE AS FLOAT) AS "COMPSIZE",	  
            COMPONENTITEM_THICKNESS.STRVALUE AS "THICKNESS",	  
            CAST(COMPONENTITEM_UNITS.STRVALUE AS FLOAT) AS "UNITS",
            COMPONENTITEM_COMMODITYCODE.STRVALUE AS "COMMODITYCODE",
            COMPONENTITEM_DRAWINGTITLE.STRVALUE AS "DRAWINGTITLE",
            COMPONENTITEM_DRAWINGREVISION.STRVALUE AS "DRAWINGREVISION",
            COMPONENTITEM_REVISIONDATE.STRVALUE AS "REVISIONDATE",
            COMPONENTITEM_TRANSMITTALNO.STRVALUE AS "TRANSMITTALNO",
            COMPONENTITEM_COMPONENTSTATUS.STRVALUE AS "COMPONENTSTATUS"

INTO #D7650SPCRPT_COMP_DIRECT_PROP_TMP

FROM #D7650SPCRPT_COMP_IOBJECT_PROP_TMP COMPONENTITEM With(Nolock)

	LEFT JOIN DATAOBJPR COMPONENTITEM_NAME ON COMPONENTITEM_NAME.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_NAME.PROPERTYDEFUID = 'Name' AND COMPONENTITEM_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_DESCRIPTION ON COMPONENTITEM_DESCRIPTION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DESCRIPTION.PROPERTYDEFUID = 'SPC_ComponentItem_ShortDescription' AND COMPONENTITEM_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
    LEFT JOIN DATAOBJPR COMPONENTITEM_MATERIAL ON COMPONENTITEM_MATERIAL.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_MATERIAL.PROPERTYDEFUID = 'SPC_ComponentItem_Material' AND COMPONENTITEM_MATERIAL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_RATING ON COMPONENTITEM_RATING.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_RATING.PROPERTYDEFUID = 'SPC_ComponentItem_Rating' AND COMPONENTITEM_RATING.TERMINATIONDATE = '9999/12/31-23:59:59:999'
    LEFT JOIN DATAOBJPR COMPONENTITEM_CLASS ON COMPONENTITEM_CLASS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_CLASS.PROPERTYDEFUID = 'SpcNonPublishedClassDesignation' AND COMPONENTITEM_CLASS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_SIZE ON COMPONENTITEM_SIZE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_SIZE.PROPERTYDEFUID = 'SPC_ComponentItem_Size' AND COMPONENTITEM_SIZE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_THICKNESS ON COMPONENTITEM_THICKNESS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_THICKNESS.PROPERTYDEFUID = 'SPC_ComponentItem_Thickness' AND COMPONENTITEM_THICKNESS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_UNITS ON COMPONENTITEM_UNITS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_UNITS.PROPERTYDEFUID = 'SPC_ComponentItem_Units' AND COMPONENTITEM_UNITS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_COMMODITYCODE ON COMPONENTITEM_COMMODITYCODE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_COMMODITYCODE.PROPERTYDEFUID = 'SPC_ComponentItem_CommodityCode' AND COMPONENTITEM_COMMODITYCODE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_DRAWINGTITLE ON COMPONENTITEM_DRAWINGTITLE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DRAWINGTITLE.PROPERTYDEFUID = 'MDR_IDOCS_DrawingTitle' AND COMPONENTITEM_DRAWINGTITLE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_DRAWINGREVISION ON COMPONENTITEM_DRAWINGREVISION.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_DRAWINGREVISION.PROPERTYDEFUID = 'MDR_IDOCS_DrawingRevision' AND COMPONENTITEM_DRAWINGREVISION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_REVISIONDATE ON COMPONENTITEM_REVISIONDATE.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_REVISIONDATE.PROPERTYDEFUID = 'MDR_IDOCS_RevisionDate' AND COMPONENTITEM_REVISIONDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_TRANSMITTALNO ON COMPONENTITEM_TRANSMITTALNO.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_TRANSMITTALNO.PROPERTYDEFUID = 'MDR_IDOCS_TransmittalNo' AND COMPONENTITEM_TRANSMITTALNO.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR COMPONENTITEM_COMPONENTSTATUS ON COMPONENTITEM_COMPONENTSTATUS.OBJOBID = COMPONENTITEM.COMPOBID AND COMPONENTITEM_COMPONENTSTATUS.PROPERTYDEFUID = 'MDR_ComponentStatus' AND COMPONENTITEM_COMPONENTSTATUS.TERMINATIONDATE = '9999/12/31-23:59:59:999'

 -- 12
SELECT
      
	    t1.COMPOBID, COMPUID, PROJECT,     
	    NAME, DESCRIPTION, MATERIAL, RATING, CLASS, COMPSIZE, THICKNESS, UNITS, COMMODITYCODE,DRAWINGTITLE,DRAWINGREVISION,REVISIONDATE,TRANSMITTALNO,COMPONENTSTATUS

INTO #D7650SPCRPT_COMPONENTITEM1

FROM #D7650SPCRPT_COMP_IOBJECT_PROP_TMP t1 With(Nolock)
LEFT JOIN #D7650SPCRPT_COMP_DIRECT_PROP_TMP t2 ON t2.COMPOBID = t1.COMPOBID

 -- 13
SELECT 
            FIWP.OBID AS "FIWPOBID",
            FIWP.OBJUID AS "FIWPUID",
            FIWP.CONFIG AS "PROJECT",
            FIWP.CREATIONUSER, FIWP.CREATIONDATE
			
INTO #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP
			
FROM DATAOBJ FIWP With(Nolock) WHERE FIWP.OBJDEFUID = 'SPC_FIWP' AND FIWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'

-- 14

SELECT 
            FIWP.FIWPOBID AS "FIWPOBID",
             FIWP_NAME.STRVALUE AS "NAME", 
            FIWP_DESCRIPTION.STRVALUE AS "DESCRIPTION", 
            Convert(datetime,FIWP_PLANNEDSTARTDATE.STRVALUE) AS "PLANNEDSTARTDATE",            
            Convert(datetime,FIWP_PLANNEDFINISHDATE.STRVALUE) AS "PLANNEDFINISHDATE",
            Convert(datetime,FIWP_ACTUALSTARTDATE.STRVALUE) AS "ACTUALSTARTDATE",
            Convert(datetime,FIWP_ACTUALFINISHDATE.STRVALUE) AS "ACTUALFINISHDATE",
            CAST(FIWP_ESTIMATEDMANHOURS.STRVALUE AS FLOAT) AS "ESTIMATEDMANHOURS",
            FIWP_SCOPE.STRVALUE AS "SCOPE",
            FIWP_NOTES.STRVALUE AS "NOTES",
            CAST(FIWP_CREWSIZE.STRVALUE AS INT) AS "CREWSIZE", 
            FIWP_EWPNUMBER.STRVALUE AS "EWPNUMBER",
            FIWP_CREWDURATION.STRVALUE AS "CREWDURATION",
            FIWP.FIWPUID as "UID",
           CAST( FIWP_PREVPROGRESS.STRVALUE AS FLOAT) as "PREV_PROGRESS",
           CAST( FIWP_PREVEARNED.STRVALUE AS FLOAT)  as "PREV_EARNED",
           CAST(FIWP_PREVWKLYEARNED.STRVALUE AS FLOAT)  as "PREV_WKLYEARNED"
		   
INTO  #D7650SPCRPT_FIWP_DIRECT_PROP_TMP
           
FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP FIWP With(Nolock)
	LEFT JOIN DATAOBJPR FIWP_NAME ON FIWP_NAME.OBJOBID = FIWP.FIWPOBID AND FIWP_NAME.PROPERTYDEFUID = 'Name' AND FIWP_NAME.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_DESCRIPTION ON FIWP_DESCRIPTION.OBJOBID = FIWP.FIWPOBID AND FIWP_DESCRIPTION.PROPERTYDEFUID = 'Description' AND FIWP_DESCRIPTION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_PLANNEDSTARTDATE ON FIWP_PLANNEDSTARTDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_PLANNEDSTARTDATE.PROPERTYDEFUID = 'FIWP_PlannedStartDate' AND FIWP_PLANNEDSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_PLANNEDFINISHDATE ON FIWP_PLANNEDFINISHDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_PLANNEDFINISHDATE.PROPERTYDEFUID = 'FIWP_PlannedFinishDate' AND FIWP_PLANNEDFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALSTARTDATE ON FIWP_ACTUALSTARTDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_ACTUALSTARTDATE.PROPERTYDEFUID = 'FIWP_ActualStartDate'  AND FIWP_ACTUALSTARTDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALFINISHDATE ON FIWP_ACTUALFINISHDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_ACTUALFINISHDATE.PROPERTYDEFUID = 'FIWP_ActualFinishDate'  AND FIWP_ACTUALFINISHDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ESTIMATEDMANHOURS ON FIWP_ESTIMATEDMANHOURS.OBJOBID = FIWP.FIWPOBID AND FIWP_ESTIMATEDMANHOURS.PROPERTYDEFUID = 'FIWP_Estimated_Manhours'  AND FIWP_ESTIMATEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_SCOPE ON FIWP_SCOPE.OBJOBID = FIWP.FIWPOBID AND FIWP_SCOPE.PROPERTYDEFUID = 'FIWP_Scope' AND FIWP_SCOPE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_NOTES ON FIWP_NOTES.OBJOBID = FIWP.FIWPOBID AND FIWP_NOTES.PROPERTYDEFUID like 'FIWP_Notes' AND FIWP_NOTES.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CREWSIZE ON FIWP_CREWSIZE.OBJOBID = FIWP.FIWPOBID AND FIWP_CREWSIZE.PROPERTYDEFUID = 'FIWP_Crew_Size' AND FIWP_CREWSIZE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_EWPNUMBER ON FIWP_EWPNUMBER.OBJOBID = FIWP.FIWPOBID AND FIWP_EWPNUMBER.PROPERTYDEFUID = 'FIWP_EWP_Number' AND FIWP_EWPNUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CREWDURATION ON FIWP_CREWDURATION.OBJOBID = FIWP.FIWPOBID AND FIWP_CREWDURATION.PROPERTYDEFUID = 'SPC_CrewDuration' AND FIWP_CREWDURATION.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  
  LEFT JOIN DATAOBJPR FIWP_PREVPROGRESS ON FIWP_PREVPROGRESS.OBJOBID = FIWP.FIWPOBID AND FIWP_PREVPROGRESS.PROPERTYDEFUID = 'MDR_PreviousProgress' AND FIWP_PREVPROGRESS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR FIWP_PREVEARNED ON FIWP_PREVEARNED.OBJOBID = FIWP.FIWPOBID AND FIWP_PREVEARNED.PROPERTYDEFUID = 'MDR_PreviousEarned' AND FIWP_PREVEARNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR FIWP_PREVWKLYEARNED ON FIWP_PREVWKLYEARNED.OBJOBID = FIWP.FIWPOBID AND FIWP_PREVWKLYEARNED.PROPERTYDEFUID = 'MDR_PrevWeeklyEarned' AND FIWP_PREVWKLYEARNED.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  


-- 15 
  SELECT 
            FIWP.FIWPOBID AS "FIWPOBID",
            FIWP_PURPOSE.OBJNAME AS "PURPOSE",
            FIWP_DISCIPLINE.OBJNAME AS "DISCIPLINE",
            FIWP_STATUS.OBJNAME AS "STATUS" 
            
INTO #D7650SPCRPT_FIWP_DIR_ENUM_PROP_TMP			
			
FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP FIWP With(Nolock)
	LEFT JOIN DATAOBJPR FIWP_PURPOSE_PR ON FIWP_PURPOSE_PR.OBJOBID = FIWP.FIWPOBID AND FIWP_PURPOSE_PR.PROPERTYDEFUID = 'FIWP_Purpose' AND FIWP_PURPOSE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_PURPOSE ON FIWP_PURPOSE.OBJUID = FIWP_PURPOSE_PR.STRVALUE AND FIWP_PURPOSE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_DISCIPLINE_PR ON FIWP_DISCIPLINE_PR.OBJOBID = FIWP.FIWPOBID AND FIWP_DISCIPLINE_PR.PROPERTYDEFUID = 'FIWP_Discipline' AND FIWP_DISCIPLINE_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_DISCIPLINE ON FIWP_DISCIPLINE.OBJUID = FIWP_DISCIPLINE_PR.STRVALUE AND FIWP_DISCIPLINE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  LEFT JOIN DATAOBJPR FIWP_STATUS_PR ON FIWP_STATUS_PR.OBJOBID = FIWP.FIWPOBID AND FIWP_STATUS_PR.PROPERTYDEFUID = 'Package_Status' AND FIWP_STATUS_PR.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_STATUS ON FIWP_STATUS.OBJUID = FIWP_STATUS_PR.STRVALUE AND FIWP_STATUS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
--  WHERE  FIWP_STATUS.OBJNAME != 'Preliminary'


 -- 16
  SELECT
            FIWP.FIWPOBID AS "FIWPOBID",
            CAST(FIWP_PLANNEDMANHOURS.STRVALUE AS FLOAT) AS "PLANNEDMANHOURS",
            CAST(FIWP_ACTUALMANHOURS.STRVALUE AS FLOAT) AS "ACTUALMANHOURS",
            CAST(FIWP_COMPLETEDMANHOURS.STRVALUE AS FLOAT) AS "COMPLETEDMANHOURS",
            CAST(FIWP_COMPONENTTOTALCONSTRAINTS.STRVALUE AS INT) AS "TOTALCOMPONENTCONSTRAINTS",
            CAST(FIWP_COMPONENTOPENCONSTRAINTS.STRVALUE AS INT) AS "OPENCOMPONENTCONSTRAINTS",
            FIWP_CONTRACT.STRVALUE AS "CONTRACT",
            FIWP_CONTRACTOR.STRVALUE AS "CONTRACTOR",
            FIWP_DESIGNAREA.STRVALUE AS "DESIGNAREA",
 
            FIWP_DESIGNAREA_OBJ.OBJNAME AS "FIWPJOBNUMBER", --ADDED ON 20260513

            FIWP_FOREMAN.STRVALUE AS "FOREMAN",
            FIWP_GENERALFOREMAN.STRVALUE AS "GENERALFOREMAN",
            FIWP_FIELDENGINEER.STRVALUE AS "FIELDENGINEER",
            FIWP_SUPERINTENDENT.STRVALUE AS "SUPERINTENDENT",
            FIWP_ISSUEDBY.STRVALUE AS "ISSUEDBY",
            FIWP_NAMEDCREW.OBID AS "CREWOBID",
            FIWP_CWP.OBID AS "CWPOBID",
            FIWP_REVDATE.STRVALUE AS "REVDATE",
            FIWP_RECEDATE.STRVALUE AS "RECEDATE",
            enumpr.objname AS "WP_REVNO",
            FIWP_TaskNo.STRVALUE AS "FIWPTASKNO",
            CAST(FIWP_Estimated.STRVALUE AS FLOAT) AS "FIWPAFCHRS",

			FIWP_MDRWeightage.STRVALUE AS "WEIGHTAGE",
            FIWP_MDRResourceCode.STRVALUE AS "RESOURCECODE",
			FIWP_MDRWorkPhase.STRVALUE AS "WORKPHASE",
			FIWP_MDRProgressGrouping.STRVALUE AS "PROGRESSGROUPING",
          FIWP_CWPNUMBER.STRVALUE AS "CWPNUMBER"
  
INTO #D7650SPCRPT_FIWP_REL_PROP_TMP  

FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP FIWP With(Nolock)
	LEFT JOIN DATAREL FIWP_PACKAGEROLLUPDATE_REL ON FIWP_PACKAGEROLLUPDATE_REL.UID1 = FIWP.FIWPUID AND FIWP_PACKAGEROLLUPDATE_REL.DEFUID = 'SPC_Package_PackageRollupData' AND FIWP_PACKAGEROLLUPDATE_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_PACKAGEROLLUPDATE ON FIWP_PACKAGEROLLUPDATE.OBJUID = FIWP_PACKAGEROLLUPDATE_REL.UID2 AND FIWP_PACKAGEROLLUPDATE.CONFIG = FIWP.PROJECT AND FIWP_PACKAGEROLLUPDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
  LEFT JOIN DATAOBJPR FIWP_PLANNEDMANHOURS ON FIWP_PLANNEDMANHOURS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_PLANNEDMANHOURS.PROPERTYDEFUID = 'PackageRollupData_TotalManHours' AND FIWP_PLANNEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_ACTUALMANHOURS ON FIWP_ACTUALMANHOURS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_ACTUALMANHOURS.PROPERTYDEFUID = 'PackageRollupData_TotalActualManHours' AND FIWP_ACTUALMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_COMPLETEDMANHOURS ON FIWP_COMPLETEDMANHOURS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_COMPLETEDMANHOURS.PROPERTYDEFUID = 'PackageRollupData_TotalManHoursCompleted' AND FIWP_COMPLETEDMANHOURS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_COMPONENTTOTALCONSTRAINTS ON FIWP_COMPONENTTOTALCONSTRAINTS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_COMPONENTTOTALCONSTRAINTS.PROPERTYDEFUID = 'PackageRollupData_TotalConstraints' AND FIWP_COMPONENTTOTALCONSTRAINTS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_COMPONENTOPENCONSTRAINTS ON FIWP_COMPONENTOPENCONSTRAINTS.OBJOBID = FIWP_PACKAGEROLLUPDATE.OBID AND FIWP_COMPONENTOPENCONSTRAINTS.PROPERTYDEFUID = 'PackageRollupData_OpenConstraints' AND FIWP_COMPONENTOPENCONSTRAINTS.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL FIWP_CONTRACT_REL ON FIWP_CONTRACT_REL.UID1 = FIWP.FIWPUID AND FIWP_CONTRACT_REL.DEFUID = 'SPC_Package_Contract' AND FIWP_CONTRACT_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_CONTRACT_OBJ ON FIWP_CONTRACT_OBJ.OBJUID = FIWP_CONTRACT_REL.UID2 AND FIWP_CONTRACT_OBJ.CONFIG = FIWP.PROJECT AND FIWP_CONTRACT_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CONTRACT ON FIWP_CONTRACT.OBJOBID = FIWP_CONTRACT_OBJ.OBID AND FIWP_CONTRACT.PROPERTYDEFUID = 'Description' AND FIWP_CONTRACT.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
  LEFT JOIN DATAREL FIWP_CONTRACTOR_REL ON FIWP_CONTRACTOR_REL.UID1 = FIWP.FIWPUID AND FIWP_CONTRACTOR_REL.DEFUID = 'SPC_Package_Contractor' AND FIWP_CONTRACTOR_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_CONTRACTOR_OBJ ON FIWP_CONTRACTOR_OBJ.OBJUID = FIWP_CONTRACTOR_REL.UID2 AND FIWP_CONTRACTOR_OBJ.CONFIG = FIWP.PROJECT AND FIWP_CONTRACTOR_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_CONTRACTOR ON FIWP_CONTRACTOR.OBJOBID = FIWP_CONTRACTOR_OBJ.OBID AND FIWP_CONTRACTOR.PROPERTYDEFUID = 'Name' AND FIWP_CONTRACTOR.TERMINATIONDATE = '9999/12/31-23:59:59:999'


--FIWP Job Number
	LEFT JOIN DATAREL FIWP_DESIGNAREA_REL ON FIWP_DESIGNAREA_REL.UID2 = FIWP.FIWPUID AND FIWP_DESIGNAREA_REL.DEFUID = 'SPC_FunctionalArea_FIWPs' AND FIWP_DESIGNAREA_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_DESIGNAREA_OBJ ON FIWP_DESIGNAREA_OBJ.OBJUID = FIWP_DESIGNAREA_REL.UID1 AND FIWP_DESIGNAREA_OBJ.CONFIG = FIWP.PROJECT AND FIWP_DESIGNAREA_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999' AND FIWP_DESIGNAREA_OBJ.OBJDEFUID = 'SPFFunctionalArea'
	LEFT JOIN DATAOBJPR FIWP_DESIGNAREA ON FIWP_DESIGNAREA.OBJOBID = FIWP_DESIGNAREA_OBJ.OBID AND FIWP_DESIGNAREA.PROPERTYDEFUID = 'Name' AND FIWP_DESIGNAREA.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	--LEFT JOIN DATAREL FIWP_FOREMAN_REL ON FIWP_FOREMAN_REL.UID1 = FIWP.FIWPUID AND FIWP_FOREMAN_REL.DEFUID = 'SPC_Package_ForemanRole' AND FIWP_FOREMAN_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	LEFT JOIN
  (
    select DENSE_RANK() OVER (PARTITION BY UID1 ORDER BY CREATIONDATE DESC) AS SEQUENCE , UID1, UID2, CREATIONDATE
    FROM SCHEMAREL With(Nolock) where  DEFUID='SPC_Package_ForemanRole'
    AND TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  ) FIWP_FOREMAN_REL ON FIWP_FOREMAN_REL.UID1=FIWP.FIWPUID AND FIWP_FOREMAN_REL.SEQUENCE=1
	
	LEFT JOIN SCHEMAOBJ FIWP_FOREMAN_OBJ ON FIWP_FOREMAN_OBJ.OBJUID = FIWP_FOREMAN_REL.UID2 AND FIWP_FOREMAN_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_FOREMAN ON FIWP_FOREMAN.OBJOBID = FIWP_FOREMAN_OBJ.OBID AND FIWP_FOREMAN.PROPERTYDEFUID = 'Name' AND FIWP_FOREMAN.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	
	--LEFT JOIN DATAREL FIWP_GENERALFOREMAN_REL ON FIWP_GENERALFOREMAN_REL.UID1 = FIWP.FIWPUID AND FIWP_GENERALFOREMAN_REL.DEFUID = 'SPC_Package_GeneralForemanRole' AND FIWP_GENERALFOREMAN_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	LEFT JOIN
  (
    select DENSE_RANK() OVER (PARTITION BY UID1 ORDER BY CREATIONDATE DESC) AS SEQUENCE , UID1, UID2, CREATIONDATE
    FROM SCHEMAREL With(Nolock) where  DEFUID='SPC_Package_GeneralForemanRole'
    AND TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  ) FIWP_GENERALFOREMAN_REL ON FIWP_GENERALFOREMAN_REL.UID1=FIWP.FIWPUID AND FIWP_GENERALFOREMAN_REL.SEQUENCE=1
	
	LEFT JOIN SCHEMAOBJ FIWP_GENERALFOREMAN_OBJ ON FIWP_GENERALFOREMAN_OBJ.OBJUID = FIWP_GENERALFOREMAN_REL.UID2 AND FIWP_GENERALFOREMAN_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_GENERALFOREMAN ON FIWP_GENERALFOREMAN.OBJOBID = FIWP_GENERALFOREMAN_OBJ.OBID AND FIWP_GENERALFOREMAN.PROPERTYDEFUID = 'Name' AND FIWP_GENERALFOREMAN.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	
	LEFT JOIN SCHEMAREL FIWP_FIELDENGINEER_REL ON FIWP_FIELDENGINEER_REL.UID1 = FIWP.FIWPUID AND FIWP_FIELDENGINEER_REL.DEFUID = 'SPC_Package_FieldEngineerRole' AND FIWP_FIELDENGINEER_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_FIELDENGINEER_OBJ ON FIWP_FIELDENGINEER_OBJ.OBJUID = FIWP_FIELDENGINEER_REL.UID2 AND FIWP_FIELDENGINEER_OBJ.CONFIG = FIWP.PROJECT AND FIWP_FIELDENGINEER_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_FIELDENGINEER ON FIWP_FIELDENGINEER.OBJOBID = FIWP_FIELDENGINEER_OBJ.OBID AND FIWP_FIELDENGINEER.PROPERTYDEFUID = 'Name' AND FIWP_FIELDENGINEER.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAREL FIWP_SUPERINTENDENT_REL ON FIWP_SUPERINTENDENT_REL.UID1 = FIWP.FIWPUID AND FIWP_SUPERINTENDENT_REL.DEFUID = 'SPC_Package_SuperintendentRole' AND FIWP_SUPERINTENDENT_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_SUPERINTENDENT_OBJ ON FIWP_SUPERINTENDENT_OBJ.OBJUID = FIWP_SUPERINTENDENT_REL.UID2 AND FIWP_SUPERINTENDENT_OBJ.CONFIG = FIWP.PROJECT AND FIWP_SUPERINTENDENT_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_SUPERINTENDENT ON FIWP_SUPERINTENDENT.OBJOBID = FIWP_SUPERINTENDENT_OBJ.OBID AND FIWP_SUPERINTENDENT.PROPERTYDEFUID = 'Name' AND FIWP_SUPERINTENDENT.TERMINATIONDATE = '9999/12/31-23:59:59:999'	
  LEFT JOIN SCHEMAREL FIWP_ISSUEDBY_REL ON FIWP_ISSUEDBY_REL.UID1 = FIWP.FIWPUID AND FIWP_ISSUEDBY_REL.DEFUID = 'SPC_Package_IWPIssuedBy' AND FIWP_ISSUEDBY_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJ FIWP_ISSUEDBY_OBJ ON FIWP_ISSUEDBY_OBJ.OBJUID = FIWP_ISSUEDBY_REL.UID2 AND  FIWP_ISSUEDBY_OBJ.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN SCHEMAOBJPR FIWP_ISSUEDBY ON FIWP_ISSUEDBY.OBJOBID = FIWP_ISSUEDBY_OBJ.OBID AND FIWP_ISSUEDBY.PROPERTYDEFUID = 'Name' AND FIWP_ISSUEDBY.TERMINATIONDATE = '9999/12/31-23:59:59:999' 
  LEFT JOIN DATAREL FIWP_NAMEDCREW_REL ON FIWP_NAMEDCREW_REL.UID1 = FIWP.FIWPUID AND FIWP_NAMEDCREW_REL.DEFUID = 'SPC_Package_Crew' AND FIWP_NAMEDCREW_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_NAMEDCREW ON FIWP_NAMEDCREW.OBJUID = FIWP_NAMEDCREW_REL.UID2 AND FIWP_NAMEDCREW.CONFIG = FIWP.PROJECT AND FIWP_NAMEDCREW.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAREL FIWP_CWP_REL ON FIWP_CWP_REL.UID2 = FIWP.FIWPUID AND FIWP_CWP_REL.DEFUID = 'SPC_CWP_FIWPs' AND FIWP_CWP_REL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJ FIWP_CWP ON FIWP_CWP.OBJUID = FIWP_CWP_REL.UID1 AND FIWP_CWP.CONFIG = FIWP.PROJECT AND FIWP_CWP.TERMINATIONDATE = '9999/12/31-23:59:59:999'
      	--IWP REVDATE
	LEFT JOIN DATAOBJPR FIWP_REVDATE ON FIWP_REVDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_REVDATE.PROPERTYDEFUID = 'MDR_RevDate' AND FIWP_REVDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	LEFT JOIN DATAOBJPR FIWP_REV ON FIWP_REV.OBJOBID = FIWP.FIWPOBID AND FIWP_REV.PROPERTYDEFUID = 'MDR_Rev' AND FIWP_REV.TERMINATIONDATE = '9999/12/31-23:59:59:999'	
  left join schemaobj enumpr on FIWP_REV.strvalue=enumpr.objuid and enumpr.objdefuid='EnumEnum' and enumpr.terminationdate='9999/12/31-23:59:59:999'
--where pr.propertydefuid='MDR_Rev' and pr.OBJOBID = '1SRI000A' 
  
	--IWP RECEDATE
	LEFT JOIN DATAOBJPR FIWP_RECEDATE ON FIWP_RECEDATE.OBJOBID = FIWP.FIWPOBID AND FIWP_RECEDATE.PROPERTYDEFUID = 'MDR_RecievedDate' AND FIWP_RECEDATE.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--FIWP TASK NO
	LEFT JOIN DATAOBJPR FIWP_TaskNo ON FIWP_TaskNo.OBJOBID = FIWP.FIWPOBID AND FIWP_TaskNo.PROPERTYDEFUID = 'MDR_FIWPTaskNo' AND FIWP_TaskNo.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--FIWP AFC Hrs
	LEFT JOIN DATAOBJPR FIWP_Estimated ON FIWP_Estimated.OBJOBID = FIWP.FIWPOBID AND FIWP_Estimated.PROPERTYDEFUID = 'FIWP_Estimated_Manhours' AND FIWP_Estimated.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--MDR_Weld_Weightage
	LEFT JOIN DATAOBJPR FIWP_MDRWeightage ON FIWP_MDRWeightage.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRWeightage.PROPERTYDEFUID = 'MDR_Weld_Weightage' AND FIWP_MDRWeightage.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--MDR_ResourceCode
	LEFT JOIN DATAOBJPR FIWP_MDRResourceCode ON FIWP_MDRResourceCode.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRResourceCode.PROPERTYDEFUID = 'MDR_ResourceCode' AND FIWP_MDRResourceCode.TERMINATIONDATE = '9999/12/31-23:59:59:999'
	
	--MDR_ProgressGrouping
	LEFT JOIN DATAOBJPR FIWP_MDRProgressGrouping ON FIWP_MDRProgressGrouping.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRProgressGrouping.PROPERTYDEFUID = 'MDR_ProgressGrouping' AND FIWP_MDRProgressGrouping.TERMINATIONDATE = '9999/12/31-23:59:59:999'

	--MDR_WorkPhase
	LEFT JOIN DATAOBJPR FIWP_MDRWorkPhase ON FIWP_MDRWorkPhase.OBJOBID = FIWP.FIWPOBID AND FIWP_MDRWorkPhase.PROPERTYDEFUID = 'MDR_WorkPhase' AND FIWP_MDRWorkPhase.TERMINATIONDATE = '9999/12/31-23:59:59:999'

   --CWP Number
    LEFT JOIN DATAOBJPR FIWP_CWPNUMBER ON FIWP_CWPNUMBER.OBJOBID = FIWP.FIWPOBID AND FIWP_CWPNUMBER.PROPERTYDEFUID = 'MDR_Proj_CWP' AND FIWP_CWPNUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'

     --LEFT JOIN DATAREL FIWP_CWPNUMBERREL ON FIWP_CWPNUMBERREL.UID2 = FIWP.FIWPUID AND FIWP_CWPNUMBERREL.DEFUID = 'SPC_CWP_FIWPs' AND FIWP_CWPNUMBERREL.TERMINATIONDATE = '9999/12/31-23:59:59:999'
     --LEFT JOIN DATAOBJ FIWP_CWPNUMBER ON FIWP_CWPNUMBER.OBJUID = FIWP_CWPNUMBERREL.UID1 AND FIWP_CWPNUMBER.OBJDEFUID = 'SPC_CWP' AND FIWP_CWPNUMBER.TERMINATIONDATE = '9999/12/31-23:59:59:999'




	 
-- 17
  SELECT DISTINCT
    t1.FIWPUID,
    t1.PROJECT AS "PROJECT",
    t3.DISCIPLINE,
    t2.NAME AS "WPNO",
    t2.DESCRIPTION as "WPDESCRIPTION",
    t5.COSTCODE  AS "ACTIVITYCODE",	
    --T6.NAME AS "NAME",     
    T5.SEQUENCE ,
    sum(T5.ACTUALMANHOURS) AS "COMPLETEDMANHOURS",
    SUM(NULLIF(T5.PLANNEDMANHOURS,0)) AS "PLANNEDHOURS",
    --ISNULL(AVG(round((t5.QUANTITYCOMPLETE/t6.UNITS) * 100,1)),0) AS "PERCCOMP",
    t4.CWPOBID, t4.REVDATE, t4.RECEDATE, t4.FIWPTASKNO, t4.FIWPAFCHRS as FIWPAFCHRS ,t4.FIWPOBID,   t1.CREATIONUSER, t1.CREATIONDATE,
	t4.WEIGHTAGE ,t4.RESOURCECODE,t4.WORKPHASE,t4.PROGRESSGROUPING,t4.CWPNUMBER,
    NULLIF(t2.PREV_PROGRESS,0)  as "PREV_PROGRESS",
    NULLIF(t2.PREV_EARNED,0)  as "PREV_EARNED",
    NULLIF(t2.PREV_WKLYEARNED,0) as "PREV_WKLYEARNED" ,
    t5.RATEUOM, t3.PURPOSE, t4.CONTRACTOR as "AREA", t4.FOREMAN as "FOREMAN",t4.GENERALFOREMAN as "GENERALFOREMAN",t4.ISSUEDBY as "ISSUEDBY", t3.STATUS,
    t2.PLANNEDSTARTDATE, t2.PLANNEDFINISHDATE, t2.ACTUALSTARTDATE, t2.ACTUALFINISHDATE, SUM(t5.PLAN_UNITS) as PLAN_UNITS, SUM(t5.UNIT_COMPLETED) as UNIT_COMPLETED, t4.WP_REVNO,
    t4.FIWPJOBNUMBER -- ADDED ON 20260513
    
INTO #D7650COMBINED	
	
FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP t1 With(Nolock)
LEFT JOIN #D7650SPCRPT_FIWP_DIRECT_PROP_TMP t2 ON t2.FIWPOBID = t1.FIWPOBID
LEFT JOIN #D7650SPCRPT_FIWP_DIR_ENUM_PROP_TMP t3 ON t3.FIWPOBID = t1.FIWPOBID
LEFT JOIN #D7650SPCRPT_FIWP_REL_PROP_TMP t4 ON t4.FIWPOBID = t1.FIWPOBID
LEFT JOIN #D7650WORKSTEPS t5 ON t5.FIWPOBID = t1.FIWPOBID
LEFT JOIN #D7650SPCRPT_COMPONENTITEM1 t6 ON t6.COMPOBID = t5.COMPOBID
--WHERE t5.PLANNEDMANHOURS > 0
--WHERE t3.STATUS='Issued For Construction' and t5.PLANNEDMANHOURS > 0 
GROUP BY t1.FIWPUID, T2.NAME, t2.DESCRIPTION, T1.PROJECT, T5.COSTCODE, t3.DISCIPLINE, T5.SEQUENCE , T4.CWPOBID, COMPLETEDMANHOURS,  t4.CWPOBID , 
t4.REVDATE, t4.RECEDATE, t4.FIWPTASKNO, t4.FIWPOBID , t1.CREATIONUSER, t1.CREATIONDATE,  t2.PREV_PROGRESS,  t2.PREV_EARNED, t2.PREV_WKLYEARNED, t5.RATEUOM, t3.PURPOSE, t4.CONTRACTOR , t4.FOREMAN,t4.GENERALFOREMAN, t4.ISSUEDBY,t3.STATUS,
  t2.PLANNEDSTARTDATE, t2.PLANNEDFINISHDATE, t2.ACTUALSTARTDATE, t2.ACTUALFINISHDATE , t4.WP_REVNO, t4.FIWPAFCHRS, t4.WEIGHTAGE ,t4.RESOURCECODE,t4.WORKPHASE,t4.PROGRESSGROUPING,t4.CWPNUMBER,
  t4.FIWPJOBNUMBER


 

-- 18
  SELECT distinct
    t1.PROJECT AS "PROJECT",
    t2.NAME AS "WPNO",
    t5.CREATIONUSER, t5.CREATIONDATE

INTO #D7650BY_WORKPACK
    
FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP t1 With(Nolock)
LEFT JOIN #D7650SPCRPT_FIWP_DIRECT_PROP_TMP t2 ON t2.FIWPOBID = t1.FIWPOBID
LEFT JOIN #D7650WORKSTEPS t5 ON t5.FIWPOBID = t1.FIWPOBID



-- 19
  SELECT a.* 
  INTO #D7650GET_USERINFO 
  from #D7650BY_WORKPACK a With(Nolock)
  inner join
  (
    select project, wpno, max(creationdate) as creationdate from #D7650BY_WORKPACK With(Nolock) group by project, wpno
  )b
  on a.project=b.project and a.wpno=b.wpno and a.creationdate=b.creationdate

-- 20
  SELECT DISTINCT B.DESIGNAREA AS JOBNO, A.ACTIVITYCODE AS ACTIVITYCODE, A.WPNO, A.FIWPUID,
  C.PLANNEDHOURS as PLANNEDHOURS, 
  C.COMPLETEDMANHOURS - C.PLANNEDHOURS  as "BALANCE", C.CUMPROGRESS, C.UNIT_COMPLETED, C.PLAN_UNITS,  C.CUMPROGRESS * C.PLANNEDHOURS as CUMEARNED
  
  INTO #D7650TOTALPLANHRS
  
  FROM  #D7650COMBINED A With(Nolock)
  LEFT JOIN #D7650SPCCWP B ON A.CWPOBID = B.CWPOBID 
  LEFT JOIN 
  (
      select FIWPOBID, sum(PLANNEDHOURS) as PLANNEDHOURS, SUM(COMPLETEDMANHOURS) as COMPLETEDMANHOURS, SUM(PLAN_UNITS) as PLAN_UNITS,
      SUM(UNIT_COMPLETED) as UNIT_COMPLETED, SUM(COMPLETEDMANHOURS) / SUM(PLANNEDHOURS) as CUMPROGRESS, SUM(CUMEARNED) as CUMEARNED
      FROM
      (
      
       SELECT   FIWPOBID,  SUM(NULLIF(PLANNEDMANHOURS,0)) as PLANNEDHOURS, sum(ActualManHours) as COMPLETEDMANHOURS, sum(Plan_units)/ count(*) as PLAN_UNITS, 
       sum(Unit_Completed) / count(*) as UNIT_COMPLETED, (sum(ActualManHours) /  SUM(NULLIF(PLANNEDMANHOURS,0))) as CUMPROGRESS,   
            (sum(ActualManHours) /  SUM(NULLIF(PLANNEDMANHOURS,0))) *   SUM(NULLIF(PLANNEDMANHOURS,0)) as CUMEARNED
            from #D7650WorkSteps With(Nolock)
         --   where fiwpobid='2XCC000A'
            Group by FIWPOBID, COMPOBID
      ) XX GROUP BY FIWPOBID
       
  ) C ON C.FIWPOBID=A.FIWPOBID 
  --AND SUBSTRING(A.WPNO, 1,LEN(A.ACTIVITYCODE)  
  --WHERE  SUBSTRING(A.WPNO, 1,LEN(A.ACTIVITYCODE)>0



-- 20
      SELECT FIWPUID, 
       SUM(QUANTITYCOMPLETE) as "FIWP_QTYCOMPLETE" , 
       SUM(QUANTITYPLANNED) as  "FIWP_QTYPLAN", 
       SUM(PLANNEDMANHOURS)  as "FIWP_PLANH", 
       SUM(ACTUALMANHOURS)   as "FIWP_ACTUAL"
	   
	   INTO #D7650FIWPTOTAL
       
	   FROM
       (
        SELECT t1x.FIWPUID, t5x.COMPOBID, t5x.PROJECT,  t5x.FIWPOBID, SUM(t5x.ACTUALMANHOURS) as ACTUALMANHOURS, SUM(t5x.PLANNEDMANHOURS) as PLANNEDMANHOURS, 
                                             AVG(t5x.QUANTITYCOMPLETE) as QUANTITYCOMPLETE, AVG(t5x.QUANTITYPLANNED) as QUANTITYPLANNED 
        FROM #D7650WORKSTEPS t5x With(Nolock)
        LEFT JOIN #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP t1x ON t5x.FIWPOBID = t1x.FIWPOBID
        GROUP BY t1x.FIWPUID, t5x.COMPOBID, t5x.PROJECT,  t5x.FIWPOBID
        
       ) X
       GROUP BY FIWPUID  


 -- 21
    SELECT t1.FIWPUID, t5.Name, t5.sequence,  SUM(NULLIF(t5.PLANNEDMANHOURS,0))  as "PLANH", ROUND(SUM(NULLIF(t5.ACTUALMANHOURS,0)),2) as "ACTUAL" , SUM(t5.UNIT_COMPLETED) as UNIT_COMPLETED, 
   -- CASE WHEN SUM(t5.PLAN_UNITS)=0 THEN 0 ELSE CASE WHEN SUM(t5.UNIT_COMPLETED) / SUM(t5.PLAN_UNITS)>1 THEN 1 ELSE SUM(t5.UNIT_COMPLETED) / SUM(t5.PLAN_UNITS) END  END as "GATEPROGRESS"
 
  CASE WHEN SUM(t5.PLANNEDMANHOURS)=0 THEN 0 ELSE CASE WHEN SUM(t5.ACTUALMANHOURS) / SUM(t5.PLANNEDMANHOURS)>1 THEN 1 ELSE SUM(t5.ACTUALMANHOURS) / SUM(t5.PLANNEDMANHOURS) END  END as "GATEPROGRESS",

  sum(t5.Gate_QTYComplete) as "GATEQTY_COMPLETE" 
  
  INTO #D7650BYGATES1
 
        FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP t1 With(Nolock)
    LEFT JOIN #D7650WORKSTEPS t5 ON t5.FIWPOBID = t1.FIWPOBID    
    --LEFT JOIN #D7650FIWPTOTAL t6 ON t6.FIWPUID = t1.FIWPUID
    where t5.Name is not Null    
    GROUP BY t1.FIWPUID, t5.sequence,t5.Name
    --Order By t5.sequence


-- 21
    SELECT FIWPUID ,Name,ROW_NUMBER() OVER (PARTITION BY FIWPUID ORDER BY Sequence Asc) As Sequence,Planh,Actual,UNIT_Completed,GATEPROGRESS,Gateqty_Complete,
    Sequence As Seqno
	
	INTO #D7650BYGATES
	
    FROM #D7650BYGATES1 With(Nolock)



-- 22
   SELECT FIWPUID, SUM(TOTAL) as COUNT_COMPLETE , SUM(PLANNED) as COUNT_PLANNED
   INTO #D7650COUNTINFO
   FROM
   (
    select FIWPUID, COMPOBID, MAX(SEQUENCE) as SEQUENCE, SUM(ISDONE) as ISDONE, CASE WHEN MAX(SEQUENCE)= SUM(ISDONE) THEN 1 ELSE 0 END as TOTAL, 1 as PLANNED
    
	
	
	FROM
    (
         SELECT  t1x.FIWPUID, COMPOBID, t5x.NAME, Seq.SEQUENCE, CASE WHEN PLANNEDMANHOURS <= ACTUALMANHOURS THEN 1 else 0 end as IsDONE
         FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP t1x With(Nolock)
	 Left Join #D7650BYGATES Seq ON Seq.FIWPUID = t1x.FIWPUID -- Added for Sequence re-order issue
         LEFT JOIN #D7650WORKSTEPS t5x ON t5x.FIWPOBID = t1x.FIWPOBID And t5x.Name = Seq.Name
        --ORDER BY t1x.FIWPUID , COMPOBID
   ) A
   GROUP BY FIWPUID, COMPOBID
   ) B
   GROUP BY FIWPUID




  SELECT a.FIWPUID, G1.NAME as G1 , G2.NAME as G2  , G3.NAME as G3  , G4.NAME as G4  , G5.NAME as G5  , G6.NAME as G6,
                    G1.PLANH as G1H , G2.PLANH as G2H , G3.PLANH as G3H ,  G4.PLANH as G4H ,  G5.PLANH as G5H , G6.PLANH as G6H,
                    G1.ACTUAL as G1A , G2.ACTUAL as G2A , G3.ACTUAL as G3A ,  G4.ACTUAL as G4A ,  G5.ACTUAL as G5A , G6.ACTUAL as G6A,
                    t6.FIWP_QTYPLAN as QTYPLANNED, t6.FIWP_QTYCOMPLETE as QTYCOMPLETE, t6.FIWP_ACTUAL as FIWP_ACTUAL, C1.COUNT_COMPLETE, C1.COUNT_PLANNED, 
                    G1.UNIT_COMPLETED as UNIT_COMPLETED_1, 
                    G2.UNIT_COMPLETED as UNIT_COMPLETED_2, 
                    G3.UNIT_COMPLETED as UNIT_COMPLETED_3, 
                    G4.UNIT_COMPLETED as UNIT_COMPLETED_4, 
                    G5.UNIT_COMPLETED as UNIT_COMPLETED_5, 
                    G6.UNIT_COMPLETED as UNIT_COMPLETED_6,
                    G1.GATEPROGRESS as G1_PROGRESS, 
                    G2.GATEPROGRESS as G2_PROGRESS,
                    G3.GATEPROGRESS as G3_PROGRESS,
                    G4.GATEPROGRESS as G4_PROGRESS,
                    G5.GATEPROGRESS as G5_PROGRESS,
                    G6.GATEPROGRESS as G6_PROGRESS,
                    G1.GATEQTY_COMPLETE as G1_QTYCOMPLETE,
                    G2.GATEQTY_COMPLETE as G2_QTYCOMPLETE,
                    G3.GATEQTY_COMPLETE as G3_QTYCOMPLETE,
                    G4.GATEQTY_COMPLETE as G4_QTYCOMPLETE,
                    G5.GATEQTY_COMPLETE as G5_QTYCOMPLETE,
                    G6.GATEQTY_COMPLETE as G6_QTYCOMPLETE

  INTO #D7650GATE
  
  FROM #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP a With(Nolock)
  LEFT JOIN #D7650FIWPTOTAL t6 ON t6.FIWPUID = A.FIWPUID  
  LEFT JOIN #D7650COUNTINFO C1 on C1.FIWPUID=A.FIWPUID
  LEFT JOIN #D7650BYGATES G1 on A.FIWPUID=G1.FIWPUID AND G1.sequence=1
  LEFT JOIN #D7650BYGATES G2 on A.FIWPUID=G2.FIWPUID AND G2.sequence=2
  LEFT JOIN #D7650BYGATES G3 on A.FIWPUID=G3.FIWPUID AND G3.sequence=3
  LEFT JOIN #D7650BYGATES G4 on A.FIWPUID=G4.FIWPUID AND G4.sequence=4
  LEFT JOIN #D7650BYGATES G5 on A.FIWPUID=G5.FIWPUID AND G5.sequence=5
  LEFT JOIN #D7650BYGATES G6 on A.FIWPUID=G6.FIWPUID AND G6.sequence=6




  SELECT distinct A.FIWPUID,  A.PROJECT, FIWPOBID,
  A.FIWPTASKNO,
  --B.WBSPATH AS "TASK NO", 
  A.FIWPTASKNO AS "TASK NO",

  --B.DESIGNAREA AS "JOB NO" COMMENTED ON 20260513, 

A.ACTIVITYCODE AS "ACTIVITY CODE", A.DISCIPLINE,  B.NAME as "ACTIVITY ID",  
  A.WPNO, A.WPDESCRIPTION as "WP DESCRIPTION",
  A.WP_REVNO,
  B.DESCRIPTION AS "ACTIVITY ID DESCRIPTION",
  --ROUND((B.BUDGETEDLABORHOURS),2) AS "AFC Hrs",
  
  --SUM(ROUND((A.FIWPAFCHRS),2)) AS "AFC Hrs",
  ROUND(A.FIWPAFCHRS,2) AS "AFC Hrs",
  --A.SEQUENCE, 
  C.PLANNEDHOURS as "WP Hrs", 
  --ROUND((B.BUDGETEDLABORHOURS),2) - C.PLANNEDHOURS as "AFC WP DELTA Hrs",
 
  ROUND((A.FIWPAFCHRS),2) - C.PLANNEDHOURS as "AFC WP DELTA Hrs", 

 

  CASE WHEN  ROUND((A.FIWPAFCHRS),2)<=C.PLANNEDHOURS  THEN  CASE WHEN C.CUMPROGRESS>1 THEN 1 ELSE C.CUMPROGRESS END  ELSE ROUND(C.CUMEARNED/ROUND((A.FIWPAFCHRS),2),4) END   AS "AFC Progress",
 
  --ROUND((CASE WHEN C.PLANNEDHOURS < ROUND((B.BUDGETEDLABORHOURS),2) THEN ROUND(C.CUMEARNED/ROUND((B.BUDGETEDLABORHOURS),2),4)  ELSE  C.CUMPROGRESS END) * ROUND--((B.BUDGETEDLABORHOURS),2),2) AS "AFC Earned Hrs",

  CASE WHEN  ROUND((A.FIWPAFCHRS),2)<=C.PLANNEDHOURS  THEN  CASE WHEN C.CUMPROGRESS>1 THEN 1 ELSE C.CUMPROGRESS END  ELSE ROUND(C.CUMEARNED/ROUND((A.FIWPAFCHRS),2),4) END * A.FIWPAFCHRS  AS "AFC Earned Hrs",
 
--ROUND((CASE WHEN C.PLANNEDHOURS < ROUND((B.BUDGETEDLABORHOURS),2) THEN ROUND(C.CUMEARNED/ROUND((B.BUDGETEDLABORHOURS),2),4)  ELSE  C.CUMPROGRESS END) * ROUND((B.BUDGETEDLABORHOURS),2),2) 
--ROUND(C.CUMEARNED,2) As "AFC WP Earned Delta Hrs" ,

ROUND((CASE WHEN C.PLANNEDHOURS < ROUND((A.FIWPAFCHRS),2) THEN ROUND(C.CUMEARNED/ROUND((A.FIWPAFCHRS),2),4)  ELSE  C.CUMPROGRESS END)  * ROUND((A.FIWPAFCHRS),2),2) -
ROUND(C.CUMEARNED,2) As "AFC WP Earned Delta Hrs" ,


--CASE WHEN C.PLANNEDHOURS < ROUND((B.BUDGETEDLABORHOURS),2) THEN ROUND(C.CUMEARNED/ROUND((B.BUDGETEDLABORHOURS),2),4)  ELSE  C.CUMPROGRESS END -  C.CUMPROGRESS 
--As  "AFC WP Progress Delta",

CASE WHEN C.PLANNEDHOURS < ROUND((A.FIWPAFCHRS),2) THEN ROUND(C.CUMEARNED/ROUND((A.FIWPAFCHRS),2),4)  ELSE  C.CUMPROGRESS END -  C.CUMPROGRESS 
As  "AFC WP Progress Delta",

  C.CUMPROGRESS  as "WP Progress",
  ROUND(C.CUMEARNED,2) as "WP Earned Hrs",
  --E.QTYPLANNED AS "WP Components Qty Planned", 
  --E.QTYCOMPLETE AS "WP Components Qty Complete", 
   ' ' AS "WP Components Qty Planned",
   ' ' As "WP Components Qty Complete",
  C.PLAN_UNITS as PLAN_UNITS, C.PLAN_UNITS * C.CUMPROGRESS  as COMPLETED_UNITS,
  
  --A.RATEUOM,
  ' ' as RATEUOM,
  A.PURPOSE AS "WP PURPOSE",
  ISNULL(A.PREV_PROGRESS,0) as "WP Last Week Progress",
  ISNULL(A.PREV_EARNED,0) as "WP Last Week Earned",
  ISNULL(A.PREV_WKLYEARNED,0) as "WP Last Week Weekly Earned",
  ISNULL(C.CUMPROGRESS,0) -  ISNULL(A.PREV_PROGRESS,0) as "WP Weekly Progress",
  ROUND(ISNULL(C.CUMEARNED,0),3) -  ROUND(ISNULL(A.PREV_EARNED,0),3)  as "WP Weekly Earned",
  E.COUNT_COMPLETE AS "WP Components Count Complete", 
E.COUNT_PLANNED AS "WP Components Count Planned", 
A.AREA, A.STATUS
  ,A.REVDATE AS "WP Revision Date", 
A.RECEDATE AS "WP Receive Date", 
D.CREATIONUSER as "WP Last Progress By", SUBSTRING(D.CREATIONDATE,1, 10) as "WP Last Progress Date", A.CREATIONUSER AS "WP Creation User", 
SUBSTRING(A.CREATIONDATE,1,10) as "WP Creation Date",
A.FOREMAN as "Foreman",
A.GENERALFOREMAN as "General Foreman",
A.ISSUEDBY as "IWP Issued By",  
  A.PLANNEDSTARTDATE AS "WP Planned Start Date",
  A.PLANNEDFINISHDATE AS "WP Planned Finish Date",
  A.ACTUALSTARTDATE AS "WP Actual Start Date", 
  A.ACTUALFINISHDATE AS "WP Actual Finish Date",
  B.EARLYSTARTDATE AS "L3 Forecast Start Date", 
  B.EARLYFINISHDATE AS "L3 Forecast Finish Date", 
  B.LATESTARTDATE AS "L3 Baseline Start Date", 
  B.LATEFINISHDATE AS "L3 Baseline Finish Date", 

  --C.BALANCE,
 
  --CASE WHEN SUM(A.COMPLETEDMANHOURS)>SUM(A.PLANNEDHOURS) THEN 1 ELSE ROUND(SUM(A.COMPLETEDMANHOURS) / NULLIF(SUM(A.PLANNEDHOURS),0), 4) END as "PERCCOMP" 

  --GATES
  E.G1 AS "ROC 1", E.G2 AS "ROC 2", E.G3 AS "ROC 3", E.G4 AS "ROC 4", E.G5 AS "ROC 5", E.G6 AS "ROC 6", 
  
  --WEIGHTAGES
  CASE WHEN ROUND(E.G1H/nullif(C.PLANNEDHOURS,0),2)>1 then -1 else ROUND(nullif(E.G1H,0)/nullif(C.PLANNEDHOURS,0),2) end as "ROC Weightage 1",   
  CASE WHEN ROUND(E.G1H/nullif(C.PLANNEDHOURS,0),2)>1 then -1 else ROUND(nullif(E.G2H,0)/nullif(C.PLANNEDHOURS,0),2) end as "ROC Weightage 2",   
  CASE WHEN ROUND(E.G1H/nullif(C.PLANNEDHOURS,0),2)>1 then -1 else ROUND(nullif(E.G3H,0)/nullif(C.PLANNEDHOURS,0),2) end as "ROC Weightage 3",   
  CASE WHEN ROUND(E.G1H/nullif(C.PLANNEDHOURS,0),2)>1 then -1 else ROUND(nullif(E.G4H,0)/nullif(C.PLANNEDHOURS,0),2) end as "ROC Weightage 4",  
  CASE WHEN ROUND(E.G1H/nullif(C.PLANNEDHOURS,0),2)>1 then -1 else ROUNd(nullif(E.G5H,0)/nullif(C.PLANNEDHOURS,0),2) end as "ROC Weightage 5",  
  CASE WHEN ROUND(E.G1H/nullif(C.PLANNEDHOURS,0),2)>1 then -1 else ROUND(nullif(E.G6H,0)/nullif(C.PLANNEDHOURS,0),2) end as "ROC Weightage 6", 
  
  --PLANHOURS
  E.G1H AS "WP Hrs ROC 1",  E.G2H AS "WP Hrs ROC 2",   E.G3H AS "WP Hrs ROC 3",   E.G4H AS "WP Hrs ROC 4",   E.G5H AS "WP Hrs ROC 5",   E.G6H AS "WP Hrs ROC 6",   
  
  --EARNINGS
  E.G1A as "WP Earned Hrs ROC 1",   E.G2A as "WP Earned Hrs ROC 2",  E.G3A as "WP Earned Hrs ROC 3",  E.G4A as "WP Earned Hrs ROC 4",  E.G5A as "WP Earned Hrs ROC 5",  E.G6A as "WP Earned Hrs ROC 6",

  --WP Progress Gate
--ROUND(E.G1A /  E.G1H,4)  As "WP Progress ROC 1",
--ROUND(E.G2A /  E.G2H, 4) As "WP Progress ROC 2",
--ROUND(E.G3A /  E.G3H, 4) As "WP Progress ROC 3",
--ROUND(E.G4A /  E.G4H, 4) As "WP Progress ROC 4",
--ROUND(E.G5A /  E.G5H, 4) As "WP Progress ROC 5",
--ROUND(E.G6A /  E.G6H, 4) As "WP Progress ROC 6" ,

E.G1_PROGRESS  As "WP Progress ROC 1",
E.G2_PROGRESS  As "WP Progress ROC 2",
E.G3_PROGRESS  As "WP Progress ROC 3",
E.G4_PROGRESS  As "WP Progress ROC 4",
E.G5_PROGRESS  As "WP Progress ROC 5",
E.G6_PROGRESS  As "WP Progress ROC 6",

--C.PLAN_UNITS * (ROUND(E.G1H/C.PLANNEDHOURS,2)) as "Qty Planned 1",
--C.PLAN_UNITS * (ROUND(E.G2H/C.PLANNEDHOURS,2)) as "Qty Planned 2",
--C.PLAN_UNITS * (ROUND(E.G3H/C.PLANNEDHOURS,2)) as "Qty Planned 3",
--C.PLAN_UNITS * (ROUND(E.G4H/C.PLANNEDHOURS,2)) as "Qty Planned 4",
--C.PLAN_UNITS * (ROUND(E.G5H/C.PLANNEDHOURS,2)) as "Qty Planned 5",
--C.PLAN_UNITS * (ROUND(E.G6H/C.PLANNEDHOURS,2)) as "Qty Planned 6",


Case When E.G1H > 0 Then C.PLAN_UNITS Else null End as "Qty Planned 1",
Case When E.G2H > 0 Then C.PLAN_UNITS Else null End as "Qty Planned 2",
Case When E.G3H > 0 Then C.PLAN_UNITS Else null End as "Qty Planned 3",
Case When E.G4H > 0 Then C.PLAN_UNITS Else null End as "Qty Planned 4",
Case When E.G5H > 0 Then C.PLAN_UNITS Else null End as "Qty Planned 5",
Case When E.G6H > 0 Then C.PLAN_UNITS Else null End as "Qty Planned 6",


--C.PLAN_UNITS * (ROUND(E.G1H/C.PLANNEDHOURS,2)) * ROUND(E.G1A /  E.G1H,2)  as "Qty Completed 1",
--C.PLAN_UNITS * (ROUND(E.G2H/C.PLANNEDHOURS,2)) * ROUND(E.G2A /  E.G2H,2)  as "Qty Completed 2",
--C.PLAN_UNITS * (ROUND(E.G3H/C.PLANNEDHOURS,2)) * ROUND(E.G3A /  E.G3H,2)  as "Qty Completed 3",
--C.PLAN_UNITS * (ROUND(E.G4H/C.PLANNEDHOURS,2)) * ROUND(E.G4A /  E.G4H,2)  as "Qty Completed 4",
--C.PLAN_UNITS * (ROUND(E.G5H/C.PLANNEDHOURS,2)) * ROUND(E.G5A /  E.G5H,2)  as "Qty Completed 5",
--C.PLAN_UNITS * (ROUND(E.G6H/C.PLANNEDHOURS,2)) * ROUND(E.G6A /  E.G6H,2)  as "Qty Completed 6",

Round(C.PLAN_UNITS * E.G1_PROGRESS,2) as "Qty Completed 1",
Round(C.PLAN_UNITS * E.G2_PROGRESS,2) as "Qty Completed 2",
Round(C.PLAN_UNITS * E.G3_PROGRESS,2) as "Qty Completed 3",
Round(C.PLAN_UNITS * E.G4_PROGRESS,2) as "Qty Completed 4",
Round(C.PLAN_UNITS * E.G5_PROGRESS,2) as "Qty Completed 5",
Round(C.PLAN_UNITS * E.G6_PROGRESS,2) as "Qty Completed 6",

SUM(E.G1_QTYCOMPLETE) as G1_QTYCOMPLETE,
SUM(E.G2_QTYCOMPLETE) as G2_QTYCOMPLETE,
SUM(E.G3_QTYCOMPLETE) as G3_QTYCOMPLETE,
SUM(E.G4_QTYCOMPLETE) as G4_QTYCOMPLETE,
SUM(E.G5_QTYCOMPLETE) as G5_QTYCOMPLETE,
SUM(E.G6_QTYCOMPLETE) as G6_QTYCOMPLETE,

A.WEIGHTAGE As "WEIGHTAGE",A.RESOURCECODE As "RESOURCECODE",
A.WORKPHASE As "WORKPHASE",A.PROGRESSGROUPING As "PROGRESSGROUPING",A.CWPNUMBER as "CWPNUMBER",
A.FIWPJOBNUMBER AS "JOB NO" --ADDED ON 20260513

  
  INTO #D7650REGISTER
  
  FROM  #D7650COMBINED A With(Nolock)
  LEFT JOIN #D7650SPCCWP B ON A.CWPOBID = B.CWPOBID 
  LEFT JOIN #D7650TOTALPLANHRS C ON C.FIWPUID=A.FIWPUID And A.ACTIVITYCODE = C.ACTIVITYCODE
  LEFT JOIN #D7650GET_USERINFO D ON D.PROJECT=A.PROJECT AND D.WPNO=A.WPNO
  LEFT JOIN #D7650GATE E ON E.FIWPUID=A.FIWPUID  
  --WHERE A.FIWPUID='cbf3ae65-15a4-478b-a0fb-cb1006b058e6'
  GROUP BY A.PROJECT,  A.FIWPUID, 
  --B.WBSPATH,  
  A.WPNO, A.WPDESCRIPTION, B.NAME  

  -- , B.DESIGNAREA COMMENTED ON 20260513

  , A.ACTIVITYCODE, --B.WBSPATH, 
  A.DISCIPLINE, B.DESCRIPTION, A.SEQUENCE, 
  --B.BUDGETEDLABORHOURS, 
  A.FIWPAFCHRS,
  C.PLANNEDHOURS, C.CUMEARNED, C.BALANCE, C.CUMPROGRESS,
  A.REVDATE, A.RECEDATE,A.FIWPTASKNO,D.CREATIONUSER, D.CREATIONDATE, A.CREATIONUSER, A.CREATIONDATE, A.PREV_PROGRESS,  A.PREV_EARNED, A.PREV_WKLYEARNED
 , E.G1, E.G2, E.G3, E.G4, E.G5, E.G6
 ,  E.G1H/C.PLANNEDHOURS
 ,  E.G2H/C.PLANNEDHOURS
 ,  E.G3H/C.PLANNEDHOURS
 ,  E.G4H/C.PLANNEDHOURS
 ,  E.G5H/C.PLANNEDHOURS
 ,  E.G6H/C.PLANNEDHOURS,
  E.G1H,
  E.G2H,
  E.G3H,
  E.G4H,
  E.G5H,
  E.G6H,
  E.G1A,
  E.G2A,
  E.G3A,
  E.G4A,
  E.G5A,
  E.G6A, E.QTYCOMPLETE, E.QTYPLANNED, 
  --A.RATEUOM, 
  E.COUNT_COMPLETE, E.COUNT_PLANNED, A.PURPOSE, A.AREA, A.FOREMAN,A.FOREMAN,A.GENERALFOREMAN,A.ISSUEDBY, A.STATUS,   
  A.PLANNEDSTARTDATE, A.PLANNEDFINISHDATE, A.ACTUALSTARTDATE, A.ACTUALFINISHDATE, B.EARLYSTARTDATE,	B.EARLYFINISHDATE, B.LATESTARTDATE, B.LATEFINISHDATE, B.EWPNUMBER ,   C.PLAN_UNITS,  A.WP_REVNO,
  E.G1_PROGRESS,
  E.G2_PROGRESS,
  E.G3_PROGRESS,
  E.G4_PROGRESS,
  E.G5_PROGRESS,
  E.G6_PROGRESS, FIWPOBID,A.WEIGHTAGE ,A.RESOURCECODE,A.WORKPHASE,A.PROGRESSGROUPING,A.CWPNUMBER,A.FIWPJOBNUMBER


 SELECT DISTINCT a."FIWPUID", FIWPOBID,
a."PROJECT",
a."FIWPTASKNO",
a."TASK NO",
a."JOB NO", --JOB NUMBER FROM FIWP

a."ACTIVITY CODE",
a."DISCIPLINE",
a."ACTIVITY ID",
a."WPNO",
a."WP DESCRIPTION",
a."WP_REVNO",
a."ACTIVITY ID DESCRIPTION",
a."AFC Hrs",
a."WP Hrs",
a."AFC WP DELTA Hrs",
a."AFC Progress",
a."AFC Earned Hrs",
ROUND(a."AFC Earned Hrs" - a."WP Earned Hrs" ,4) as "AFC WP Earned Delta Hrs",
ROUND(a."AFC WP Progress Delta", 4) as "AFC WP Progress Delta",
ROUND(a."WP Progress",4) as "WP Progress",
a."WP Earned Hrs",
a."WP Components Qty Planned",
a."WP Components Qty Complete",
a."PLAN_UNITS",
a."COMPLETED_UNITS",
a."RATEUOM",
a."WP PURPOSE",
a."WP Last Week Progress",
a."WP Last Week Earned",
a."WP Last Week Weekly Earned",
a."WP Weekly Progress",
a."WP Weekly Earned",
a."WP Components Count Complete",
a."WP Components Count Planned",
a."AREA",
a."STATUS",
a."WP Revision Date",
a."WP Receive Date",
a."WP Last Progress By",
a."WP Last Progress Date",
a."WP Creation User",
a."WP Creation Date",
a."Foreman",
a."General Foreman",
a."IWP Issued By",
a."WP Planned Start Date",
a."WP Planned Finish Date",
a."WP Actual Start Date",
a."WP Actual Finish Date",
a."L3 Forecast Start Date",
a."L3 Forecast Finish Date",
a."L3 Baseline Start Date",
a."L3 Baseline Finish Date",
a."ROC 1",
a."ROC 2",
a."ROC 3",
a."ROC 4",
a."ROC 5",
a."ROC 6",
a."ROC Weightage 1",
a."ROC Weightage 2",
a."ROC Weightage 3",
a."ROC Weightage 4",
a."ROC Weightage 5",
a."ROC Weightage 6",
a."WP Hrs ROC 1",
a."WP Hrs ROC 2",
a."WP Hrs ROC 3",
a."WP Hrs ROC 4",
a."WP Hrs ROC 5",
a."WP Hrs ROC 6",
a."WP Earned Hrs ROC 1",
a."WP Earned Hrs ROC 2",
a."WP Earned Hrs ROC 3",
a."WP Earned Hrs ROC 4",
a."WP Earned Hrs ROC 5",
a."WP Earned Hrs ROC 6",
a."WP Progress ROC 1",
a."WP Progress ROC 2",
a."WP Progress ROC 3",
a."WP Progress ROC 4",
a."WP Progress ROC 5",
a."WP Progress ROC 6",
a."Qty Planned 1",
a."Qty Planned 2",
a."Qty Planned 3",
a."Qty Planned 4",
a."Qty Planned 5",
a."Qty Planned 6",
a."Qty Completed 1",
a."Qty Completed 2",
a."Qty Completed 3",
a."Qty Completed 4",
a."Qty Completed 5",
a."Qty Completed 6",

a.G1_QTYCOMPLETE,
a.G2_QTYCOMPLETE,
a.G3_QTYCOMPLETE,
a.G4_QTYCOMPLETE,
a.G5_QTYCOMPLETE,
a.G6_QTYCOMPLETE,
a."WEIGHTAGE" ,a."RESOURCECODE",a."WORKPHASE",a."PROGRESSGROUPING",a."CWPNUMBER"

/*
 CASE WHEN "AFC Hrs"<"WP Hrs" then "WP Progress ROC 1"  else   ROUND(("WP Earned Hrs ROC 1" / nullif("ROC Weightage 1",0)) / nullif("AFC Hrs",0) ,3) end as "AFC Progress ROC 1",
 CASE WHEN "AFC Hrs"<"WP Hrs" then "WP Progress ROC 2"  else   ROUND(("WP Earned Hrs ROC 2" / nullif("ROC Weightage 2",0)) / nullif("AFC Hrs",0) ,3) end as "AFC Progress ROC 2",
 CASE WHEN "AFC Hrs"<"WP Hrs" then "WP Progress ROC 3"  else   ROUND(("WP Earned Hrs ROC 3" / nullif("ROC Weightage 3",0)) / nullif("AFC Hrs",0) ,3) end as "AFC Progress ROC 3",
 CASE WHEN "AFC Hrs"<"WP Hrs" then "WP Progress ROC 4"  else   ROUND(("WP Earned Hrs ROC 4" / nullif("ROC Weightage 4",0)) / nullif("AFC Hrs",0) ,3) end as "AFC Progress ROC 4",
 CASE WHEN "AFC Hrs"<"WP Hrs" then "WP Progress ROC 5"  else   ROUND(("WP Earned Hrs ROC 5" / nullif("ROC Weightage 5",0)) / nullif("AFC Hrs",0) ,3) end as "AFC Progress ROC 5",
 CASE WHEN "AFC Hrs"<"WP Hrs" then "WP Progress ROC 6"  else   ROUND(("WP Earned Hrs ROC 6" / nullif("ROC Weightage 6",0)) / nullif("AFC Hrs",0) ,3) end as "AFC Progress ROC 6" 
 */
 
 INTO #D7650FINAL
 
 FROM #D7650REGISTER a With(Nolock)  


Select 
 "FIWPOBID",
 "FIWPUID",
"PROJECT",
"TASK NO",
"JOB NO",
"ACTIVITY CODE",
"DISCIPLINE",
"ACTIVITY ID",
"WPNO",
"WP DESCRIPTION",
"WP_REVNO",
"ACTIVITY ID DESCRIPTION",
Round("AFC Hrs",2) As "AFC Hrs" ,
Round("WP Hrs",2) As "WP Hrs",
Round("AFC WP DELTA Hrs",2) As "AFC WP DELTA Hrs" ,
Round("AFC Progress",2) As "AFC Progress" ,
Round("AFC Earned Hrs",2) As "AFC Earned Hrs",
ROUND("AFC Earned Hrs" - ("WP Progress" * "WP Hrs"), 2) as "AFC WP Earned Delta Hrs",
Round("AFC WP Progress Delta",2) "AFC WP Progress Delta",

Round("WP Progress",4) as "WP Progress" ,
ROUND("WP Progress" * "WP Hrs" ,2) as "WP Earned Hrs",

--"WP Components Qty Planned",
--"WP Components Qty Complete",
"PLAN_UNITS",
"COMPLETED_UNITS",
"RATEUOM",
"WP PURPOSE",
Round("WP Last Week Progress",2) As "WP Last Week Progress",
Round("WP Last Week Earned",2) As "WP Last Week Earned",
Round("WP Last Week Weekly Earned",2) As "WP Last Week Weekly Earned",
Round("WP Weekly Progress",2) As "WP Weekly Progress",
--Round(CASE WHEN "AFC Hrs" < "WP Hrs" THEN Round("WP Progress",2) * Round("WP Hrs",2)  ELSE Round("WP Earned Hrs",2) END  - Round("WP Last Week Earned",2),2) AS "WP Weekly Earned" ,
Round(CASE WHEN "AFC Hrs" < "WP Hrs" THEN "WP Progress" * "WP Hrs"  ELSE "WP Earned Hrs" END  - "WP Last Week Earned",2) AS "WP Weekly Earned" ,
"WP Components Count Complete",
"WP Components Count Planned",
"AREA",
"STATUS",
"WP Revision Date",
"WP Receive Date",
"WP Last Progress By",
"WP Last Progress Date",
"WP Creation User",
"WP Creation Date",
"Foreman",
"General Foreman",
"IWP Issued By",
"WP Planned Start Date",
"WP Planned Finish Date",
"WP Actual Start Date",
"WP Actual Finish Date",
"L3 Forecast Start Date",
"L3 Forecast Finish Date",
"L3 Baseline Start Date",
"L3 Baseline Finish Date",
"ROC 1",
"ROC 2",
"ROC 3",
"ROC 4",
"ROC 5",
"ROC 6",
Round("ROC Weightage 1",2) As "ROC Weightage 1" ,
Round("ROC Weightage 2",2) As "ROC Weightage 2" ,
Round("ROC Weightage 3",2) As "ROC Weightage 3" ,
Round("ROC Weightage 4",2) As "ROC Weightage 4" ,
Round("ROC Weightage 5",2) As "ROC Weightage 5" ,
Round("ROC Weightage 6",2) As "ROC Weightage 6" ,


Round("WP Hrs ROC 1",2) As "WP Hrs ROC 1",
Round("WP Hrs ROC 2",2) As "WP Hrs ROC 2",
Round("WP Hrs ROC 3",2) As "WP Hrs ROC 3",
Round("WP Hrs ROC 4",2) As "WP Hrs ROC 4",
Round("WP Hrs ROC 5",2) As "WP Hrs ROC 5",
Round("WP Hrs ROC 6",2) As "WP Hrs ROC 6",

Round("WP Earned Hrs ROC 1",2) As "WP Earned Hrs ROC 1",
Round("WP Earned Hrs ROC 2",2) As "WP Earned Hrs ROC 2",
Round("WP Earned Hrs ROC 3",2) As "WP Earned Hrs ROC 3",
Round("WP Earned Hrs ROC 4",2) As "WP Earned Hrs ROC 4",
Round("WP Earned Hrs ROC 5",2) As "WP Earned Hrs ROC 5",
Round("WP Earned Hrs ROC 6",2) As "WP Earned Hrs ROC 6",

Round("WP Progress ROC 1",2) As "WP Progress ROC 1",
Round("WP Progress ROC 2",2) As "WP Progress ROC 2",
Round("WP Progress ROC 3",2) As "WP Progress ROC 3",
Round("WP Progress ROC 4",2) As "WP Progress ROC 4",
Round("WP Progress ROC 5",2) As "WP Progress ROC 5",
Round("WP Progress ROC 6",2) As "WP Progress ROC 6",

"Qty Planned 1",
"Qty Planned 2",
"Qty Planned 3",
"Qty Planned 4",
"Qty Planned 5",
"Qty Planned 6",
"Qty Completed 1",
"Qty Completed 2",
"Qty Completed 3",
"Qty Completed 4",
"Qty Completed 5",
"Qty Completed 6",

Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 1"  ELSE ROUND(("WP Earned Hrs ROC 1")/ ("AFC Hrs" * nullif("ROC Weightage 1",0)),2) END,2) as "AFC Progress ROC 1",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 2"  ELSE ROUND(("WP Earned Hrs ROC 2")/ ("AFC Hrs" * nullif("ROC Weightage 2",0)),2) END,2) as "AFC Progress ROC 2",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 3"  ELSE ROUND(("WP Earned Hrs ROC 3")/ ("AFC Hrs" * nullif("ROC Weightage 3",0)),2) END,2) as "AFC Progress ROC 3",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 4"  ELSE ROUND(("WP Earned Hrs ROC 4")/ ("AFC Hrs" * nullif("ROC Weightage 4",0)),2) END,2) as "AFC Progress ROC 4",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 5"  ELSE ROUND(("WP Earned Hrs ROC 5")/ ("AFC Hrs" * nullif("ROC Weightage 5",0)),2) END,2) as "AFC Progress ROC 5",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 6"  ELSE ROUND(("WP Earned Hrs ROC 6")/ ("AFC Hrs" * nullif("ROC Weightage 6",0)),2) END,2) as "AFC Progress ROC 6",


Round(("AFC Hrs" * "ROC Weightage 1"),2) as "AFC Hrs ROC 1",
Round(("AFC Hrs" * "ROC Weightage 2"),2) as "AFC Hrs ROC 2",
Round(("AFC Hrs" * "ROC Weightage 3"),2) as "AFC Hrs ROC 3",
Round(("AFC Hrs" * "ROC Weightage 4"),2) as "AFC Hrs ROC 4",
Round(("AFC Hrs" * "ROC Weightage 5"),2) as "AFC Hrs ROC 5",
Round(("AFC Hrs" * "ROC Weightage 6"),2) as "AFC Hrs ROC 6", 


Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 1"  ELSE ("WP Earned Hrs ROC 1")/ ("AFC Hrs" * nullif("ROC Weightage 1",0)) END * ("AFC Hrs" * nullif("ROC Weightage 1",0)),2) as "AFC Earned ROC 1",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 2"  ELSE ("WP Earned Hrs ROC 2")/ ("AFC Hrs" * nullif("ROC Weightage 2",0)) END * ("AFC Hrs" * nullif("ROC Weightage 2",0)),2) as "AFC Earned ROC 2",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 3"  ELSE ("WP Earned Hrs ROC 3")/ ("AFC Hrs" * nullif("ROC Weightage 3",0)) END * ("AFC Hrs" * nullif("ROC Weightage 3",0)),2) as "AFC Earned ROC 3",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 4"  ELSE ("WP Earned Hrs ROC 4")/ ("AFC Hrs" * nullif("ROC Weightage 4",0)) END * ("AFC Hrs" * nullif("ROC Weightage 4",0)),2) as "AFC Earned ROC 4",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 5"  ELSE ("WP Earned Hrs ROC 5")/ ("AFC Hrs" * nullif("ROC Weightage 5",0)) END * ("AFC Hrs" * nullif("ROC Weightage 5",0)),2) as "AFC Earned ROC 5",
Round(CASE WHEN "AFC Hrs" <= "WP Hrs" THEN "WP Progress ROC 6"  ELSE ("WP Earned Hrs ROC 6")/ ("AFC Hrs" * nullif("ROC Weightage 6",0)) END * ("AFC Hrs" * nullif("ROC Weightage 6",0)),2) as "AFC Earned ROC 6",
G1_QTYCOMPLETE as "QTY COMPLETE ROC 1",
G2_QTYCOMPLETE as "QTY COMPLETE ROC 2",
G3_QTYCOMPLETE as "QTY COMPLETE ROC 3",
G4_QTYCOMPLETE as "QTY COMPLETE ROC 4",
G5_QTYCOMPLETE as "QTY COMPLETE ROC 5",
G6_QTYCOMPLETE as "QTY COMPLETE ROC 6",
"WEIGHTAGE" ,"RESOURCECODE","WORKPHASE","PROGRESSGROUPING","CWPNUMBER"

From #D7650FINAL With(Nolock)

--where Isnull(STATUS,'') = 'Issued For Construction' 
 
-- #D7650region DROP TABLES
 DROP TABLE #D7650SPCRPT_CWP_IOBJECT_PROP_TMP;
DROP TABLE #D7650SPCRPT_CWP_DIRECT_PROP_TMP;
DROP TABLE #D7650SPCRPT_CWP_DIR_ENUM_PROP_TMP;
DROP TABLE #D7650SPCRPT_CWP_REL_PROP_TMP;
DROP TABLE #D7650SPCCWP;
DROP TABLE #D7650SPCRPT_WORKSTEP_IOBJ_PROP_TMP;
DROP TABLE #D7650SPCRPT_WORKSTEP_DIR_PROP_TMP;
DROP TABLE #D7650SPCRPT_WORKSTEP_REL_PROP_TMP;
DROP TABLE #D7650WorkStepsX;
DROP TABLE #D7650WorkSteps;
DROP TABLE #D7650SPCRPT_COMP_IOBJECT_PROP_TMP;
DROP TABLE #D7650SPCRPT_COMP_DIRECT_PROP_TMP;
DROP TABLE #D7650SPCRPT_COMPONENTITEM1;
DROP TABLE #D7650SPCRPT_FIWP_IOBJECT_PROP_TMP;
DROP TABLE #D7650SPCRPT_FIWP_DIRECT_PROP_TMP;
DROP TABLE #D7650SPCRPT_FIWP_DIR_ENUM_PROP_TMP;
DROP TABLE #D7650SPCRPT_FIWP_REL_PROP_TMP;
DROP TABLE #D7650COMBINED;
DROP TABLE #D7650BY_WORKPACK;
DROP TABLE #D7650GET_USERINFO;
DROP TABLE #D7650TOTALPLANHRS;
DROP TABLE #D7650BYGATES1;
DROP TABLE #D7650COUNTINFO;
DROP TABLE #D7650GATE;
DROP TABLE #D7650REGISTER;
DROP TABLE #D7650FINAL;
DROP TABLE #D7650FIWPTOTAL;
DROP TABLE #D7650BYGATES;
-- #D7650endregion